### ISSUE TITLE
Implement Sequential Monte Carlo

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1304]
This issue tracks progress towards implementing Sequential Monte Carlo aka Particle Filtering.

For general control flow this appears to be difficult due to Python's lack of forkable coroutines.

For static computation graphs we may be able to implement tensorized forking via sparse tensors.

**Comment by jpchen** [comment]
may be useful but extremely outdated: @OptimusLime 's [implementation](https://github.com/uber/pyro/tree/nightmare-poutine) using OS forking iirc

**Comment by ndepalma** [comment]
I'd love this feature. Maybe you could start small with a limited example (non-language support). I'm currently evaluating some of these probabilistic languages and it looks like only Gen has support for SMC. 

I'd be glad to help you all out if you're currently working on an implementation.
