### ISSUE TITLE
conda support in the future

### ISSUE THREAD

**Issue by CompRhys** [pyro-ppl/pyro#1494]
My research group is looking at whether to use pyro vs gpflow for a new project, I am inclined towards pyro due to prefering pytorch to tensorflow. 

However, for ease of workflow our PI is very keen on ensuring that we use conda for maintaining environments within the group now that the HPC cluster we have access to has adopted conda. Would it be possible to get a conda release of pyro-ppl?

**Comment by fehiepsi** [comment]
You can use `pip` in conda to install pyro, so I guess there is no need to have a conda release at this *alpha* stage. Writing a conda build receipt for pyro is easy so I think that pyro's devs will make it available in the next version of pyro.

**Comment by CompRhys** [comment]
My hand may be forced before then but that’s great to know! Thanks for your work

**Comment by jpchen** [comment]
what is the difference between pip installing and conda installing in your conda environment?  as @fehiepsi said, i use them interchangeably and observe no difference. if you `conda list` you can see all your installed packages from both conda and pip.

**Comment by fritzo** [comment]
> @jpchen what is the difference between pip .. and conda

I don't understand fully, but I believe `conda indstall torch` can install a more system-tailored version of `torch` than `pip install torch`. And if we want to trigger that conda install via `___ install pyro`, we would also need to publish a conda package. If this is not the case, then we can simply ask conda users to use our pip package, e.g.
```yml
# in environment.yml
name: some_conda_package
dependencies:
- torch
- pip:
  - pyro
```

**Comment by fritzo** [comment]
@CompRhys Can you give us some specific reasons to create a conda package, rather than simply using `-pip -pyro` in your `environment.yml` file?

**Comment by CompRhys** [comment]
Sadly it's just group politics, in trying to pre-empt issues I thought it might be used as a reason not to swap.

**Comment by CompRhys** [comment]
@jpchen I have already used pyro as described for personal tests, this was a simple quality of life inquiry for non-technical potentially irrational reasons.
