### ISSUE TITLE
add listicle with common gotchas and solutions

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/pyro#1677]
- [ ] forgetting `param` or `module`
- [ ] forgetting to constrain things like `scale` to be positive
- [ ] maybe some generic advice about stochastic optimization (try a lower learning rate!)
- [ ] what else?

**Comment by jpchen** [comment]
where would this list live? some of these can be more adequately addressed as warnings

**Comment by fehiepsi** [comment]
I think wiki is a good place. :)

**Comment by fritzo** [comment]
Closing as I believe @martinjankowiak addressed this in http://pyro.ai/examples/svi_part_iv.html
