### ISSUE TITLE
[FR] Graph Neural Network Support

### ISSUE THREAD

**Issue by kitaev-chen** [pyro-ppl/pyro#1733]
Hi there,

I'm digging ppl tools for graph neural network. Originally I thought pyro should be very easy to implement these but after reading documents it's not obviously to find even an implement for GCN. 

I also found some libraries which has already implement some, such as euler (https://github.com/alibaba/euler), geometric (https://github.com/rusty1s/pytorch_geometric/tree/master/torch_geometric/nn/conv), etc. Will pyro plan to support GNNs in the future?

Best

**Comment by eb8680** [comment]
[DGL](https://www.dgl.ai/) seems like a nice graph neural network library with PyTorch support which you could use with Pyro.  Can you be more specific about what functionality you want to see Pyro provide?  Graph neural networks are not probabilistic models, although you can imagine them as performing certain kinds of approximate message-passing algorithms on factor graphs.

**Comment by eb8680** [comment]
Closing as addressed by [DGL](https://www.dgl.ai/), feel free to reopen if you have a Pyro-specific feature in mind.
