### ISSUE TITLE
[feature request] add arbitrary sampling of latent and intermediate values

### ISSUE THREAD

**Issue by elbamos** [pyro-ppl/pyro#1756]
### Issue Description

It would be helpful to be able to apply sampling statements to intermediate values (values that are neither parameters nor the product of sample sites), in order to increment the log prob in MCMC, or add gradient in SVI. 

This issue arises in models that are highly constrained and/or involve a lot of intermediate math applied to parameters.

As a simple example:  In certain time series models, we sample a starting price and a vector of periodic log-returns which are then `cumsum`'d.  If the number of periods is large then, especially in the early stages of sampling (or if the sampler tries to use step sizes that are too high...) it is not uncommon for the vector to, at some point, exceed constraints or even the range of the variable type.

One way of dealing with this in other ppl's, is to add a sampling statement with very broad values.   For example, I might constrain the price series to be in `uniform(0, 1e6)`.   Or, in Stan, throw a `reject()` statement.  I don't see a way of doing either in Pyro?

**Comment by eb8680** [comment]
Hi @elbamos, this seems like a reasonable request but I'm not sure I fully understand what you're asking for.  You can use `pyro.sample` to add constraints; I believe NUTS should handle the following correctly:
```python
def model(...):
    ...
    x = pyro.sample("x", Normal(...))
    y = f(x)
    pyro.sample(Uniform(0, 1e6), obs=y)
    ...
```
If that's not what you had in mind, could you provide a Stan example that does what you want or maybe write a piece of Pyro model pseudocode that doesn't currently run but demonstrates the extra syntax/functionality you'd like to see?

**Comment by elbamos** [comment]
Thanks! I had not considered using the `obs` parameter in that way.  That may work.  Let me try it and see.

**Comment by elbamos** [comment]
@eb8680 You're correct.    

Before your comment, I had been under the impression, based on reading examples such as http://pyro.ai/examples/mcmc.html, that calling `theta = pyro.sample("theta", dist.HalfCauchy([something]))` was sufficient to set a prior on theta.  

I now realize that was incorrect.
