### ISSUE TITLE
Redirect docs.pyro.ai to a 'stable' endpoint

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1761]
## Problem
Currently docs.pyro.ai redirects to http://docs.pyro.ai/en/0.3.1/. This prevents search engines from aggregating links. For example if I search for "pyro poutine", google currently points me to https://docs.pyro.ai/en/0.2.1-release/poutine.html which is old documentation.

## Proposed solution
If we instead redirected to http://docs.pyro.ai/en/stable/ then search engines would point to the latest stable documentation. This is how PyTorch docs work.

**Comment by fritzo** [comment]
This might also help avoid url churn as in #1757

**Comment by jpchen** [comment]
done
