### ISSUE TITLE
[FR] Improve save_visualization's functionality

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#1769]
It is my first time to use `save_visualization` function. But it does not work as my expect. Here is the output of the model in Bayesian regression tutorial:

![image](https://user-images.githubusercontent.com/4736342/52992983-8646f980-33e0-11e9-94c3-bbee9101ccb0.png)

The output only displays random variables in an order and adds colors to the nodes. It does not capture dependency.

I think that `save_visualization` will be more useful if we can add dependency information for simple models by using `torch.jit.get_trace_graph` (or something similar).

**Comment by eb8680** [comment]
This might be useful but is probably not straightforward to implement, though PRs are certainly welcome.  Let's track this in #1502 and close this issue as a duplicate.
