### ISSUE TITLE
add weight parameter for the NLL and KL term in ELBO

### ISSUE THREAD

**Issue by yikuanli** [pyro-ppl/pyro#1777]
I find that when the number of parameters increase, the model is impossible to train with current ELBO, since the KL term basically prevent the network from learning anything, which is why we need a parameter to reduce the weight of KL term. 

is there anyway to do that right now ?

### Guidelines

**NOTE:** Issues are for bugs and feature requests only. If you have a question about using Pyro or general modeling questions, please post it on the [forum](https://forum.pyro.ai/).

If you would like to address any minor bugs in the documentation or source, please feel free to contribute a Pull Request without creating an issue first. 

Please tag the issue appropriately in the title e.g. [bug], [feature request], [discussion], etc.

Please provide the following details:
--------------------------------------------------------------------------------------------------
### Issue Description
Provide a brief description of the issue.

### Environment
For any bugs, please provide the following:
 - OS and python version.
 - PyTorch version, or if relevant, output of `pip freeze`.
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'`

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

**Comment by karalets** [comment]
Check out the ‘custom objectives’ in the pyro examples. There is an example
of kl annealing, both in code and well documented as a tutorial.

That should probably answer your question, else please ask again here.

**Comment by jpchen** [comment]
as @karalets said, the air, dmm, and ss-vae tutorials have examples of annealing, as it is also in the [custom objectives tutorial](http://pyro.ai/examples/custom_objectives.html#Example:-KL-Annealing).  as noted in your issue, please post pyro usage questions on the [forum](https://forum.pyro.ai) so that others may benefit from your questions.
