### ISSUE TITLE
[discussion] Pyro sets all Parameters to requires_grad=True

### ISSUE THREAD

**Issue by cfperez** [pyro-ppl/pyro#1778]
### Issue Description
pyro.module() set `requires_grad=True` fo all `nn.Parameters` in a module, even if they were created with `requires_grad=False`.

Using `register_buffer()` solves this problem, but requires changing code that otherwise works in PyTorch.

It is hard to see how this would not be considered unexpected behavior. The question is how important is it, and if it is worth changing the behavior (and risk breaking other code?) or simply logging a warning + adding documentation.

### Environment
 - OSX, Python 3.6
 - PyTorch 1.0
 - Pyro 0.3.1

### Code Snippet

```py
import torch
import pyro

class Module(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.with_grad = torch.nn.Parameter(torch.zeros(1))
        self.no_grad = torch.nn.Parameter(torch.zeros(1), requires_grad=False)

m = Module()
assert m.with_grad.requires_grad
assert not m.no_grad.requires_grad

pyro_m = pyro.module('module', m)
assert pyro_m.with_grad.requires_grad
assert not pyro_m.no_grad.requires_grad
```

**Comment by fritzo** [comment]
Thanks for the report @cfperez . Can you clarify your expected/desired behavior? When a PyTorch param has `.requires_grad == False` does the parameter simply not get updated during training? If that is the case, I guess we could ignore such params in `pyro.module` and possible emit a warning recommending use of `register_buffer()` (so as to maintain plausible backwards compatibility with previous versions of Pyro).

**Comment by jpchen** [comment]
> does the parameter simply not get updated during training

yes, from [the pytorch docs](https://pytorch.org/docs/stable/notes/autograd.html#excluding-subgraphs)

> we could ignore such params in `pyro.module` and possible emit a warning recommending use of `register_buffer()`

i can make this fix; i think this might have been a later pytorch feature we didnt account for - i seem to remember that when `module` was implemented in pyro (~pytorch 0.2), `Parameter`s were defined to be `Variable`s with `requires_grad = True`.

**Comment by fritzo** [comment]
@jpchen I believe the correct behavior is to **skip** calling `pyro.param` inside `pyro.module` whenever the param has `.requires_grad == False`. Specifically, I believe changes should be limited to `pyro.module`, and there should be no changes required to `pyro.param`. Let me know if you disagree. Otherwise, thanks for implementing this!

**Comment by jpchen** [comment]
@cfperez what is your use case of non-grad parameters of a nn?  if you have fixed weights or non-learnable params can't you just not wrap it in `torch.nn.Parameter`?
