### ISSUE TITLE
No TransformedDistribution in pyro.distributions

### ISSUE THREAD

**Issue by createmomo** [pyro-ppl/pyro#1797]
--------------------------------------------------------------------------------------------------
### Issue Description
Unable to import TransformedDistribution in pyro.distributions, and Adam in pyro.optim. 

### Environment
For any bugs, please provide the following:
 - Ubuntu 16.04, python 3.6
 - PyTorch version, 1.0.1.post2
 - Pyro version: 0.3.1

### Code Snippet
I am using the code of DMM here:
https://github.com/pyro-ppl/pyro/blob/dev/examples/dmm/dmm.py

**Comment by neerajprad** [comment]
Could you paste the error trace that you are getting, and also the output of `pip freeze`? Note that `TransformedDistribution` is imported and wrapped automatically inside of Pyro.

**Comment by createmomo** [comment]
Hey, many thanks for your quick reply. I figured out the problem. There is no problem with the code. I think the bug is about PyCharm (it cannot recognise the wrapped pytorch classes in the code editor window). But I can run the code successfully. 

Thank you very much~
