### ISSUE TITLE
no Adam in pyro.optim

### ISSUE THREAD

**Issue by createmomo** [pyro-ppl/pyro#1798]
--------------------------------------------------------------------------------------------------
### Issue Description
There is no Adam in pyro.optim. But I can found it in the doc.

### Environment
For any bugs, please provide the following:
 - Ubuntu 16.04, python 3.6
 - PyTorch version, 1.0.1.post2
 - Pyro version: 0.3.1

### Code Snippet
I am using the code of HMM here:
from pyro.optim import Adam
https://github.com/pyro-ppl/pyro/blob/dev/examples/hmm.py

**Comment by neerajprad** [comment]
Let us follow up in #1797. I think the underlying issue is the same.
