### ISSUE TITLE
Unknown/missing/extra labels not be handled well in the sample function of a distribution

### ISSUE THREAD

**Issue by createmomo** [pyro-ppl/pyro#1823]
--------------------------------------------------------------------------------------------------
### Issue Description
Unknown/missing/extra labels not be handled well in the sample function of a distribution e.g. Categorical. I am not sure if this is a bug or enhancement.

### Environment
Ubuntu 18.04, pytorch 1.0.1, pyro 0.3.0

### Code Snippet
For example, in my situation, I have 2 labels, classA, classB. But some labels in my data are missing, I use the label **MIS** to indicate this situation. The indices of these three labels are 0,1,2 respectively.

**Problem:**
When I build emitter in HMM (from hidden state to observations of these labels), I only need a softmax which output the probability distribution of 2 labels, i.e. [classA, classB]. I don’t need the probability distribution [classA, classB, MIS]

But the problem is when I use the sample function, e.g.

pyro.sample(
dist.Categorical(distribution from softmax over classA and classB).mask(the mask that masked out the missing (MIS) labels, obs=observation)
)

The function seems cannot handle the extra class (MIS) well, just report an error (because in my observation I have some missing data, e.g. [0,1, 2], the index here 2 is not valid for the sample function). Thus I have to use the softmax output a distribution over 3 classes. However, the last one (MIS) is not needed for me.

Is there a better way to deal with this situation? Maybe for now I could just assign an arbitrary value within 0 or 1 for missing data because anyway they will be masked out by the corresponding mask.

**Comment by fritzo** [comment]
The canonical way to handle missing data in `pyro.sample` statements is to set `obs=None`, i.e. `None` is the canonical missing value.
```py
is_observed = (data != MIS).all()
pyro.sample("name", dist.Categorical(probs),
             obs=data if is_observed else None)
```
This works well for batches where each variable is either entirely observed or entirely missing within each batch.

To handle batches with heterogeneously missing values, I'd use [poutine.mask](http://docs.pyro.ai/en/stable/poutine.html#pyro.poutine.mask):
```py
is_observed = (data == MIS)
valid_data = data.clone()
valid_data[~is_observed] = 0  # ensure all values are valid
with poutine.mask(mask=is_observed):
    pyro.sample("name", dist.Categorical(probs),
                obs=valid_data)
```

If you have further questions, would you mind asking at http://forum.pyro.ai instead of github? The forum is a better place for questions because it is a little easier to find answered questions there. Thanks!

**Comment by createmomo** [comment]
> The canonical way to handle missing data in `pyro.sample` statements is to set `obs=None`, i.e. `None` is the canonical missing value.
> 
> ```python
> is_observed = (data != MIS).all()
> pyro.sample("name", dist.Categorical(probs),
>             obs=data if is_observed else None)
> ```
> 
> This works well for batches where each variable is either entirely observed or entirely missing within each batch.
> 
> To handle batches with heterogeneously missing values, I'd use [poutine.mask](http://docs.pyro.ai/en/stable/poutine.html#pyro.poutine.mask):
> 
> ```python
> is_observed = (data == MIS)
> valid_data = data.clone()
> valid_data[~is_observed] = 0  # ensure all values are valid
> with poutine.mask(mask=is_observed):
>     pyro.sample("name", dist.Categorical(probs),
>                 obs=valid_data)
> ```
> 
> If you have further questions, would you mind asking at http://forum.pyro.ai instead of github? The forum is a better place for questions because it is a little easier to find answered questions there. Thanks!

Hi fritzo, many thanks for your quick and nice reply. I will post my questions in the forum.

**Comment by zhangqimin17** [comment]
My data is a matrix and there are missing values in it. I tried to use the `poutine.mask` function:
```
def matrix_factorization(anime_matrix, k = k):
    
    m = anime_matrix.shape[0]
    n = anime_matrix.shape[1]
    
    #anime_matrix = Variable(torch.FloatTensor(anime_matrix.values))
    
    u_mean = Variable(torch.zeros([m, k]))
    u_sigma = Variable(torch.ones([m, k]) * sigma_u)

    v_mean = Variable(torch.zeros([n, k]))
    v_sigma = Variable(torch.ones([n, k]) * sigma_v)

    u = pyro.sample("u", dist.Normal(loc = u_mean, scale = u_sigma).independent(2))
    v = pyro.sample("v", dist.Normal(loc = v_mean, scale = v_sigma).independent(2))
    
    expectation = torch.mm(u, v.t())
    is_observed = (~np.isnan(anime_matrix))
    is_observed = torch.tensor(is_observed)
    valid_matrix = torch.tensor(anime_matrix).clone()
    valid_matrix[~is_observed] = 0  # ensure all values are valid
    with pyro.poutine.mask(mask=is_observed):
        pyro.sample("obs", dist.Normal(expectation, Variable(torch.ones([m, n]) * sigma)).independent(2), 
                    obs = valid_matrix)
```

but when training, it returns:

```
ValueError: at site "obs", invalid log_prob shape
  Expected [], actual [100, 200]
  Try one of the following fixes:
  - enclose the batched tensor in a with plate(...): context
  - .to_event(...) the distribution being sampled
  - .permute() data dimensions
```

**Comment by fehiepsi** [comment]
`zhangqimin17` masks out `log_prob`. If you use `.independent(2)`, then `log_prob` will be scalar, so it can't be masked by `is_observed`. You can add some `pyro.plate` statements to declare batch dimensions (more information can be found at [this tutorial](http://pyro.ai/examples/tensor_shapes.html)).

FYI, the name `.independent` causes confusions, so in Pyro, we renamed it to `.to_event`.

**Comment by zhangqimin17** [comment]
@fehiepsi Thanks for your reply!

**Comment by fritzo** [comment]
Also, an alternative to using a plate here is to use the distribution's `.mask()` method, as in
```py
pyro.sample("obs",
            dist.Normal(expectation, Variable(torch.ones([m, n]) * sigma))
                .independent(2).mask(is_observed), 
            obs = valid_matrix)
```
It depends on your problem whether it is easier to use `poutine.mask()` with a plate versus `Distribution.mask()`.

**Comment by zhangqimin17** [comment]
@fritzo looks good, thank you！
