### ISSUE TITLE
Confusion in the KL and ELBO definitions

### ISSUE THREAD

**Issue by CedricGarzotto** [pyro-ppl/pyro#1829]
During the reading of the pyro tutorial, in the chapter 2, I notice a problem during the ELBO definition. The definition of the ELBO given is mathematically the definition of the Kullback-liebler divergence, and the définition of KL is the one of the ELBO.

The link of the chapter : http://pyro.ai/examples/svi_part_i.html

I would now if it's normal and in that case what is the reason.

Thank you for your attention.

**Comment by karalets** [comment]
Dear Cedric,

I cannot reproduce your concern, the math in the link looks fine to me. Can
you please point more specifically? Maybe it is not clear which section you
mean.

Also: the elbo can be derived from the kl divergence of the variational
approximation to the true posterior, which is how this is set up in the
example.

**Comment by jpchen** [comment]
i'm not sure what your question is. as @karalets said, the elbo is the negative KL + log evidence. for a more in-depth derivation, perhaps take a look at [this overview](https://arxiv.org/pdf/1601.00670.pdf).

also, issues are for bug reports and feature requests regarding pyro.  please post these types of questions on the [forum](http://forum.pyro.ai) so others may benefit from the answer as well.

**Comment by CedricGarzotto** [comment]
I just notice that the ELBO is defined with p(x,z), that is a result in itself... sorry the definition is correct, I'm just disturbed by the fact that you start by the need ELBO and not by the KL divergence as used to be in mathematics.
