### ISSUE TITLE
LDA tutorial: incorrect tensor shape when document size is larger than the vocabulary size

### ISSUE THREAD

**Issue by curtis999** [pyro-ppl/pyro#1841]
https://github.com/pyro-ppl/pyro/blob/56c06176763f1676bd586c89b2dc503c64315f0a/examples/lda.py#L101

The filler array of ones should have expanded into the size of the sliced data. This is problematic when the number of words per document is larger than the vocabulary size
Try 
`counts.scatter_add_(0, data[:, ind], torch.tensor(1.).expand(data[:,ind].shape))`
instead

**Comment by fritzo** [comment]
Thanks @curtis999 for the report and fix! Do you have a simple example we can add as a regression test? It can be totally random data.

**Comment by curtis999** [comment]
@fritzo the error can be replicated simply by passing `-w 63` or whatever that sets the vocabulary size to be smaller than the total number of words in a document.

In the example, the data is from the generative model, or we can explicatly generate it with 
```
theta = dist.Dirichlet(torch.zeros([args.num_docs, args.num_topics]) + 0.2).sample()
phi = dist.Dirichlet(torch.zeros([args.num_topics, args.num_words]) + 0.1).sample()
z = dist.Categorical(theta).expand([args.num_words_per_doc, args.num_docs]).sample()
data = dist.Categorical(phi[z]).sample()
```
