### ISSUE TITLE
Reorganizing transforms and normalizing flows? [discussion]

### ISSUE THREAD

**Issue by stefanwebb** [pyro-ppl/pyro#1869]
There are quite a few normalizing flows and other transforms in the `pyro.distributions` module. @fritzo What do you think about moving them to a separate `pyro.transforms` module? I think this also makes sense because they aren't distributions per se. And they could be automatically copied into `pyro.distributions` like `torch.distributions` is for backwards compatibility

**Comment by martinjankowiak** [comment]
cc @neerajprad

**Comment by fritzo** [comment]
We've historically thought of `pyro.distributions` as a component that is independent of the rest of Pyro and that extends `torch.distributions`. From that view, it seems like a nice organization would be `pyro.distributions.transforms`, extending the existing `torch.distributions.transforms`.

**Comment by stefanwebb** [comment]
After my two most recent flows #1887 #1890 have been merged, I'll push the reorganization into `pytorch.distributions.transform`

**Comment by stefanwebb** [comment]
Complete as of #1908
