### ISSUE TITLE
scipy imresize is deprecated

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#1871]
`imresize` is used in `air` example, but it is deprecated now. We need to replace it by something else to make tests pass.

More context about this issue: `imresize` is used in [observations](https://github.com/edwardlib/observations) but this library is deprecated now in favour of tensorflow [datasets](https://github.com/tensorflow/datasets). But multi-mnist is not available in tensorflow's datasets yet. So I'm not sure what is a good solution for this issue.

**Comment by neerajprad** [comment]
The problem is with the `observations` library (that uses this function) which is not being maintained anymore. I think we need to remove dependency on `observations`.

**Comment by null-a** [comment]
> We need to replace it by something else

The [docs](https://docs.scipy.org/doc/scipy-1.2.0/reference/generated/scipy.misc.imresize.html) suggest using `numpy.array(Image.fromarray(arr).resize())` inplace of `imresize`. This requires `PIL` which AIR already has as a dependency.
