### ISSUE TITLE
Incompatibility with numpy 1.16.3?

### ISSUE THREAD

**Issue by mattwescott** [pyro-ppl/pyro#1873]
### Description

On a native conda installation, `make test` fails at 0f6b7689440310cfb2dffdc2cde3918d6132eb65 seemingly due to numpy incompatibility

### Details

On `osx==10.14`, with `conda==4.6.14` and `python=3.7.3`:

```
git checkout 0f6b76
conda update -n root conda
conda create -n pyro python=3
conda activate pyro
make install
make test
```

Error: `numpy.ufunc size changed, may indicate binary incompatibility`
[full output](https://github.com/pyro-ppl/pyro/files/3200006/make_test1.txt)
[`pip freeze`](https://github.com/pyro-ppl/pyro/files/3200008/pip_freeze.txt)

### Temporary resolution

Downgrading numpy via `pip install numpy==1.15.0` seems to have `make test` happy.

**Comment by fritzo** [comment]
@neerajprad I have also seen this error often. Can we simply ignore it in conftest.py or setup.cfg (as is recommended by scipy)? I tried to modify our configs but gave up.
