### ISSUE TITLE
Evaluate risk from in-place operations in `tracegraph_elbo`

### ISSUE THREAD

**Issue by mattwescott** [pyro-ppl/pyro#1893]
In discussing #1891 @fritzo raised the possibility of in-place operations being an issue for jit tracing. 

My impression from [the torch docs](https://pytorch.org/docs/stable/jit.html#tracing-edge-cases) is that in-place operations on views are to be avoided (and will result in a warning).

It looks like these tracer warnings are being ignored in most of the tests in `test_jit`. Is that important? If it would be easy to miss introducing a problematic in-place operation on a view, would it reduce risk to avoid in-place operations entirely, even where it is currently safe?

**Comment by fritzo** [comment]
In general all new code in Pyro should avoid in-place ops. I believe `TraceGraph_ELBO` was one of the earlier elbos.

**Comment by fritzo** [comment]
Thanks for opening this @mattwescott . I think I'll close it now, since the PyTorch jit has been increasing support for in-place ops.
