### ISSUE TITLE
Graph retention in JitTraceGraph_ELBO

### ISSUE THREAD

**Issue by mattwescott** [pyro-ppl/pyro#1894]
In reviewing #1891, @martinjankowiak  noted that `JitTraceGraph_ELBO` isn't using `retain_graph`. It could make sense to simply switch to `backward(retain_graph=self.retain_graph)`. I'm reluctant to do that without some understanding of how graph retention interacts with jit.

**Comment by fritzo** [comment]
Graph retention should be independent of the jit because `.backward()` and `grad()` cannot be called within the jit. I believe the `retain_graph` arg has been missing simply because nobody had needed it.

**Comment by mattwescott** [comment]
Alright, went ahead and added the fix to #1891. This will be closed automatically when it is merged.
