### ISSUE TITLE
No pyro distributions for torch >=1.1

### ISSUE THREAD

**Issue by AishwaryaHB** [pyro-ppl/pyro#1898]
My PyTorch version is 1.0.1, trying to install pyro using "pip install pyro-ppl"

I run into an error that says:
ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 (from pyro-ppl) (from versions: 0.1.2, 0.1.2.post1)
ERROR: No matching distribution found for torch>=1.1.0 (from pyro-ppl)

This happens once it starts "Collecting torch>=1.1.0 (from pyro-ppl)"

**Comment by fritzo** [comment]
I believe you'll need to either upgrade your torch
```
pip install -U torch  # Or use conda or other method.
```
or downgrade pyro
```
pip install pyro-ppl==0.3.0  # Maybe this version works.
```
Can you please print some system info so we can help determine why your torch is not upgrading?

**Comment by neerajprad** [comment]
@AishwaryaHB - If you continue to have installation problems, please feel free to post your question on the [forum](https://forum.pyro.ai/).
