### ISSUE TITLE
Cannot delete constrained parameter [bug]

### ISSUE THREAD

**Issue by NoAxioms** [pyro-ppl/pyro#1901]
### **Issue Description**
Deleting a constrained parameter throws an error.
In the function `param_store.__delitem__()`, the line 
`unconstrained_value = constrained_value.unconstrained()`
throws
`AttributeError: 'Tensor' object has no attribute 'unconstrained'`

### **Environment**
OS: Windows 8.1
Python Version: 3.6.8
Pytorch Version: 1.1.0
Pyro Version: 0.3.3

This error was also present using Pytorch 1.0 and Pyro 0.3.1.
### **Code Snippet**
```py
import torch
import pyro
from torch.distributions import constraints

param_store = pyro.get_param_store()
a = pyro.param('a', torch.ones(3))
print(param_store.keys())  #dict_keys(['a'])
param_store.__delitem__('a')  #Works fine
print(param_store.keys())  #dict_keys([])
b = pyro.param('b', torch.ones(3), constraint=constraints.positive)
print(param_store.keys())  #dict_keys(['b'])
param_store.__delitem__('b')  #AttributeError: 'Tensor' object has no attribute 'unconstrained'
```

**Comment by fritzo** [comment]
Thanks for the clear failing example @NoAxioms ! I'll take a look.
