### ISSUE TITLE
System Usage with NUTS

### ISSUE THREAD

**Issue by jburroni** [pyro-ppl/pyro#1912]
While running NUTS on cpu, a big part of the CPU Load is devoted to System.
 This is a consequence of the CPU backend trying to split the work between several threads, even when using a single chain. In particular, this happens inside the calls to `logsumexp`

This is the performance monitor's visualization running NUTS with  a single chain:
![cpu-pyro](https://user-images.githubusercontent.com/2650090/59634665-505f1b00-911d-11e9-9612-37834293b82d.jpg)

 

The following code solves the issue:
```diff
--- a/pyro/infer/mcmc/nuts.py
+++ b/pyro/infer/mcmc/nuts.py
@@ -11,6 +11,14 @@ from pyro.infer.mcmc.hmc import HMC
 from pyro.ops.integrator import velocity_verlet
 from pyro.util import optional, torch_isnan

+
+def _logsumexp(vals, dim=0):
+    assert dim == 0
+    assert vals.shape == (2,)
+    M = vals[0] if vals[0] > vals[1] else vals[1]
+    p = (vals-M).exp().sum().log() + M
+    return p
+
 # sum_accept_probs and num_proposals are used to calculate
 # the statistic accept_prob for Dual Averaging scheme;
 # z_left_grads and z_right_grads are kept to avoid recalculating
@@ -219,7 +227,7 @@ class NUTS(HMC):
                                            direction, tree_depth-1, energy_current)

         if self.use_multinomial_sampling:
-            tree_weight = logsumexp(torch.stack([half_tree.weight, other_half_tree.weight]), dim=0)
+            tree_weight = _logsumexp(torch.stack([half_tree.weight, other_half_tree.weight]), dim=0)
         else:
             tree_weight = half_tree.weight + other_half_tree.weight
         sum_accept_probs = half_tree.sum_accept_probs + other_half_tree.sum_accept_probs
@@ -363,7 +371,7 @@ class NUTS(HMC):
                     break
                 else:  # update tree_weight
                     if self.use_multinomial_sampling:
-                        tree_weight = logsumexp(torch.stack([tree_weight, new_tree.weight]), dim=0)
+                        tree_weight = _logsumexp(torch.stack([tree_weight, new_tree.weight]), dim=0)
                     else:
                         tree_weight = tree_weight + new_tree.weight
```
Notice that I'm not proposing using this code, but only showing where the root of the problem is. 
### Environment
OS: OSX 10.13.6
PyTorch: 1.1.0
Pyro: 0.3.3+76b82785

**Comment by neerajprad** [comment]
Thanks a lot for submitting this issue. On the test examples, I don't see the system usage being that high. It is mostly within ~ 3% or so. It is possible that you only see this when the chains get really long, so while it may not depend on the model exactly, if possible could you share your model code (or a part of it) that I could use to try to replicate this on my system.

**Comment by neerajprad** [comment]
Running `logsumexp` in a loop as below (which is what the above code is doing) seems to not consume any significant incremental system level resources, so I think the issue might lie somewhere else.

```python
import torch

t = torch.randn(10000)
s = torch.randn(10000)

for i in range(10**6):
    print(i)
    torch.logsumexp(torch.stack([s, t], dim=0), dim=0)
```

**Comment by jburroni** [comment]
Thank you for the prompt reply.
I tried your snippet and it work perfectly, which is a bit  puzzling.

The following code reproduce the issue:
```python
import torch
from torch import tensor, rand
import pyro
import torch.distributions.constraints as constraints
import pyro.distributions as dist
from pyro.infer import mcmc


def model(x: 'int[10]'=None):
    theta: 'real' = pyro.sample('theta', dist.Uniform(0.0, 1.0))
    pyro.sample('theta' + '__1', dist.Beta(1, 1), obs=theta)
    for i in range(1, 10 + 1):
        pyro.sample('x' + '__{}'.format(i - 1) + '__2', dist.Bernoulli(
            theta), obs=x[i - 1])

x = torch.Tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])
def nuts(model, **kwargs):
    nuts_kernel = mcmc.NUTS(model)
    return mcmc.MCMC(nuts_kernel, **kwargs)

nuts(model, num_samples=10000, warmup_steps=100).run(x=x)
``` 

Surprisingly, after applying the patch I described above the issue was solved, but I don't know what could be.

**Comment by neerajprad** [comment]
I didn't see the system usage being high with this example either, but what I noticed was that this consumes a lot of CPU and depending on other load, might trigger the CPU fans / temperature control leading to high system usage. I think that's what is happening with this example. We should just use the `_logsumexp` implementation that you put in above which is much more optimized for the case where we have only two elements and is faster. Do you mind creating a Pull Request with your changes above?

I will also do some profiling and create a PyTorch issue if there is a need to have something like `logaddexp` or make `logsumexp` more efficient with small number of elements. This was really helpful, thanks for pointing out this inefficiency!

**Comment by jburroni** [comment]
done #1915
