### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by rojinsafavi** [pyro-ppl/pyro#1928]
Hello,

I went through your semi-supervised tutorial here: [https://pyro.ai/examples/ss-vae.html](url) , and I was wondering if it is possible to apply this model to a single prediction task(like a regression prediction) and not a classification?  basically replacing the classification part with a regression task (MLP with one output node that predicts a value)

**Comment by karalets** [comment]
sure, you could do that, if you changed the model appropriately and trained
it to do so.

In the generative model that would indicate something like two continuous
variables z_observed and z_unobserved, where occasionally you know
z_observed, which both generate the 'image' x, i.e.: P(x|z_o, z_u) P(z_u)
P(z_o)
and your inference models can account for them appropriately.

Changes necessary:
-change the model to have an appropriate continuous prior on the
observation that now is a categorical
-change the inference model to do Q_1(z_o|x) and then Q_2(z_u|z_o, x) via
two amortization networks q_1 and q_2.

Try it and let us know if it works.

**Comment by eb8680** [comment]
Closing, feel free to follow up on this question on the [forum](https://forum.pyro.ai/)
