### ISSUE TITLE
[FR] support divergence diagnostics for NUTS

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#1931]
Based on @riversdark [request](https://github.com/pyro-ppl/pyro/issues/1093#issuecomment-506943294), it would be convenient for users to be able to access to divergence information. Let's support that feature.

**Comment by robsalomone** [comment]
@fehiepsi Straightforward divergence counts should be simple (you just keep count of how often the energy is not conserved within a given tolerance, and ideally flag those samples to identify problem regions).  However, there is an  additional diagnostic (and more discussion about divergences) here
https://arxiv.org/abs/1604.00695

These are also in Stan (and only know to more advanced users). It could be worth implementing this as well.

**Comment by fehiepsi** [comment]
Thanks @robsalomone ! We might try to have the simple case first. To be honest, I don't know what `diverging` means in Stan and PyMC3 result. I thought that we just need to calculate the number of [diverging at this line](https://github.com/pyro-ppl/pyro/blob/dev/pyro/infer/mcmc/nuts.py#L34) for NUTS algorithm, that is the number of trajectories which end up with `delta_energy = new_energy - old_energy > 1000`. Do you know if that number matches `Stan/PyMC3` divergence diagnostic? In addition, is there also a `diverging` notion in HMC?

**Comment by robsalomone** [comment]
That’s correct @fehiepsi, it’s just used to flag areas of problematic curvature. Divergences usually indicate the chain is unlikely to be mixing well.  The precise number is in the Stan documentation somewhere I believe, but more or less it just needs to be some large number that would indicate the HMC integrator is failing (flies off due to overly steep gradient).

**Comment by fehiepsi** [comment]
@robsalomone Thanks for explaining! It is very helpful to me. I just find the number in the footnote of the [manual](https://mc-stan.org/docs/2_18/reference-manual/divergent-transitions.html). :)

**Comment by neerajprad** [comment]
Handled by @fehiepsi in #1942.
