### ISSUE TITLE
When should we drop support for Python 2?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1935]
Some of Pyro's dependencies are dropping support for Python 2: [pytest 5.0](https://docs.pytest.org/en/latest/py27-py34-deprecation.html), [numpy 1.17](https://github.com/numpy/numpy/pull/12506), [opt_einsum 3.0](https://github.com/dgasmith/opt_einsum/issues/79). I had been trying to hold out for as long as PyTorch supported Python 2, but this is increasingly difficult as Pyro's other dependencies drop support. I guess we should balance breakage between:
1. breaking users who actually use Python 2, and
2. breaking users who need newer versions of other packages (e.g. pytest, ipython).

### Poll results as of 2019-07-10:
- 20 to drop support
- 0 to keep support

**Comment by fritzo** [comment]
Upvote here to drop Python 2 support. You use Python 3 and need up-to-date versions of all libraries.

**Comment by fritzo** [comment]
Upvote here to keep Python 2 support. You still use Python 2 but you want the latest Pyro features.

**Comment by martinjankowiak** [comment]
wasn't pytorch planning on dropping python 2 support at some point anyway?

**Comment by fritzo** [comment]
Last I heard, @soumith wanted to keep Python 2 support because pypi download stats showed continued use (though I suspect those stats are dominated by ci builds rather than new installs).

**Comment by jpchen** [comment]
fwiw i know some academic users who use python 2, probably because it's the default version that ships with osx...

**Comment by fritzo** [comment]
Ok, our tentative plan is to cut one more patch release with Python 2 support, then drop Python 2 support in the next minor release [0.4](https://github.com/pyro-ppl/pyro/milestone/8).

**Comment by fritzo** [comment]
OK, does anyone want to get features into the final Python 2.7 release of Pyro? I think we can cut a patch release this week and then drop support for Python 2.7.
cc @neerajprad @fehiepsi

**Comment by neerajprad** [comment]
Discussed with @fritzo - we just have 1 or 2 PRs that we would like to get in with the new MCMC interface for the patch release. I think we should have everything in by Wednesday.

**Comment by neerajprad** [comment]
@fritzo - We have all MCMC related changes in dev, and I was planning to cut a patch release now. Is there anything else that you would like to get into this patch?

**Comment by fritzo** [comment]
@neerajprad Now is a great time to make a patch release. I'd prefer my current PRs not be in the release :smile:

**Comment by neerajprad** [comment]
pyro-0.3.4 is released. We can remove python 2 support in the next major release.

**Comment by fritzo** [comment]
Moving discussion to #1963
