### ISSUE TITLE
Need help with understanding of num_samples/ num_particles in SVI class.

### ISSUE THREAD

**Issue by sankrutyayan** [pyro-ppl/pyro#1968]
### Issue Description
I would like to know what num_particles/ num_samples in SVI class intuitively mean.

**Comment by neerajprad** [comment]
`num_particles` is an argument provided to the `ELBO` (`Trace_ELBO`, `TraceEnum_ELBO`) classes that determines the number of samples taken to form the monte carlo estimate of the ELBO (and also the surrogate term used to compute the gradient).

`num_samples` argument to SVI is not used during inference at all, and is only used to determine the number of model traces to generate from the approximate posterior when `SVI.run` is called. There is a possibility that this might be deprecated with #1930. 

Please feel free to post any follow-up questions to discuss on the [forum](https://forum.pyro.ai/) where topics are more easily discoverable and will benefit the larger community.
