### ISSUE TITLE
[bug] TraceGraph_ELBO inconsistent in sign of ELBO

### ISSUE THREAD

**Issue by sharrison5** [pyro-ppl/pyro#1982]
### Issue Description
 + `TraceGraph_ELBO.loss()` returns the negative ELBO (as expected).
 + `TraceGraph_ELBO.loss_and_grads()` returns the positive ELBO.

This doesn't affect the optimisation as the surrogate loss is based on the negative ELBO, but is confusing when monitoring convergence. May well happen in other ELBO classes, this is just the one that I've been using and hence spotted it in.

### Environment
MacOS, Python 3.7.1, PyTorch 1.1.0, Pyro 0.3.4

**Comment by JamesTrick** [comment]
I agree it seems a bit confusing. Not fully knowing the reasons behind the implementation, I would hazard a guess that pyro use a negative ELBO loss for minimization and use with optimizers, but ELBO (normally) is positive which is still helpful and accessible through `TraceGraph_ELBO.loss_and_grads()`?

**Comment by fritzo** [comment]
This is just a bug, any `ELBO` implementation should return the "elbo loss" = -elbo from `.loss_and_grads()`. Anyone have time to submit a quick fix :smile:?

**Comment by JamesTrick** [comment]
😂 - I'm happy to fix it quickly.
