### ISSUE TITLE
KL divergence VAE

### ISSUE THREAD

**Issue by rojinsafavi** [pyro-ppl/pyro#2016]
I was wondering if there is a way in pyro to force the VAE encoder to map the input to a vector of means and a covariance matrix instead of a vector of means and a vector of standard deviations? I would like to find the KL between the two VAE's latent space, but that requires a covariant matrix since I need to calculate

Σ^(-1)

I was hoping to see if pyro has any solution for that? 

Thanks,

**Comment by fritzo** [comment]
Hi @rojinsafavi, yes you can easily create a covariance matrix as the result of a VAE. If you start with a vae with diagonal covariance
```py
def guide_1(data):
    loc, scale = my_diag_nn(data)
    pyro.sample("embedding", dist.Normal(loc, scale).to_event(1))
```
you can adapt this to a different nn that generates covariances
```py
def guide_2(data):
    loc, cov = my_diag_nn(data)
    pyro.sample("embedding", dist.MultivariateNormal(loc, cov))
```
There are a few ways of gerating an `n`-by-`n` positive definite covariance in your nn. One way is to generate an `n-by-k` matrix `L` with `k > n` (to keep the result nonsingular) and then set `cov = L.matmul(L.transpose(-1, -2))`, e.g.:
```py
class MyFullNN(nn.Module):
    def __init__(self, input_dim, n, k):
        self.n = n
        self.k = k
        self.flat_net = nn.Linear(input_dim, n + n * k)
    def forward(self, data):
        loc_L = self.flat_net(data)
        loc = loc_L[..., :self.n]
        L = loc_L[..., self.n:].reshape(loc_L.shape[:-1], self.n, self.k)
        cov = L.matmul(L.transpose(-1, -2))
        return loc, cov
```
Another way is to use `torch.distributions.constraints.lower_cholesky`, but I'm having issues with that method https://github.com/pyro-ppl/pyro/issues/2017, so I'd recommend the cov.

Also https://forum.pyro.ai is probably a better place for discussion. I'll close this issue, but feel free to continue discussion in a forum topic.
