### ISSUE TITLE
pyro pytorch 1.2. compatibility

### ISSUE THREAD

**Issue by NarasimhaM3101** [pyro-ppl/pyro#2034]
Is pyro current version compatible with pytorch 1.2 ? 

I have pytorch 1.2 and pyro. Not sure why but for a very simple linear NN model notebook is crashing when I define model function and guide function. 

The NN model has only 2 layers with not many parameters. RAM has lot of free space too (in 10+ GBs. So I suspect this may be due to version compatibility issue. Please advise.

Narasimha

**Comment by fritzo** [comment]
Yes Pyro is currently compatible with PyTorch 1.2. Can you try to paste a simple-to-reproduce example? I sometimes see segfaults due to low-level PyTorch bugs. Pyro tends to exercise uncommonly used parts of PyTorch that tend to be buggier than vanilla nn code.

**Comment by NarasimhaM3101** [comment]
Please close this issue. I was using an old example book which had old pytorch functions which were not relevant. However I saw another issue with Pyro sandbox examples. 

https://github.com/pyro-ppl/sandbox/blob/master/2019-08-time-series/part_iii_custom.ipynb

`
from pyro import poutine
with torch.no_grad():
    guide_trace = poutine.trace(guide).get_trace(features_train, counts_train)
    hmm = poutine.replay(model_2, guide_trace)(features_train, counts_train)
    init_dist = hmm.filter(guide_trace.nodes["log_rates"]["value"])
` 

I got this error:-
AttributeError: 'GaussianHMM' object has no attribute 'filter'

Any suggestions please? Should we use poutine.replay().get_trace or poutine.

Narasimha
