### ISSUE TITLE
GP with MCMC from examples not working

### ISSUE THREAD

**Issue by ziatdinovmax** [pyro-ppl/pyro#2042]
### Issue Description
The MCMC training of GP from [this example](http://docs.pyro.ai/en/stable/contrib.gp.html) doesn't work. Specifically, mcmc object doesn't seem to have get_samples attribute.

### Environment
Google Colab

### Code Snippet
(see screenshot below)
![image](https://user-images.githubusercontent.com/34245227/65088235-9333c780-d986-11e9-8acf-b24fb7db9c69.png)

**Comment by neerajprad** [comment]
The interface to MCMC that you are using is deprecated and will be removed in the next major version. Could you try to import the new interface using `from pyro.infer.mcmc.api import MCMC` instead? You may need to update your version of Pyro if this module does not exist.

**Comment by ziatdinovmax** [comment]
It worked! Thanks a lot!
