### ISSUE TITLE
Support for building Bayesian Non-parametric Models in Pyro

### ISSUE THREAD

**Issue by shashankg7** [pyro-ppl/pyro#2064]
Hello, I am new to PPL world. I came across TF-probability and was giving it a try, but the dependency mess in TF world is a turn-off. I am planning to switch to Pyro world for my needs. 

Basically, I am interested in building Hierarchical Dirichlet Process-based models for text mining/IR. 

Pardon my lack of knowledge about Pyro, but can we build Bayesian Non-parametric models using Pyro (similar to https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Fitting_DPMM_Using_pSGLD.ipynb)? 

Any leads on this would be highly appreciated. 

Thanks,

**Comment by fritzo** [comment]
Hi @shashankg7 would you mind asking this question on https://forum.pyro.ai ? We try to keep one-time issues on github, and keep reusable knowledge on the forum. Thanks!

In the mean time I'll look into that notebook...

**Comment by fritzo** [comment]
Okay for a quick answer here: yes you should be able to train models like that in Pyro. Note most implementations of DPMMs actually truncate and approximate the Dirichlet process mixture with a finite mixture and a sparse Dirichlet prior over the mixture weights. You can start with a couple Pyro tutorials: [Gaussian Mixture Models](http://pyro.ai/examples/gmm.html) and a not-great [LDA example](http://pyro.ai/examples/lda.html). Let's discuss further on https://forum.pyro.ai .

**Comment by shashankg7** [comment]
@fritzo Thanks for your prompt reply. 

Sure, I'll add the question there.

**Comment by shashankg7** [comment]
I added the question there.
