### ISSUE TITLE
Support for invertible convolution transforms

### ISSUE THREAD

**Issue by bmazoure** [pyro-ppl/pyro#2066]
Seeing that almost all normalizing flow models are implemented under `pyro.distributions.transforms`, would it be possible (in theory) to support convolutional invertible layers (see [here](https://arxiv.org/abs/1807.03039) )? Similarly to `InvertibleAutoregressiveFlow`, which would take a convolutional layer and compute the forward/backward passes together with the log_det_jacobian.
Just wondering if there would be any hidden issues that would arise if I was to implement it.

**Comment by martinjankowiak** [comment]
no, i don't see any reason why it couldn't be added to `pyro.distributions.transforms`. contributions welcome!

cc @stefanwebb
