### ISSUE TITLE
Bug AffineCoupling

### ISSUE THREAD

**Issue by emited** [pyro-ppl/pyro#2084]
Hello,

There seems to be a bug in [here](https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/transforms/affine_coupling.py#L106).

`mean, log_scale = self.arn(x1)`

should probably be

`mean, log_scale = self.hypernet(x1)`

instead, right?

Thanks in advance

**Comment by martinjankowiak** [comment]
@stefanwebb any idea why this isn't being caught by existing tests?

**Comment by stefanwebb** [comment]
Let me look into this and add fix to #1932
