### ISSUE TITLE
Gaussian process kernels with vector lengthscales fail in pyro 0.5

### ISSUE THREAD

**Issue by tbrx** [pyro-ppl/pyro#2118]
A few of us at the Alan Turing Institute have been looking into using the Gaussian process contrib module for structured Bayesian optimization (in fact, we've been working on reimplementing [BOAT](https://github.com/VDalibard/BOAT), in Pyro).

Unfortunately, updating to pyro 0.5.1 from 0.4.0 has broken our existing code. Maybe this is just a case of us not finding the updated documentation, or perhaps there was a different way we should have been doing this all along — but it's not clear anymore how to set priors (or autoguides) for kernels which have lengthscales that vary across dimensions (i.e., with a lengthscale as a vector rather than a scalar, or an ARD kernel).

### Minimal example

The following code (under torch 1.3.0, python 3.6) worked for us with pyro 0.4.0, but fails with 0.5.1:

```python
import torch
import pyro
import pyro.distributions as dist
import pyro.contrib.gp as gp

X = torch.tensor([[1., 2], [3, 4], [0, 2]])
y = torch.tensor([3., 5, 4])

kernel = gp.kernels.Matern52(input_dim=2, lengthscale=torch.ones(2))
gpmodel = gp.models.GPRegression(X, y, kernel)

# The following line raises an AssertionError in pyro 0.5.1, but not 0.4.0:
gpmodel.kernel.set_prior("lengthscale", dist.LogNormal(torch.tensor(0.), torch.tensor(1.)))
gpmodel.kernel.autoguide("lengthscale", dist.Normal)

loss_fn = pyro.infer.TraceMeanField_ELBO().differentiable_loss

loss = loss_fn(gpmodel.model, gpmodel.guide)
```

This code will actually run (even under pyro 0.5.1) if we remove the two lines that define the prior and autoguide for the lengthscale, but obviously would prefer to keep them!

The relevant error is a failed assertion in `trace_mean_field_elbo.py`:

```
~/miniconda3/lib/python3.6/site-packages/pyro/infer/trace_mean_field_elbo.py in _differentiable_loss_particle(self, model_trace, guide_trace)
mask=guide_site["mask"])
--> 101                         assert kl_qp.shape == guide_site["fn"].batch_shape
```

**Comment by fritzo** [comment]
Thanks for the clear bug report, @tbrx. This appears to be an issue with the new `kl_divergence(Delta, -)` pattern. As a quick workaround you can remove `_kl_delta(p, q)`:
```diff
diff --git a/pyro/distributions/kl.py b/pyro/distributions/kl.py
index 8ffc883f..c6f3f114 100644
--- a/pyro/distributions/kl.py
+++ b/pyro/distributions/kl.py
@@ -8,7 +8,7 @@ from pyro.distributions.torch import Independent, MultivariateNormal, Normal
 from pyro.distributions.util import sum_rightmost


-@register_kl(Delta, Distribution)
+# @register_kl(Delta, Distribution)
 def _kl_delta(p, q):
     return -q.log_prob(p.v)
```
Let me know if that works for you. Meanwhile I will look for a solution.

**Comment by fritzo** [comment]
@tbrx Additionally you can add the following patch to your own code and use unmodified Pyro:
```py
import pyro.distributions as dist
from torch.distributions.kl import register_kl
@register_kl(dist.Delta, dist.Distribution)
def _kl_delta(p, q):
    raise NotImplementedError

```

**Comment by fehiepsi** [comment]
Hi @tbrx, I think that this might not be a bug. If you set correct shapes for prior, the script will work 
```
gpmodel.kernel.set_prior("lengthscale",
                         dist.LogNormal(torch.zeros(2), torch.ones(2)).to_event(1))
```
I think we missed some checks in version 0.4.0. Could you verify that using the above prior gives an expected behavior for you?

**Comment by tbrx** [comment]
Thanks both — @fritzo the patch certainly does get this working.

Hi @fehiepsi, the first thing I tried to fix this was actually
```python
gpmodel.kernel.set_prior("lengthscale", dist.LogNormal(torch.zeros(2), torch.ones(2)))
```
which would have made sense to me, but failed at the same assertion. It does work again if I use your code, thanks.

Incidentally, I realized that if I use `torch.distributions` instead of `pyro.distributions` for the prior (but not for the guide…), this also "fixes" the original issue (in a "gets the code running again" sense), presumably by no longer triggering use of the new KL computation:

```python
import pyro.distributions as pyro_dist
import torch.distributions as torch_dist
gpmodel.kernel.set_prior("lengthscale", torch_dist.LogNormal(0., 1.))
gpmodel.kernel.autoguide("lengthscale", pyro_dist.Normal)
```
…but I assume I shouldn't be mixing `pyro.distributions` and `torch.distributions` like that! And
`gpmodel.kernel.autoguide("lengthscale", torch_dist.Normal)` fails a whitelist check for autoguide distributions in `parameterized.py`.

Probably an aside, but I don't fully understand why `.to_event(1)` would be required. At least, semantically I find it confusing — the linked documentation says I would use it "to declare a dimension as dependent", but the dimensions here are independent.

In any case I guess this falls under user error… though I have to admit the previous, more "forgiving" behavior using scalars in priors was convenient!

**Comment by fehiepsi** [comment]
@tbrx FYI, all GP modules are subclassed of `pyro.nn.PyroModule` in the next Pyro release. The only change in API is to replace `set_prior` statement with
```
gpmodel.kernel.lengthscale = pyro.nn.PyroSample(dist.LogNormal(0, 1).expand([2]).to_event())
```
I think we can close this issue for now. Please let us know when your team comes up with a nice application of GP contrib module! :)
