### ISSUE TITLE
Predictive class fails for non-scalar sites

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2122]
I usually use raw poutines to for prediction:
```py
vectorize = pyro.plate("_vectorize", num_samples, dim=-2)
trace = poutine.trace(vectorize(guide)).get_trace()
samples = poutine.replay(vectorize(model), trace)()
```
When instead I try the new `Predictive` class, this fails on models with nontrivial plate structure:
```py
predictive = Predictive(model, guide=guide, return_sites=["x", "y"],
                        num_samples=num_samples, parallel=True)
samples = predictive.get_samples()
```
I believe this is due to reshaping of posterior samples without regard to their event shape. I don't know why `_predictive()` even needs to reshape samples.

I have added a failing test in this branch. Feel free to take over the branch and create a PR:
https://github.com/pyro-ppl/pyro/pull/new/fix-preditive-shapes

**Comment by fritzo** [comment]
@fehiepsi let me know if you need more failing examples, this came up in an uber internal model.

**Comment by fehiepsi** [comment]
@fritzo Sure, more failing examples would be helpful! I'll also test some related cases which I can think about.
