### ISSUE TITLE
ConditionedPlanarFlow's event_dim is wrong [bug]

### ISSUE THREAD

**Issue by gamerDecathlete** [pyro-ppl/pyro#2147]
--------------------------------------------------------------------------------------------------
### Issue Description
Provide a brief description of the issue.

I think the ConditionedPlanarFlow's event_dim is incorrect. I think the class needs to be set as such:
```

class ConditionedPlanarFlow(Transform):
   event_dim=1 #this line is not in the current release version
    def __init__(self, bias=None, u=None, w=None):
        super(ConditionedPlanarFlow, self).__init__(cache_size=1)
        self.bias = bias
        self.u = u
        self.w = w
        self._cached_logDetJ = None

```
The Transform super class default is event_dim=0.

Maybe I misunderstand this class, but I notice the PlanarFlow class has event_dim=1, as do many of the other normalizing flows and when I tried using this flow for my models my ELBO would go negative. I think the confusion is that ConditionalPlanarFlow has the event_dim=1, but that isn't setting it when it the actual flows are created (from what I can tell anyways).

### Environment
For any bugs, please provide the following:
 - Found on: Ubuntu 
 - PyTorch version: I think I was using 1.2 ...but again this is a super minor bug
You can see it in the the pyro docs http://docs.pyro.ai/en/stable/_modules/pyro/distributions/transforms/planar.html#ConditionalPlanarFlow

 - Pyro version: 3.6.10 (I think...pretty sure a single boolean value is pretty robust to version though)
Was originally found in...nightly build (not sure on term... I built from sourceb asically)

**Comment by stefanwebb** [comment]
Thanks for picking this up! Will look into this and add to #1932
