### ISSUE TITLE
Refactor Predictive to make it a serializable PyroModule

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#2154]
While working on #2083, I found that the Predictive class is not working for AutoGuides as expected. 

One issue is that using a Predictive module where we set model and trained guide as submodules throws an error `submodule model has executed outside of supermodule".format(name)`.

It will be nice to refactor it so that it:
 - [ ] Returns correct results for autoguides.
 - [ ] Supports serializability as `ScriptModule`.
 - [ ] Faster serializability for the sequential predictive function.

**Comment by fritzo** [comment]
Should this be part of 1.0 milestone?

**Comment by neerajprad** [comment]
This is currently blocking #2083, though we can have work-arounds for that. But more importantly, this has uncovered a situation where (I think) the earlier autoguide code would have worked, so it will be good to understand why this is not working.

**Comment by neerajprad** [comment]
Hmm..I don't see an easy way of supporting this. For a class like `Predictive`:

```python
class Predictive(PyroModule):
  def __init__(self, model, guide):
    self.model = model
    self.guide = guide
    ...
```
, the `model` and `guide` would have been called outside the predictive context so the check will always fail. Allowing for that will however mean that we need to set the right prefixes for all params/samples/modules, which seems onerous to support. Is there an easy way to support this?

**Comment by neerajprad** [comment]
Other serialization related issue with Predictive:
 - Currently the `num_samples` argument is static. So once a `Predictive` instance is `jit.saved` we can only draw at one time `num_samples` argument. Ideally `num_samples` should be an argument to `forward` so that we could change `num_samples` in real time from the deserialized predictive module.
 - Related to the previous point, sequential sampling will take an extremely long time to compile since it has a python for loop. If it were an argument instead, that will result in faster compilation time. 

However, changing to have `num_samples` be dynamic will require more additional refactoring since we will need to resample from `posterior_samples`, but it can probably be easily supported for SVI.

**Comment by fehiepsi** [comment]
> changing to have num_samples be dynamic will require additional refactoring since we will need to resample from posterior_samples

Looks reasonable to me. I think that we can just leave `num_samples=None` by default which will resample `posterior_samples` if `num_samples != None`. Or we can just let `num_samples` have no effect when `posterior_samples` is specified.
