### ISSUE TITLE
Question about the model serving for `VariationalSparseGP` 

### ISSUE THREAD

**Issue by Capri2014** [pyro-ppl/pyro#2224]
### Guidelines

**NOTE:** Issues are for bugs and feature requests only. If you have a question about using Pyro or general modeling questions, please post it on the [forum](https://forum.pyro.ai/).

If you would like to address any minor bugs in the documentation or source, please feel free to contribute a Pull Request without creating an issue first. 

Please tag the issue appropriately in the title e.g. [bug], [feature request], [discussion], etc.

Please provide the following details:
--------------------------------------------------------------------------------------------------
### Issue Description
Provide a brief description of the issue.

I was trying to follow the tutorials for model serving  in https://github.com/pyro-ppl/pyro/blob/dev/tutorial/source/bayesian_regression.ipynb with my fix in 546f9010aeb2308ae566726b1cec67a7b4fda9c2 and e0149fca09b6005ebf7a4a0134825cb2bdaa7899 . Then I have successfully saved the bayesian regression model as in tutorial. But when I extend it to  `VariationalSparseGP` it does not work. May I know what should I do different to save a `VariationalSparseGP` model and if so will there be different tutorials coming out? Thanks. 

### Environment
For any bugs, please provide the following:
 - OS and python version.
 - PyTorch version, or if relevant, output of `pip freeze`.
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'`

1.0.0

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

**Comment by fehiepsi** [comment]
Hi @Capri2014, I haven't tried model serving for vsgp yet. Could you provide some simple repro codes so I can get an idea of what's going on?

**Comment by Capri2014** [comment]
@fehiepsi Hi fehiepsi, I double checked and it looks like the bare bone vsgp works fine, it might be something wrong with our model (encoding + vsgp). -- Somehow we constructed the model that it can be trained, evaluated but when saved it with git trace it gave the `guide()` only expect 1 positional argument but 2 were given error. I will look into it more and keep you updated.
