### ISSUE TITLE
FR StudentTReparam, StudentTHMM

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2254]
This proposes to implement reparameterizers for `StudentT` distributions by introducing latent `Gamma`-distributed variables, following the pattern of of symmetric `Stable` distributions.

## Tasks
- [ ] `StudentTReparam` following [SymmetricStableReparam](http://docs.pyro.ai/en/latest/infer.reparam.html#pyro.infer.reparam.stable.SymmetricStableReparam). #2265 
- ~~`StudentTHMM` following [StableHMM](http://docs.pyro.ai/en/latest/distributions.html#pyro.distributions.StableHMM). Note this version should use batched `StudentT` distributions rather than the elliptical `MultivariateStudentT` distribution; the latter distribution might be separately generalized to an HMM.~~
    UPDATE this is obsoleted by the new generic `LinearHMM` #2260
- ~~`StudentTHMMReparam` following [StableHMMReparam](http://docs.pyro.ai/en/latest/infer.reparam.html#pyro.infer.reparam.stable.StableHMMReparam).~~
  UPDATE this is obsoleted by the new generic `LinearHMMReparam` class in #2259

**Comment by fritzo** [comment]
@fehiepsi I should have some time to implement this maybe next week, or did you want to implement it? It's nearly identical to the `Stable` versions.

**Comment by fehiepsi** [comment]
@fritzo I can implement them later this week. Thanks for bringing them up!
