### ISSUE TITLE
Create an autoguide to flexibly use any normalizing flow

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#2281]
We have many nice normalizing flows added by @stefanwebb, but going by our current design, we may need to separately wrap each of these in an Autoguide. Instead, I propose having a generic `AutoNormalizingFlow` guide that can taken in any normalizing flow (a `TranformModule` instance). 

Additionally:
 - It will be nice to be able to specify the number of flows. 
 - We should be able to delegate creating these transforms to an initialization function. That way users can specify other parameters like hidden dims, etc.

@stefanwebb, @fehiepsi : WDYT? I have a rough draft ready that I'll push shortly. 

I need this to do some experiments for the neural transport HMC.

**Comment by fehiepsi** [comment]
Resolved at #2282
