### ISSUE TITLE
Missing reference in Kalman Filter tutorial

### ISSUE THREAD

**Issue by ZappD0S** [pyro-ppl/pyro#2303]
In the kalman filter tutorial, the authors mention a source a few times by referring to it with its index [1], but the actual reference is nowhere to be found within the rest of the tutorial. The tutorial file is the following: <https://github.com/pyro-ppl/pyro/blob/dev/tutorial/source/ekf.ipynb>.

**Comment by fritzo** [comment]
@jpchen do you remember the reference?

@ZappD0S I've mostly switched to [Funsor](https://github.com/pyro-ppl/funsor) for Kalman filtering. You might check out the [example](https://github.com/pyro-ppl/funsor/blob/master/examples/kalman_filter.py) there.

**Comment by jpchen** [comment]
i believe it was the seminal [kalman filter paper](https://www.cs.unc.edu/~welch/kalman/media/pdf/Kalman1960.pdf) but if you're interested in the derivation, there are a plethora of [lectures](https://www.cs.unc.edu/~welch/media/pdf/kalman_intro.pdf) and [papers](https://arxiv.org/pdf/1710.04055.pdf) that give a better overview. i'll add the reference to the tutorial.
