### ISSUE TITLE
[bug] GP covariance matrix from `pyro.contrib.gp.models.GPRegression.forward` is not PD

### ISSUE THREAD

**Issue by rameshvs** [pyro-ppl/pyro#2319]
### Issue Description
Running `GPRegression.forward(..., full_cov=True)` on the data from the tutorial produces a covariance matrix with (near-zero) negative eigenvalues, which then leads to an error when trying to use it in `pyro.distributions.MultivariateNormal`.

### Environment
- Python 3.7.3 on Docker on MacOS 10.14.6
- PyTorch version: 1.3.1
- Pyro version: 1.1.0

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

```
import numpy as np

import torch
import pyro
import pyro.contrib.gp as gp
import pyro.distributions as dist

pyro.enable_validation(True)
pyro.set_rng_seed(0)

num_samples = 20
x = dist.Uniform(0., 5.).sample(sample_shape=(num_samples,))
y = 0.5 * torch.sin(3*x) + dist.Normal(0., 0.2).sample(sample_shape=(num_samples,))

kernel = gp.kernels.RBF(
    input_dim = 1, 
    variance = torch.tensor(5.), 
    lengthscale = torch.tensor(10.)
)

model = gp.models.GPRegression(x, y, kernel, noise=torch.tensor(1.))
mean, covariance = model.forward(x, full_cov=True)

cov_eig = np.linalg.eigvalsh(covariance.detach().numpy())
print('Nonpositive eigenvalues are', cov_eig[cov_eig <= 0])

# produces an error since the covariance matrix isn't positive definite
dist.MultivariateNormal(mean, covariance)
```

**Comment by fehiepsi** [comment]
I think you will want to include the noise term to the output of your GP (i.e. `model(x, full_cov=True, noiseless=False)`.

**Comment by fehiepsi** [comment]
@rameshvs Thanks for the issue report! It is expected that the covariance matrix in single precision will be not positive definite if we don't include jitter or noise, so I'm going to close this issue.
