### ISSUE TITLE
Jitting HMC does not work for models with `param` statements

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#2350]
The following repro script shows the issue
```python
import torch
import pyro
import pyro.distributions as dist
from pyro.infer import MCMC, NUTS

def model():
    x = pyro.param("x", torch.tensor(1.))
    pyro.sample("y", dist.Normal(x, 1))

mcmc = MCMC(NUTS(model, jit_compile=True), 10)
mcmc.run()
mcmc.summary()
```
raises the error `RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient`.

**Comment by fritzo** [comment]
An easy workaround is to hide the constant by a `lambda`:
```py
import torch

import pyro
import pyro.distributions as dist
from pyro.infer import MCMC, NUTS


def model():
    x = pyro.param("x", lambda: torch.tensor(1.))
    pyro.sample("y", dist.Normal(x, 1))


model()  # initialize param store
mcmc = MCMC(NUTS(model, jit_compile=True), 10)
mcmc.run()
mcmc.summary()
```

**Comment by fehiepsi** [comment]
Hmm, I still get the issue. Are you using PyTorch `dev`?

**Comment by fritzo** [comment]
I'm using PyTorch release. Did you make sure to initialize the param store before inference?
```py
model()  # initialize param store
```

**Comment by fehiepsi** [comment]
Yes, I used your code and still observed the issue. I think this is the same issue as [this one](https://github.com/pytorch/pytorch/issues/17583) and PyTorch won't support it. IIUC we can resolve the issue by replaying `pyro.param` sites by constant values in the computation of `potential_fn`.

**Comment by neerajprad** [comment]
The JIT tracer expects any constants in the trace to have `requires_grad=False` as expected. Some of our examples and tests for HMC use `model.requires_grad_(False)` if the model is a `PyroModule` or `nn.Module`. 

I think we could provide a `param_store._requires_grad(requires_grad=True)` method which will allow us to use the param store for simple key value lookup that will be useful in such situations. 

```python
def requires_grad_(self, requires_grad=True):
    for v in self.named_parameters().values():
        v.requires_grad_(requires_grad)
```

**Comment by fehiepsi** [comment]
@neerajprad's solution works like a charm!! :D
