### ISSUE TITLE
[FR] support forecasting for count time series

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#2373]
Currently, the pattern of modeling `noise`, `prediction`, `residual` does not work for Poisson likelihood. It would be nice if we support another `predict` pattern in `ForecastingModel` to deal with count data.

**Comment by fritzo** [comment]
I suppose we could allow a single arg, so `.predict()` could be used as either
```py
self.predict(predict_dist)  # prediction is implicitly zero
```
or
```py
self.predict(noise_dist, prediction)
```
In fact to work around until we have this working, you can set `prediction=zero_data`, even for `Poisson`.

**Comment by fehiepsi** [comment]
Literally, I have been thinking about this for many days. Haizz, I should make this FR earlier... Thanks for your simple solution!

**Comment by fehiepsi** [comment]
I think `self.predict(dist.Poisson(predicted_rate), zero_data)` is a pretty good solution. So I would like to close this issue.
