### ISSUE TITLE
API issues with MCMC initialization

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#2415]
- [x] We should be able to provide `initial_params` in the constrained space which makes for a more natural choice.
 - [x] We use the `initialize_model` utility at a few places including within the `MCMC` class and the `HMCKernel` class. This function is used to get the value for the transforms, convert a model representation into a potential energy function, and get initial parameter values. If a user specifies an explicit value for `initial_params` and we call this function to get transforms or potential energy function, we shouldn't error if a viable initial parameter was not found. 
 - [x] Expose initialization strategy, e.g. sampling from uniform in the unconstrained space or the prior within the `MCMC` class.

cc. @fritzo, @fehiepsi

**Comment by neerajprad** [comment]
@fehiepsi - what do you think about refactoring out finding the initial parameters into its own function? That will make it easier to skip it if the user provides valid initial params.

**Comment by fehiepsi** [comment]
Agreed! We can even use `autoguide` initialization as in NumPyro. I'll make a PR for it.

**Comment by fritzo** [comment]
Maybe add a new `init_params` in the constrained space and deprecate the `initial_params`, thus preserving backwards compatibility? Kind of hacky tho.

**Comment by neerajprad** [comment]
Closing this issue - it looks like #2417 and #2420 should have resolved all of these. Regarding (1), we need to use init_strategy instead of `initial_params` to specify initialization in the constrained space, since the latter is also used when a user passes in a potential energy function directly. Feel free to reopen if there are any related issues that you observe.
