### ISSUE TITLE
[bug] Trying to import sir_hmc

### ISSUE THREAD

**Issue by mturk24** [pyro-ppl/pyro#2449]
When trying to import sir_hmc into another script or notebook, there's an issue "ImportError: cannot import name 'init_to_value' from 'pyro.infer.autoguide'"

### Environment
For any bugs, please provide the following:
 - OS and python version: macOS Mojave 10.14.6 and Python 3.8
 - PyTorch version: 1.5.0
 - Pyro version: 1.3.1

**Comment by fritzo** [comment]
Hi @mturk24 `init_to_value` has not yet been released. You should be able to run `sir_hmc.py` using Pyro's dev branch. We plan to release after `pyro.contrib.epidemiology` settles down in a few weeks. Good luck~

**Comment by mturk24** [comment]
Hi @fritzo thanks so much for getting back! I was trying to run this on the Dev branch using Python 3.8 but looks like a torch binary isn't available yet for 3.8.

**Comment by mturk24** [comment]
@fritzo By the way, I still cannot run the sir_hmc.py script (even after copy/pasting init_to_value and other dependencies in that can't be imported, such as ExtendedBinomial which isn't in the distributions module anymore).


After copy/pasting everything, I run "python sir_hmc.py" with the default args and the HMC algo hangs at Warmup: 0% with 0/300 iterations. What is the simplest example you are able to run?

**Comment by eb8680** [comment]
@mturk24 running `python sir_hmc.py` to completion with default args works fine for me on `dev`, no copy-pasting necessary.  Usually to run unreleased code in Pyro you'll need to [install the `dev` branch with `extras` requirements](https://github.com/pyro-ppl/pyro/#installing-pyro-dev-branch).  You might try uninstalling Pyro and reinstalling `dev` from source.

**Comment by mturk24** [comment]
@eb8680 Which version of python are you using? I'm unable to import torch in all versions of Python I've tried (in Python 3)

**Comment by fritzo** [comment]
follow https://github.com/pyro-ppl/pyro/blob/dev/.travis.yml

**Comment by mturk24** [comment]
@fritzo Thanks! Do you mean using a conda env based on that yml?

**Comment by mturk24** [comment]
Unable to use that yml to fix my torch issue. Though I do have the extras pyro-ppl version installed. Given this, can you help orient me on next steps?

**Comment by eb8680** [comment]
@mturk24 without more details about what you mean by "unable to import torch" it's hard to say, but you probably just got some library versions tangled up, especially if you're using pip and conda together.  I suggest creating a completely fresh Python environment with one of the supported Python versions using `virtualenv` or `conda` and reinstalling Pyro `dev` and all Python dependencies including PyTorch from scratch there.  

If you're still having trouble getting PyTorch working independent of Pyro after that, you might try asking for help on the [PyTorch forum](https://discuss.pytorch.org/).

**Comment by mturk24** [comment]
@eb8680 @fritzo Thank you both! So I'm able to run it now, but the script actually hangs on the sampling component (all of my CPU resources are being exhausted). Are you running this using a GPU?

**Comment by eb8680** [comment]
@mturk24 I'm afraid I still can't reproduce your issue - I can run `python sir_hmc.py` with default args to completion on my underpowered laptop CPU in under 60 seconds.  Can you provide more details about your error and Python environment, ideally enough for me to reproduce the problem?  What do you mean when you say the script hangs?  What happens if you try different random seeds (`--rng-seed`)?

As @fritzo mentioned, `sir_hmc.py` depends on `pyro.contrib.epidemiology` and associated functionality, which is under active development and has not been officially released.  We can try to help you get the script running, but keep in mind that we may not be able to provide much support beyond that right now.

**Comment by mturk24** [comment]
@eb8680 Got it to run with default args! Thanks so much for the help, really appreciate it. It had to do with the [extras] module being installed incorrectly. I went through each and every step on the README from scratch and got it to work. 

I've noticed that the plotting functionality isn't working when trying to run the default version. Is this consistent with what you've noticed?

**Comment by eb8680** [comment]
@mturk24 I have not had any issues with `sir_hmc.py`, including with the plotting functionality (`--plot`), so presumably whatever is happening is related to your installation problems.

**Comment by mturk24** [comment]
@eb8680 Got everything to work fine now, apologies for the confusion and than you and @fritzo  both for the help! Hopefully our dialogue on this thread can help anyone else who experiences any similar issues.

This model has been very useful!
