### ISSUE TITLE
RTD build fails for `latest` branch

### ISSUE THREAD

**Issue by desertnaut** [pyro-ppl/pyro#2453]
Couple of days ago I checked it was all OK, but now it seems whole sections of the documentation under `latest`have effectively been "emptied", with nothing but a list in them (no content):

http://docs.pyro.ai/en/latest/inference_algos.html#importance

http://docs.pyro.ai/en/latest/distributions.html

http://docs.pyro.ai/en/latest/parameters.html

http://docs.pyro.ai/en/latest/nn.html

http://docs.pyro.ai/en/latest/optimization.html

http://docs.pyro.ai/en/latest/poutine.html

http://docs.pyro.ai/en/latest/ops.html

http://docs.pyro.ai/en/latest/contrib.autoname.html

http://docs.pyro.ai/en/latest/contrib.bnn.html

http://docs.pyro.ai/en/latest/contrib.examples.html

etc etc (non-contributed tutorials & examples seem OK)

Docs under `stable` seem to be OK.

**Comment by fritzo** [comment]
@jpchen can you recommend a good debugging workflow for docs building? They build for me locally, so it must be a RTD mismatch.

I suspect the docs are failing because I've been adding non-ascii characters to docstrings lately, all in `pyro.contrib.epidemiology`.

**Comment by neerajprad** [comment]
Strangely, the links to the `dev` branch that `latest` should point to seem to work fine. e.g.
 - http://docs.pyro.ai/en/dev/inference_algos.html#importance
 - http://docs.pyro.ai/en/dev/distributions.html

This seems to me to be some readthedocs issue rather than a build issue.

**Comment by jpchen** [comment]
the torch endpoint seems to have changed:
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.4.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0)
ERROR: No matching distribution found for torch==1.4.0+cpu
```

Can we build against 1.5 (as I assume you're doing locally)? The [website](https://pytorch.org/get-started/previous-versions/) only lists up to 1.2.
