### ISSUE TITLE
AffineCoupling uses NHWC, PyTorch uses NCHW [feature request]

### ISSUE THREAD

**Issue by akern40** [pyro-ppl/pyro#2464]
### Issue Description
The `AffineCoupling` transformation module splits the incoming tensor along its last dimension:
```{python}
x1, x2 = x[..., :self.split_dim], x[..., self.split_dim:]
```
However, affine coupling layers split their inputs along channels. Since the convention in PyTorch is to use NCHW ordering, a naive usage of the `AffineCoupling` transformation would split data along the width of a tensor.

This could be fixed with two `Permute` modules that change the data from NCHW to NHWC and back again, but it seems like Pyro should conform to the NCHW standard of PyTorch.

### Replication
To replicate, you can perform the following:
```{python}
import torch, pyro

loc = torch.zeros(512, 32, 14, 14)  # A common NCHW set of values
scale = torch.eye(14)
base_dist = pyro.distributions.MultivariateNormal(loc, covariance_matrix=scale)

# A basic convolutional NN for the hypernet
hypernet = torch.nn.Sequential(
    torch.nn.Conv2d(16, 512, 3, padding=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(512, 512, 1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(512, 32, 3, padding=1)
)
hnet_fn = lambda x: hypernet(x).chunk(2, dim=1)

ac = pyro.distributions.transforms.AffineCoupling(16, hnet_fn)
y = ac(x)
```
I'd expect that `AffineCoupling` would break up the tensor along the channel dimension (canonically dimension 1) at the 16th channel, but instead, it breaks it up into two tensors: one of shape `[512, 32, 14, 0]`, and the other of size `[512, 32, 14, 14]`. This gives the following error:
```{python}
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-245-bb8c77bf15c5> in <module>()
----> 1 ac(base.sample())

/torch/distributions/transforms.py in __call__(self, x)
    127         if x is x_old:
    128             return y_old
--> 129         y = self._call(x)
    130         self._cached_x_y = x, y
    131         return y

/pyro/distributions/transforms/affine_coupling.py in _call(self, x)
    105         x1, x2 = x[..., :self.split_dim], x[..., self.split_dim:]
    106 
--> 107         mean, log_scale = self.nn(x1)
    108         log_scale = clamp_preserve_gradients(log_scale, self.log_scale_min_clip, self.log_scale_max_clip)
    109         self._cached_log_scale = log_scale

<ipython-input-231-d0eaba723c7e> in <lambda>(x)
----> 1 hnet_fn = lambda x: hypernet(x).chunk(2, dim=1)

/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/torch/nn/modules/container.py in forward(self, input)
     98     def forward(self, input):
     99         for module in self:
--> 100             input = module(input)
    101         return input
    102 

/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/torch/nn/modules/conv.py in forward(self, input)
    343 
    344     def forward(self, input):
--> 345         return self.conv2d_forward(input, self.weight)
    346 
    347 class Conv3d(_ConvNd):

/torch/nn/modules/conv.py in conv2d_forward(self, input, weight)
    340                             _pair(0), self.dilation, self.groups)
    341         return F.conv2d(input, weight, self.bias, self.stride,
--> 342                         self.padding, self.dilation, self.groups)
    343 
    344     def forward(self, input):

RuntimeError: Given groups=1, weight of size 512 16 3 3, expected input[512, 32, 14, 14] to have 16 channels, but got 32 channels instead
```

### Potential Solution
If there is a desire to move `AffineCoupling` to use NCHW instead of NHWC, a quick backwards-compatible fix would be add a keyword argument specifying the channel dimension, altering the signature of `AffineCoupling` from
```{python}
def __init__(self, split_dim, hypernet, log_scale_min_clip=-5., log_scale_max_clip=3.)
```
to
```{python}
def __init__(
    self,
    split_dim,
    hypernet,
    log_scale_min_clip=-5.,
    log_scale_max_clip=3.,
    channel_dim=1
)
```
The `_call` method could then use
```{python}
x1, x2 = x.chunk(2, dim=self.channel_dim)
```
and the `_inverse` method could do the same thing.

If I'm off-base here, I'd be happy to know. Thanks!

**Comment by fritzo** [comment]
cc @stefanwebb

**Comment by stefanwebb** [comment]
Hi @akern40, I think you might have a misunderstanding of how GLOW/Neural Spline Flow etc. flow. There is the "1x1 convolution" layer, which in Pyro is `transforms.GeneralizedChannelPermute`. This does the permutation of the channel dimension and a bit more.

Then there is the permutation *along the channel, width, and height dimensions*. This could be accomplished by resizing the tensor and using `transforms.Permute`, then sizing back. The transform to reshape the size of transform needs some work upstream in PyTorch and hasn't been completed yet but is in the works...

Related to what you suggested, I think it may however be useful to be able to input an `event_dim=x` into `torch.Permute` to get it to permute the final `x` dimensions. That way you wouldn't have to go through the reshaping. I'll add this in a PR today!

**Comment by stefanwebb** [comment]
Related to what you suggested, I think it may however be useful to be able to input an `event_dim=x` into `transforms.Permute`, `transforms.Coupling` etc. to get it to operate on the final `x` dimensions of the input tensor (rather than just the final dimension). I'll think about this moving forward! :)

**Comment by akern40** [comment]
Hi @stefanwebb! Thanks for the quick responses to everything. It is entirely possible that I'm confused about Glow/RealNVP etc. I understand the "1x1 convolution" is the `GeneralizedChannelPermute`, and stands in for using `Permute` directly in the Glow setup (as the authors do in RealNVP). My understanding, however, was that `AffineCoupling` does a channel-wise split on the incoming tensor. From the Glow paper, in the section on Affine Coupling:

> As in (Dinh et al., 2014), the `split()` function splits the input tensor into two halves along the channel dimension, while the `concat()` operation performs the corresponding reverse operation

The authors define their tensors as `[h x w x c]`, but (as I said above) I'd expect PyTorch tensors to be `[c x h x w]`.

That's why I was suggesting the additional `channel_dim` keyword, so that users could specify which dimension they want split. My understanding is that `event_dim` is reserved for indicating the expected number of dimensions a tensor should have for the bijection to apply (e.g. `event_dim>1` for `AffineCoupling`, since it works on tensors with at least 2 dimensions), but not *which* dimensions should be split and concatenated.

Thanks for considering my suggestion 😄

**Comment by stefanwebb** [comment]
Ah yes, it's more complicated than I thought as you suggest!

I had a look in `tfp` to see what they do. The solution there is to use `tfp.Reshape` along with `tfp.Permute` so you can use `tfp.RealNVP` that only operates on a one-dimensional random variable, just like `transforms.AffineCoupling` in Pyro, and accomplish any arbitrary masking pattern you want (like the checkerboard pattern in RealNVP/Glow).

Unfortunately there is no equivalent of `tfp.Reshape` in Pyro... I started working on this and discovered it needs changes upstream in PyTorch. Hopefully myself or someone else can complete it soon (needed for the second part of the NF tutorial I've got planned)!

By the way, splitting on the channel dim would make it an `event_dim=3` transform if the tensor is in `CxHxW` format. This could be a useful feature so I'll do a PR for review now

**Comment by stefanwebb** [comment]
It's also unfortunately we can't change the API... I think `split_dim` (what I chose at the time) is a bit ambiguous, because `dim` refers to the elements of the last dimension in the tensor rather than the dimension of the tensor

**Comment by stefanwebb** [comment]
@akern40 see #2472

**Comment by akern40** [comment]
The PR Looks great! Thanks for responding so quickly.

On a related note, I was wondering about a `Reshape` transformation in Pyro... what is the blocking upstream change? Just curious.

**Comment by akern40** [comment]
I was looking at the pull request above and I realized that the final lines of `_call`, `_inverse`, and `log_abs_det_jacobian` for `AffineCoupling` also need to take `self.dim` into account:

```{python}
def _call(...):
    ...
    return torch.cat([y1, y2], dim=self.dim)

def _inverse(...):
    ...
    return torch.cat([x1, x2], dim=self.dim)

def log_abs_det_jacobian(...):
    ...
    result_size = log_scale.size()[:-self.event_dim] + (-1,)
    result = log_scale.view(result_size).sum(-1)
    shape = x.shape[:-self.event_dim]
    return result.expand(shape)
```
I wasn't sure how best to suggest these, so I made a PR to @stefanwebb's fork with the other changes. Sorry if that wasn't the best way, I'm still new to contributing to open-source.

As a clarification, the changes to `log_abs_det_jacobian` are needed to perform an "elementwise" summation, where the elements are the samples/batches. This ensures that the transform works with things like `TransformedDistribution` that use the transform's `event_dim` to sum log probabilities from different transformations.

**Comment by akern40** [comment]
I also believe similar changes are needed for the `log_abs_det_jacobian` of `Permute`. Computationally it will make no difference (as they're all zeros anyway), but it will be necessary to avoid errors when using `TransformedDistributions` and other modules that combine log probabilities.

**Comment by stefanwebb** [comment]
@akern40 I'll close this issue now that #2472 has been merged.

With regards to the reshape transform, I'll submit a PR to PyTorch soon and tag you so you can provide feedback/contribute to the code :)
