### ISSUE TITLE
FR Reshape transformation

### ISSUE THREAD

**Issue by akern40** [pyro-ppl/pyro#2481]
### Issue Description
Normalizing flows often use tensor reshaping between different transformations. Having a `Reshape` transformation would allow users to include this in a `ComposeTransform` without having to write a custom transformation that includes reshaping via `torch.reshape`.

Reshaping does not change the volume of a tensor, which makes an implementation simpler. A similar question of operating on the rightmost dimensions may come up, as in #2480.

cc @stefanwebb

**Comment by fritzo** [comment]
This is now available as [torch.distributions.transforms.ReshapeTransform](https://pytorch.org/docs/stable/distributions.html#torch.distributions.transforms.ReshapeTransform)
