### ISSUE TITLE
[feature request] Full code for VAE example

### ISSUE THREAD

**Issue by icml-compbio** [pyro-ppl/pyro#2489]
### Issue Description
I got a normal distribution result after training and encode with my VAE. I am not sure if I did anything wrong. I was wondering if you can provide codes for the MINIST result and TSNE plot. Thanks!

**Comment by fritzo** [comment]
I believe the VAE utilities are all in 
https://github.com/pyro-ppl/pyro/blob/dev/examples/vae/utils
for example here is the tsne plotting code:
https://github.com/pyro-ppl/pyro/blob/dev/examples/vae/utils/vae_plots.py#L81
