### ISSUE TITLE
[feature request] Kaiming Normal distribution

### ISSUE THREAD

**Issue by sumanthratna** [pyro-ppl/pyro#2515]
### Issue Description
With a deterministic model, I can use `torch.nn.init.kaiming_normal_(m.weight.data, a=0, mode='fan_out')`, where `m` is a `torch.nn.Module`. I'd like to be able to keep using Kaiming initialization, but I don't think this is in Pyro. 

### Environment
For any bugs, please provide the following:
 - macOS 10.15.5 Beta, Python 3.8.2
 - torch 1.5.0
 - pyro 1.3.1

### Code Snippet
n/a

**Comment by fritzo** [comment]
Hi @sumanthratna , I believe Kaiming initialization is just a carefully scaled normal initialization, so you should be able to do something like
```py
def kaiming_normal(shape, a=0., mode="fan_in"):
    fan_out, fan_in = shape[-2:]
    n = fan_in if mode == "fan_in" else fan_out
    loc = torch.zeros(shape)
    scale = torch.ones(shape)
    scale = scale * (2 / ((1 + a**2) * n)) ** 0.5
    return dist.Normal(loc, scale)
```

**Comment by sumanthratna** [comment]
Thanks for the reply. Would this be the appropriate the appropriate replace for the example given in the original post?
```python
m.weight = PyroSample(prior=kaiming_normal(m.weight.data.size(), a=0, mode='fan_out'))
```

**Comment by fritzo** [comment]
@sumanthratna yes that is the appropriate replacement. Let me know if that works, and feel free to contribute that or similar methods in a module say `pyro.nn.init` if you'd like.

**Comment by sumanthratna** [comment]
Thanks for letting me know—it does work. 

As for a `pyro.nn.init` module, I don't think that's really necessary yet. I know Pyro's documentation is still being improved, so I think the best option is just to add docs on higher-level content, such as this issue. 

Alternatively, pyro could decide to focus on making its API as similar to torch's as possible—e.g., `pyro.optim.lr_scheduler` instead of just `pyro.optim`. In this case, I'm all for a `pyro.nn.init` module. 

I'll close this issue since my original question was answered.

**Comment by sumanthratna** [comment]
Actually, when I use `torch.jit.script` on my PyroModule, I get `Module 'PyroConv2d' has no attribute 'weight'`. I'm trying:
```python
m._parameters['weight'].data = PyroSample(prior=kaiming_normal(m.weight.data.size(), a=0, mode='fan_out'))
```
but this raises `TypeError: Variable data has to be a tensor, but got PyroSample`.

**Comment by fritzo** [comment]
Hi @sumanthratna can you ask this on http://forum/pyro.ai and post a complete code snippet? Thanks!

**Comment by sumanthratna** [comment]
Sure, I'll try to do that soon. For the record, this is the function that produce similar results as `torch.nn.init.kaiming_normal_`:
```python
def kaiming_normal(shape, a=0, mode="fan_in"):
    # adapted from:
    # https://pytorch.org/docs/stable/_modules/torch/nn/init.html#kaiming_normal_

    # the nonlinearity is leaky ReLU
    def _calculate_fan_in_and_fan_out(tensor_shape):
        num_input_fmaps = tensor_shape[1]
        num_output_fmaps = tensor_shape[0]
        if len(tensor_shape) > 2:
            # TODO: there's probably a way to collapse this if-statement
            # into a min(1, len(tensor_shape) - 2) or inline if.
            receptive_field_size = len(tensor_shape) - 2
        else:
            receptive_field_size = 1
        fan_in = num_input_fmaps * receptive_field_size
        fan_out = num_output_fmaps * receptive_field_size

        return fan_in, fan_out

    fan_in, fan_out = _calculate_fan_in_and_fan_out(shape)
    fan = fan_in if mode == 'fan_in' else fan_out
    loc = torch.zeros(shape)
    gain = (2.0 / (1 + a ** 2)) ** 0.5
    std = gain / (fan ** 0.5)
    return dist.Normal(loc, std)
```
