### ISSUE TITLE
VSCode linting issue with torch methods

### ISSUE THREAD

**Issue by Gulshan2002** [pyro-ppl/pyro#2548]
### Guidelines

**NOTE:** Issues are for bugs and feature requests only. If you have a question about using Pyro or general modeling questions, please post it on the [forum](https://forum.pyro.ai/).

If you would like to address any minor bugs in the documentation or source, please feel free to contribute a Pull Request without creating an issue first. 

Please tag the issue appropriately in the title e.g. [bug], [feature request], [discussion], etc.
[discussion] [urgent]

Please provide the following details:
--------------------------------------------------------------------------------------------------
###Issue Description
![image](https://user-images.githubusercontent.com/63960580/86537783-3bfbe500-bf0f-11ea-8eb5-7e45a2bc2951.png)
![image](https://user-images.githubusercontent.com/63960580/86537923-20450e80-bf10-11ea-9e56-22704b8ffe40.png)

### Environment
For any bugs, please provide the following:
 - OS and python version.Pop!_OS 20.04 LTS x86_64 and python3.8
 - PyTorch version, or if relevant, output of `pip freeze`.1.5.1
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'` 1.3.1

### Code Snippet

import torch

x= torch.randn(2,3,requires_grad=True)
w=torch.randn(2,requires_grad=True)
print(x)
print(w)

def main(y):
    return y@w.t + x

pred = main(input)
print(pred)

**Comment by JamesTrick** [comment]
Hi @Gulshan2002 

This is an issue that is best raised with pyTorch themselves. I've also found the relevant issue - they recommend suppressing such messages. [Issue is here](https://github.com/pytorch/pytorch/issues/701).

**Comment by fritzo** [comment]
@JamesTrick thanks for the fix. Indeed this is an upstream issue with PyTorch + VSCode and it looks like the best fixes are described at https://github.com/pytorch/pytorch/issues/701
