### ISSUE TITLE
Mini-batch training for sparse variational GP

### ISSUE THREAD

**Issue by keyulu** [pyro-ppl/pyro#2556]
There is no official documentation for how to perform mini-batch training for sparse variational GP (https://pyro.ai/examples/gp.html#More-Sparse-GPs). From my understanding, we need to define a wrapper class for VariationalSparseGP. I have the class defined as below, but it does not run. What could go wrong? Thanks.

```
class GPModel(pyro.nn.Module):
	def __init__(self, X, y, kernel, Xu, likelihood):
		super(GPModel, self).__init__()
		self.svgp = gp.models.VariationalSparseGP(
			X,
			y,
			kernel,
			Xu=Xu,
			likelihood=likelihood,
			whiten=True,
			latent_shape=torch.Size([30]))

	def model(self, X, y):
		self.svgp.set_data(X, None)

	def guide(self, X, y):
		self.svgp.guide()

	def forward(self, X_new):
		return self.svgp(X_new)

loss_fn = pyro.infer.TraceMeanField_ELBO().differentiable_loss

def train(model, train_loader):
	for data, label in train_loader:
		optimizer.zero_grad()
		loss = loss_fn(model.model, model.guide, data, label)
		loss.backward()
		optimizer.step()
```

**Comment by fehiepsi** [comment]
@keyulu You can look at [Deep Kernel Learning](http://pyro.ai/examples/dkl.html) for an example to see how to train a gp model in batch. I'll add a paragraph in the docs to mention about it.

**Comment by fehiepsi** [comment]
Actually, it is already mentioned in the [docs](http://docs.pyro.ai/en/stable/contrib.gp.html#pyro.contrib.gp.models.model.GPModel.set_data) of `set_data` method.

**Comment by keyulu** [comment]
@fehiepsi  Thanks for the reference. I changed my code to below. But I'm confused by how to get prediction. My prediction "pred" as code below is of size (50, batch_size), but I expected (batch_size).

```
def train(model, train_loader):
	for data, label in train_loader:
		optimizer.zero_grad()
		model.set_data(data, label)
		loss = loss_fn(model.model, model.guide)
		loss.backward()
		optimizer.step()

		pred, _ = model(data)
		pred = pred.cpu().detach().numpy()
		print(pred)


likelihood = gp.likelihoods.Gaussian()
kernel = gp.kernels.RBF(input_dim=X_train.shape[1])
model = gp.models.VariationalSparseGP(X_train, y_train, kernel, Xu=Xu, likelihood=likelihood, latent_shape=torch.Size([50]))
loss_fn = pyro.infer.TraceMeanField_ELBO().differentiable_loss
optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)


```

**Comment by keyulu** [comment]
PS: I wasn't sure what latent_shape meant, so I set it according to the example code.

**Comment by fehiepsi** [comment]
> I wasn't sure what latent_shape meant

I would recommend leaving it at the default value unless you want to do something special (e.g. for multi-class prediction). With `latent_shape=torch.Size([50])`, I guess your training data `y` has shape `50 x N`, where N is the number of data points?

> set it according to the example code

Which example code that you mentioned? I think most GP examples do not use `latent_shape` argument. I think it is only useful when you want to use a single kernel to predict multiple GPs (e.g. multi-class classification problems).

**Comment by keyulu** [comment]
@fehiepsi  I see, after leaving it as default, now I'm getting predictions of size (batch_size) as expected. Thanks.
