### ISSUE TITLE
How to set device for Pyro models?

### ISSUE THREAD

**Issue by h56cho** [pyro-ppl/pyro#2579]
Hello,

I am trying to convert a PyTorch neural network model into a Bayesian Pyro model.
Is there any way that I can set device for my Pyro model, similar to ```torch.device("cuda")```?
or would simply the ```torch.device``` command do the trick?

Thank you,

**Comment by fritzo** [comment]
Hi @h56cho would you mind asking questions on the Pyro forum, so that others may benefit from answers? https://forum.pyro.ai Thanks!
