### ISSUE TITLE
Cannot run the example code due to unknown parameter

### ISSUE THREAD

**Issue by lundlab-kaltinel** [pyro-ppl/pyro#2600]
Hi,
I would like to run the ss-vae, and I am trying to get a sense of it by running the example by:
`python ss_vae_M2.py --seed 0 --aux-loss -alm 46 -enum parallel -sup 100 -zd 50 -hl 50 -lr 0.00042 -b1 0.95 -bs 100 -log ./tmp.log`

However, I am receiving the error of:
```
Traceback (most recent call last):

  File "ss_vae_M2.py", line 438, in <module>
    main(args)

  File "ss_vae_M2.py", line 324, in main
    data_loaders = setup_data_loaders(MNISTCached, args.batch_size, sup_num=args.sup_num)

TypeError: setup_data_loaders() missing 1 required positional argument: 'batch_size
```

I see that `batch_size` is a required argument, however it is being provided in the command line in `-bs` format?
I would like to learn how to fix it.

PS: I am using Pyro without CUDA, and using its 1.3.1 version.

Thank you!

**Comment by fritzo** [comment]
It looks like you are missing the required `use_cuda` argument. Does this work for you?
```py
data_loaders = setup_data_loaders(MNISTCached, use_cuda=False,
                                  batch_size=args.batch_size, sup_num=args.sup_num)
```

**Comment by lundlab-kaltinel** [comment]
Yes,now I can run it, thank you very much!

However, it uses almost all cores and I cannot see a way of limiting the thread usage. 
I appreciate to learn how to control it?

**Comment by fritzo** [comment]
To limit thread parallelism, you could set the `OMP_NUM_THREADS` environment variable
```
OMP_NUM_THREADS=42 my_pytorch_script.py
```

In the future could you ask questions on https://forum.pyro.ai ? That way your questions are more easily discoverable by other users. Thanks!
