### ISSUE TITLE
Cleanup: use black code formatter

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2602]
It would be nice for contributors if we could auto-format Pyro's codebase. It seems the most popular python formatter is now [black](https://github.com/psf/black).

Formatting the entire codebase will wreak havok on open PRs, so if we decide to run `black` we should try to
1. close out existing PRs beforehand, and
2. possibly split the formatting across multiple PRs

**Comment by eb8680** [comment]
Maybe as the last step before the 1.5 release?
