### ISSUE TITLE
Cleanup: use sphinxcontrib.bibtex for citations?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2612]
Currently Pyro's codebase has numerous references but inconsistent format. Is there any demand for standardizing these, say via [shinxcontrib.bibtex](https://pypi.org/project/sphinxcontrib-bibtex/)?

**Pros:**
- reduces duplicated citations across functions
- standardization

**Cons:**
- Not all citations belong in docstrings; some belong in comments e.g. for implementation details
- Introduces an extra layer of abstraction for readers of source code

**Comment by martinjankowiak** [comment]
i rather keep the flexibility that comes with doing it in an ad hoc way
