### ISSUE TITLE
Access to pyro.markov design document

### ISSUE THREAD

**Issue by RaulPL** [pyro-ppl/pyro#2616]
Hi, I would like to read the design document [pyro.markov](https://docs.google.com/document/d/1EPaKng2zaXfKEK9EIY59CgoIpUiitp3-_XvpNeJY6sM/edit?usp=sharing)  that its listed on the the Wiki page but it says that I have to "Request access".  Can you make it publicly available like the rest of the documents?

Thanks for making this documentation open, it has help me to understand the internals better.

**Comment by fritzo** [comment]
Hi @RaulPL I've updated the link to a [public document](https://docs.google.com/document/d/1EPaKng2zaXfKEK9EIY59CgoIpUiitp3-_XvpNeJY6sM/edit?usp=sharing). Thanks for pointing this out!
