### ISSUE TITLE
Install pyro on system with Cuda 10

### ISSUE THREAD

**Issue by vsuhasm** [pyro-ppl/pyro#2625]
Please provide the following details:
--------------------------------------------------------------------------------------------------
### Issue Description
I wish to install pyro on a system with Cuda 10 and Nvidia driver version 410.72. However, installing pyro with pip requires torch >= 1.5, which does not support Cuda 10. Any suggestions?

### Environment
 - OS: CentOS Linux release 7.5.1804 (Core) 
 - Python version: 3.7
 - GCC version: (GCC) 6.2.0
 - CUDA runtime version: 10.0.130
 - GPU models and configuration: GPU 0: Tesla V100-PCIE-16GB
 - Nvidia driver version: 410.72

**Comment by fritzo** [comment]
Hi @vsuhasm you should be able to install an [older version of PyTorch](https://pytorch.org/get-started/previous-versions/) with an older version of Pyro, something like this:
```sh
# CUDA 10.1
conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch
pip install pyro-ppl==1.3.0
```
Let me know if that doesn't work.
