### ISSUE TITLE
Improper guide does not raise exception

### ISSUE THREAD

**Issue by xidulu** [pyro-ppl/pyro#2628]
Hi, I am trying to implement a 2 component Gaussian Mixture model with Relaxed Bernoulli as the posterior:

```python
T = 0.5
def model(data):
    weights = pyro.param('weights', torch.tensor(0.5))
    locs = pyro.param('locs', torch.randn(2,))
    with pyro.plate('data', len(data)):
        assignment = pyro.sample('assignment',
                                 dist.Bernoulli(weights)).long()
        pyro.sample('obs', dist.Normal(locs[assignment], 1.0), obs=data)

def guide(data):
    alpha = pyro.param('alpha', torch.rand(len(data)), constraints.unit_interval)
    with pyro.plate('data', len(data)):
        pyro.sample('assignment', dist.RelaxedBernoulli(torch.tensor(T), probs=alpha))
```

During one of my experiments, I deliberately set the posterior for `assignment` to be RelaxedBernoulli, a continuous distribution with support on (0, 1), I was expecting an error to be thrown out because the evaluation of the likelihood requires indexing from gaussian components ```locs[assignment]```, which is not possible for continuous samples from `assignment`. However, the SVI could still run without trouble.

**Comment by fehiepsi** [comment]
@xidulu In your model, assignment is converted to `long` tensor (`assignment = pyro.sample(...).long()`). So you can use it for indexing.

**Comment by xidulu** [comment]
@fehiepsi 
Your are right! Thanks for your help.
