### ISSUE TITLE
[bug] HiddenLayer include_hidden_bias incorrect behaviour

### ISSUE THREAD

**Issue by alexander-belikov** [pyro-ppl/pyro#2639]
### Issue Description
As far as I understand HiddenLayer implements functionality of a pytorch Linear layer + an activation function (with probabilistic weights, of course).

So the expected signatures of input and output tensors should be the same.

I see a problem with include_hidden_bias=True.

In pytorch 
```python
X : (nbatch, dim_input) : input
A : (dim_output, dim_input) : weight
B : (dim_output) : bias
```

then output is 

`y = XA^T + b`

and has dimensions (nbatch, dim_output) whether bias is used or not.

In the current pyro bnn implementation: [here](https://github.com/pyro-ppl/pyro/blob/b31963692e176a5099027dd4837c8a4cfe673a75/pyro/contrib/bnn/hidden_layer.py#L108
) and [here](https://github.com/pyro-ppl/pyro/blob/b31963692e176a5099027dd4837c8a4cfe673a75/pyro/contrib/bnn/utils.py#L14)

```python
if self.include_hidden_bias:
	activation = adjoin_ones_vector(activation)
```

bias is added as an extra dimension to the output dimensions (!), after activation (?!).

In other words, whether include_hidden_bias=True or False, the dimensions of output will be either (nbatch, dim_output) or (nbatch, dim_output+1). I do not think this expected behaviour. Bias should be sampled probabistitically as well as the weight tensor and added (not concatenated !) in [here](https://github.com/pyro-ppl/pyro/blob/b31963692e176a5099027dd4837c8a4cfe673a75/pyro/contrib/bnn/hidden_layer.py#L95) and [here](https://github.com/pyro-ppl/pyro/blob/b31963692e176a5099027dd4837c8a4cfe673a75/pyro/contrib/bnn/hidden_layer.py#L101)

Here is a snippet to demonstrate the issue with dimensions:

```python
import pyro.contrib.bnn as bnn
import torch
B, D, H = 3, 5, 7
inp = torch.ones(B, D)
m = torch.ones(D, H)
s = torch.ones(D, H)
hl_bias = bnn.HiddenLayer(inp, m, s, include_hidden_bias=True)
hl = bnn.HiddenLayer(inp, m, s, include_hidden_bias=False)
print(hl_bias().shape, hl().shape)

> torch.Size([3, 8]) torch.Size([3, 7])
```

It is possible I am missing something, but I am almost certain the current behaviour is not correct. 

### Environment
For any bugs, please provide the following:
- pytorch version: 1.6.0
 - Pyro version: 1.4.0

**Comment by martinjankowiak** [comment]
hello,

this was the intended behavior. it's just a convenience method for the case where you're stringing together multiple layers. if you have layer1 followed by layer2, the way you include a bias term in layer2 is by setting `include_hidden_bias=True` in layer1. this isn't a great API, but that was the intention. in any case this is quite old code that should probably be deprecated, as its API hasn't evolved along with the rest of pyro. for a more principled (but still experimental) approach to bayesian neural networks in pyro please refer to [tyxe](https://github.com/karalets/TyXe).

**Comment by alexander-belikov** [comment]
Thank you for such a quick reply, clear explanation and a good reference.

Stringing layers is exactly what I was trying to do, and I found odd that the output dimension is different from what is set in the constructor, but all right, as long as it was intended.
