### ISSUE TITLE
sampling from ZeroInflatedPoisson

### ISSUE THREAD

**Issue by rojinsafavi** [pyro-ppl/pyro#2661]
Hello,
I am new to Pyro tool, thanks for providing such a great package.
I was wondering if there is a wat to sample from a ZeroInflatedPoisson instead of a normal distribution for the VAE example?

Thank you very much

**Comment by fritzo** [comment]
Hi @rojinsafavi, there are a few places to replace `Normal` with `ZeroInflatedPoisson` in the VAE example. It should be easy to replace the observation likelihood with `ZeroInflatedPoisson`; see for example the [scANVI example](https://github.com/pyro-ppl/pyro/blob/f9dee1e2cd494a2c473b09d9ffb6098ab16dc105/examples/scanvi/scanvi.py#L211). It is much more difficult to replace the latent variable by a discrete distribution; I believe discrete-latent VAEs are still a subject of research.

In the future, feel free to ask questions on https://forum.pyro.ai; your response time should be quicker and your question will be more discoverable.
