### ISSUE TITLE
Elbo.compute_marginals throws an error for basic model

### ISSUE THREAD

**Issue by sky660099** [pyro-ppl/pyro#2678]
As @Bart mentioned in this forum question :
https://forum.pyro.ai/t/elbo-compute-marginals-throws-an-error-for-basic-model/2245

When observed variables has no enumerated ancestors, this error of compute_marginals will arise:
"ValueError: Number of einsum subscripts must be equal to the number of operands."

Now this error can be fixed by adding a dummy upstream discrete node, but a formal fix is needed.

**Comment by fritzo** [comment]
copying the minimum working example from the forum:

<details>

```py
@config_enumerate()
def model(a=None, b=None):
    a = sample("a", dist.Bernoulli(0.75), obs=a)
    p = 1-0.25*a
    b = sample("b", dist.Bernoulli(p), obs=b)

elbo = pyro.infer.TraceEnum_ELBO()

# This works.
elbo.compute_marginals(model, guide, b=tt(1.))

# These fail.
elbo.compute_marginals(model, guide, a=tt(1.))
elbo.compute_marginals(model, guide)
```

</details>
