### ISSUE TITLE
lift to memoize samples

### ISSUE THREAD

**Issue by jpchen** [pyro-ppl/pyro#269]
taken from #266 :
lift doesn't quite work properly when param is called with the same name twice in a stochastic function. This is not allowed for sample but is currently fine to do with param, since the second call just retrieves the same value from the parameter store.

**Comment by eb8680** [comment]
@jpchen this seems like an easy fix, do you want to get this into 0.3?

**Comment by jpchen** [comment]
yeah i can do this, it's not a release blocker though.
