### ISSUE TITLE
Trace_dist must be trace posterior distribution object when i ran code in tutorial.

### ISSUE THREAD

**Issue by lwgkzl** [pyro-ppl/pyro#2694]
### Description
 I'm having problems with the code I'm running in tutorial:   
https://bookdown.org/robertness/causalml/docs/tutorial-on-deep-probabilitic-modeling-with-pyro.html
codes:
![image](https://user-images.githubusercontent.com/30727306/98455980-8984a900-21b2-11eb-829a-cb98779b24fe.png)

error: 
![image](https://user-images.githubusercontent.com/30727306/98455987-ac16c200-21b2-11eb-885f-9d72b2f995fa.png)

thanks for any help!

### Environment
For any bugs, please provide the following:
 - OS and python version.  windows 10,   Python 3.8.3
 - PyTorch version  1.6.0
 - Pyro version: 1.5.0

**Comment by fehiepsi** [comment]
@lwgkzl The API of MCMC has changed since that tutorial is written. To get posterior samples, you can use
```python
mcmc = MCMC(...)
mcmc.run(...)
posterior = mcmc.get_samples()
```

**Comment by lwgkzl** [comment]
> @lwgkzl The API of MCMC has changed since that tutorial is written. To get posterior samples, you can use
> 
> ```python
> mcmc = MCMC(...)
> mcmc.run(...)
> posterior = mcmc.get_samples()
> ```

Many thanks : )

**Comment by lwgkzl** [comment]
> @lwgkzl The API of MCMC has changed since that tutorial is written. To get posterior samples, you can use
> 
> ```python
> mcmc = MCMC(...)
> mcmc.run(...)
> posterior = mcmc.get_samples()
> ```
After this line of code is run：
```samples_posterior = mcmc.get_samples()```
The type of variable ```samples_posterior``` is still not ```TracePosterior```, so  when i run the code: 
```marginal = EmpiricalMarginal(samples_posterior , "weight")```
 The error still exists, did I not understand what you meant?

**Comment by fehiepsi** [comment]
Hi @lwgkzl, you don't need to use `EmpiricalMarginal` to plot histogram. You can plot samples in `samples_posterior` directly.

**Comment by lwgkzl** [comment]
> Hi @lwgkzl, you don't need to use `EmpiricalMarginal` to plot histogram. You can plot samples in `samples_posterior` directly.

ありがとうございました
