### ISSUE TITLE
Enable validation by default?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2700]
An issue I often see with new users is that they forget to enable validation when creating new models. Moreover I find that even in production models, validation is cheap enough to enable always. When speed matters, we usually JIT compile, and the JIT implementations generally disable validation, so enabling validation by default wouldn't slow down any of those users. Moreover all our tutorials specify `pyro.enable_validation() # Always a good idea.` so maybe we should act on that comment. Finally, when adding validation to our examples in #2701, I discovered a number of bugs, suggesting validation is indeed helpful.

Should we `enable_validation(True)` or `__debug__` by default in the next release?

cc @neerajprad @fehiepsi

**Comment by fehiepsi** [comment]
I just wonder if we need to worry about some expensive constraint checks (e.g. positive_definite). Validating models by default is nice to me.

**Comment by fritzo** [comment]
> need to worry about some expensive constraint checks

Well users can always `pyro.enable_validation(False)` if they want to speed up a model. But that's the last step in

> ["first make it work, then make it right, and, finally, make it fast"](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast#:~:text=%22Make%20it%20work%2C%20make%20it,to%20DesignForPerformance%20ahead%20of%20time.)

**Comment by fehiepsi** [comment]
> users can always pyro.enable_validation(False)

We should think about how to deliver this message. For now, many users might not know about this utility.

**Comment by fritzo** [comment]
@fehiepsi good point. I guess we can
1. Expand the docstring of `pyro.enable_validation()` and ensure it appears in pyro.primitives
2. Create a short tutorial entitled "Make it work, make it correct, make it fast" detailing tips on computational Bayesian workflow. Like "first here's how to avoid shape errors", then "here's how to avoid NANs", finally "here's how to speed up your code".

**Comment by fehiepsi** [comment]
Thanks, Fritz! Looks great to me.
