### ISSUE TITLE
Allow size == 1 in funsor IndepMessenger

### ISSUE THREAD

**Issue by ordabayevy** [pyro-ppl/pyro#2737]
@eb8680 can you allow `size == 1` here:

https://github.com/pyro-ppl/pyro/blob/e39d36c758cf1ca9a16b75909c793b06a8dabdd6/pyro/contrib/funsor/handlers/plate_messenger.py#L30

I ran into this issue when `PlateMessenger` has `subsample_size=1` . Pyro `IndepMessenger` only [checks](https://github.com/pyro-ppl/pyro/blob/e39d36c758cf1ca9a16b75909c793b06a8dabdd6/pyro/poutine/indep_messenger.py#L57) for `size!=0`:

**Comment by eb8680** [comment]
Resolved in #2741
