### ISSUE TITLE
[feature request] Stan like constraints

### ISSUE THREAD

**Issue by mandel** [pyro-ppl/pyro#2756]
Stan supports multiples kind of constraints on parameters (https://mc-stan.org/docs/2_26/reference-manual/vector-and-matrix-data-types.html). To translate Stan models into Pyro, it would be convenient to have the same constraints implemented in Pyro.

Here is the list of constraints (the marked ones are already supported):
- [x] lower bound (`<lower=...>`): greater or equal
- [x] upper bound (`<upper=...>`): lower or equal
- [x] interval (`<lower=..., upper=...>`)
- [x] unit simplex (`simplex`): vector with non-negative values whose entries sum to 1
- [x] unit vector (`unit_vector`): vector with a norm of one
- [x] ordered vector (`ordered`): vector whose entries are sorted in ascending order
- [x] positive, ordered vector (`positive_ordered`): ordered vector where all entries are constrained to be positive
- [x] covariance matrix (`cov_matrix`): symmetric and positive definite matrix
- [x] correlation matrix (`corr_matrix`): symmetric and positive definite matrix, that has entries between −1 and 1, and has a unit diagonal
- [x] cholesky factors of covariance matrices (`cholesky_factor_cov`): https://mc-stan.org/docs/2_26/reference-manual/vector-and-matrix-data-types.html#cholesky-factors-of-covariance-matrices
- [x] cholesky factors of correlation matrices (`cholesky_factor_corr`): https://mc-stan.org/docs/2_26/reference-manual/vector-and-matrix-data-types.html#cholesky-factors-of-correlation-matrices

**Comment by fritzo** [comment]
Pyro's dev branch already has a few of those [constraints](http://docs.pyro.ai/en/dev/distributions.html#module-pyro.distributions.constraints):
- `greater_than_eq` and `greater_than` (corresponding to Stan's `lower` I believe)
- `corr_cholesky_constraint` soon to be renamed to `corr_cholesky` as in PyTorch
- `ordered_vector` (corresponding to Stan's `ordered`)
- `sphere` (corresponding to Stan's `unit_vector`; I plan to port this to NumPyro soon)

**Comment by fehiepsi** [comment]
Thanks, @mandel! Beside some mentioned above by @fritzo, for NumPyro, there is
+ `corr_matrix` (to be ported to Pyro soon)

Currently, in your list, Pyro and NumPyro is missing:
+ `positive_ordered` (IIUC the corresponding transform will be `ExpTransform(OrderedTransform())`)

**Comment by fritzo** [comment]
Thanks to @fehiepsi for adding the missing constraints! These are now available in Pyro's dev branch. We're planning a next release sometime in March, just after the release of PyTorch 1.8.
