### ISSUE TITLE
Softplus transform for AutoNormal scales [feature request]

### ISSUE THREAD

**Issue by vitkl** [pyro-ppl/pyro#2766]
Hi @fritzo @fehiepsi 

Following the conversation in numpyro issues (https://github.com/pyro-ppl/numpyro/issues/855#issuecomment-778250255) about the usefulness of softplus transform for AutoNormal scales, adding this feature request for further discussion here.

Requires https://github.com/pytorch/pytorch/pull/52300

**Comment by fritzo** [comment]
Thanks @vitkl!  Mind if I sketch a potential solution for discussion?
