### ISSUE TITLE
Update pyro.param to read event_dim from the constraint

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2795]
#1796 added an `event_dim` kwarg to `pyro.param()`, which #2323 used to support subsampling in `AutoNormal` and `AutoDelta`. However now that constraints have an `.event_dim` attribute (https://github.com/pytorch/pytorch/pull/50547, https://github.com/pytorch/pytorch/pull/50581), we can deprecate `pyro.param`'s `event_dim` kwarg and read that directly off the `constraint` kwarg.

**Comment by Padarn** [comment]
@fritzo do you also want to refactor `nn.PyroParam` to get rid of the `event_dim` argument? It seems like it'll have to stay for `subsample` too right?

**Comment by fehiepsi** [comment]
I think event_dim kwarg has been used to decide if we want to subsample a parameter so we need a way to tell the inference algorithms that we want to subsample over a parameter.

**Comment by Padarn** [comment]
Right.. removing it specifically from pyro.param seems reasonable but there seems to be little use of this. The use in subsample seems distinct. (But I may be totally wrong here, fresh set of eyes)

**Comment by fritzo** [comment]
Hmm I don't see a clean way to resolve this issue, given that we want to remain backwards compatible and as @fehiepsi `event_dim` is used to decide subsampling...

**Comment by Padarn** [comment]
It seems to me that you could remove `event_dim` from the `pyro.param()` and `PyroParms` use cases and rely on the constraint, and keep the subsample `event_dim`, but perhaps that isn't an improvement. It would as you say potentially break some backwards compatibility though.

**Comment by fritzo** [comment]
I think backwards compatibility outweighs the slight interface cleanup, so I think it's best to close this issue. @Padarn thanks for trying to address this, and @fehiepsi thanks for pointing out the subtleties!

**Comment by Padarn** [comment]
Completely agree. Thanks,
