### ISSUE TITLE
Model and guide event_dims disagree at site 'module$$$out.weight': 0 vs 1

### ISSUE THREAD

**Issue by tjucaokun** [pyro-ppl/pyro#2797]
### Issue Description
I want to implement the [Making Your Neural Network Say “I Don’t Know” — Bayesian NNs using Pyro and PyTorch](https://towardsdatascience.com/making-your-neural-network-say-i-dont-know-bayesian-nns-using-pyro-and-pytorch-b1c24e6ab8cd)
but when i run it , i got error.
`ValueError: Model and guide event_dims disagree at site 'module$$$out.weight': 0 vs 1`
i copy its module and guide here

```py
def model(x_data, y_data):
    
    fc1w_prior = Normal(loc=torch.zeros_like(net.fc1.weight), scale=torch.ones_like(net.fc1.weight))
    fc1b_prior = Normal(loc=torch.zeros_like(net.fc1.bias), scale=torch.ones_like(net.fc1.bias))
    
    outw_prior = Normal(loc=torch.zeros_like(net.out.weight), scale=torch.ones_like(net.out.weight))
    outb_prior = Normal(loc=torch.zeros_like(net.out.bias), scale=torch.ones_like(net.out.bias))
    
    priors = {'fc1.weight': fc1w_prior, 'fc1.bias': fc1b_prior,  'out.weight': outw_prior, 'out.bias': outb_prior}
    print(priors['out.weight'])
    # lift module parameters to random variables sampled from the priors
    lifted_module = pyro.random_module("module", net, priors)
    # sample a regressor (which also samples w and b)
    lifted_reg_model = lifted_module()
    
    lhat = log_softmax(lifted_reg_model(x_data))
    
    pyro.sample("obs", Categorical(logits=lhat), obs=y_data)
```
```py
def guide(x_data, y_data):

    # First layer weight distribution priors
    fc1w_mu = torch.randn_like(net.fc1.weight)
    fc1w_sigma = torch.randn_like(net.fc1.weight)
    fc1w_mu_param = pyro.param("fc1w_mu", fc1w_mu)
    fc1w_sigma_param = softplus(pyro.param("fc1w_sigma", fc1w_sigma))
    fc1w_prior = Normal(loc=fc1w_mu_param, scale=fc1w_sigma_param)
    # First layer bias distribution priors
    fc1b_mu = torch.randn_like(net.fc1.bias)
    fc1b_sigma = torch.randn_like(net.fc1.bias)
    fc1b_mu_param = pyro.param("fc1b_mu", fc1b_mu)
    fc1b_sigma_param = softplus(pyro.param("fc1b_sigma", fc1b_sigma))
    fc1b_prior = Normal(loc=fc1b_mu_param, scale=fc1b_sigma_param)
    # Output layer weight distribution priors
    outw_mu = torch.randn_like(net.out.weight)
    outw_sigma = torch.randn_like(net.out.weight)
    outw_mu_param = pyro.param("outw_mu", outw_mu)
    outw_sigma_param = softplus(pyro.param("outw_sigma", outw_sigma))
    outw_prior = Normal(loc=outw_mu_param, scale=outw_sigma_param).independent(1)
    # outw_prior = Normal(loc=outw_mu_param, scale=outw_sigma_param)
    # Output layer bias distribution priors
    outb_mu = torch.randn_like(net.out.bias)
    outb_sigma = torch.randn_like(net.out.bias)
    outb_mu_param = pyro.param("outb_mu", outb_mu)
    outb_sigma_param = softplus(pyro.param("outb_sigma", outb_sigma))
    outb_prior = Normal(loc=outb_mu_param, scale=outb_sigma_param)
    priors = {'fc1.weight': fc1w_prior, 'fc1.bias': fc1b_prior, 'out.weight': outw_prior, 'out.bias': outb_prior}
    print(priors['out.weight'])
    
    lifted_module = pyro.random_module("module", net, priors)
    
    return lifted_module()
```
how can i resolve this problem? i tried to add `.to_event()`after the variables (such as fc1w_prior) but it cause more errors

### Environment
 - ubuntu python 3.8.8
 - PyTorch 1.8.1+cu102
 - Pyro version: 1.6.0

Hope for some help . thanks a lot !!

**Comment by fritzo** [comment]
@tjucaokun you'll probably have better luck with questions like this on https://forum.pyro.ai, but I believe you can use `.to_event()` in most places:
```py
def model(...):
    fc1w_prior = Normal(loc=torch.zeros_like(net.fc1.weight),
                        scale=torch.ones_like(net.fc1.weight)).to_event(net.fc1.weight.dim())
    fc1b_prior = Normal(loc=torch.zeros_like(net.fc1.bias),
                        scale=torch.ones_like(net.fc1.bias)).to_event(net.fc1.bias.dim())
    ...
    pyro.sample("obs", Categorical(logits=lhat), obs=y_data).to_event(???)
```
and similarly in the guide. That will work for a single observation, but for multiple observations you should wrap the "obs" statement in a `with pyro.plate("data", len(x_data)): ...`.

Again, for further discussion it's better to use https://forum.pyro.ai so that discussion is discoverable.

**Comment by arm-on** [comment]
@fritzo I have searched a lot on this error. No real answer is available. Would you please clarify what you mean by "???" ?

**Comment by fritzo** [comment]
@arm-on the above snipped assumes all dimensions are event dimensions, so you should be able to call something like
```py
event_dim = max(lhat.dim() - 1, y_data.dim())
pyro.sample("obs", Categorical(logits=lhat).to_event(event_dim), obs=y_data)
```

**Comment by tgeller08** [comment]
I had the same issue and was not able to fix it by manually setting the event dimensions. When trying to run the code, I recommend installing an earlier version of pyro (ex: !pip3 install pyro-ppl==1.4.0) in the notebook instead as a temporary fix. I am still trying to figure out how to fix it.

**Comment by arm-on** [comment]
> I had the same issue and was not able to fix it by manually setting the event dimensions. When trying to run the code, I recommend installing an earlier version of pyro (ex: !pip3 install pyro-ppl==1.4.0) in the notebook instead as a temporary fix. I am still trying to figure out how to fix it.

Hi
I eventually fixed the code by installing the previous versions of all of the necessary packages. Here is my code:
https://github.com/arm-on/interpretable-image-classification/blob/main/bayesian-nn/MNIST_Bayesian_Training.ipynb

**Comment by peace-andjoy** [comment]
> > I had the same issue and was not able to fix it by manually setting the event dimensions. When trying to run the code, I recommend installing an earlier version of pyro (ex: !pip3 install pyro-ppl==1.4.0) in the notebook instead as a temporary fix. I am still trying to figure out how to fix it.
> 
> Hi I eventually fixed the code by installing the previous versions of all of the necessary packages. Here is my code: https://github.com/arm-on/interpretable-image-classification/blob/main/bayesian-nn/MNIST_Bayesian_Training.ipynb

thank you soooo muuuuch!! it perfectly solved my problem

**Comment by arm-on** [comment]
> 

You're welcome :) give it a star if you liked it.

**Comment by peace-andjoy** [comment]
> 

sure!
