### ISSUE TITLE
[FR]: Example of Predictive with MCMC sampling

### ISSUE THREAD

**Issue by fonnesbeck** [pyro-ppl/pyro#2803]
There are currently no examples in the docs and tutorials of `Predictive` being used in MCMC sampling. Given its importance in returning deterministic values of interest from models, it would probably be useful for users to be able to see how they are used.

**Comment by mtsokol** [comment]
Hi! 
Is it open as a good-first-issue? If yes then I would like to try it. 
I haven't used `pyro` (only TFP) so I would be grateful if you could point out which examples from http://pyro.ai/examples I can refer to and follow while writing it.

**Comment by fritzo** [comment]
Hi @mtsokol, yes this would be a good first issue.

But wait, it looks like the [Bayesian Regression II tutorial](http://pyro.ai/examples/bayesian_regression_ii.html) and the [baseball example](http://pyro.ai/examples/baseball.html) use MCMC and `Predictive`.  @fonnesbeck can you suggest how we might improve these tutorials and examples to make `Predictive` easier to understand?

**Comment by fonnesbeck** [comment]
My mistake--did not notice it in the baseball example. One minor suggestion is for important classes like `Predictive` to have links in the API docs to where it is used in the examples. I think Tensorflow does this (not sure if its done automatically or manually).

**Comment by mtsokol** [comment]
Hi @fritzo! Sorry for the delay and thank you for a guidance!

I did a short (draft with possible errors and misunderstanding) notebook in a "tutorial" way that utilizes `deterministic`, `Predictive` and `MCMC` with the model you provided. But it's pretty short and it repeats content from existing tutorials so I don't think it's worth it. (However writing it was a great way to familiarize myself with the library!)

I can search for another issue in `pyro` or `numpyro` or continue this notebook according to your tips if you consider it worthwhile. What do you think?

Links to the notebook:
https://nbviewer.jupyter.org/gist/mtsokol/fe00f78bb0b925f986d241622c2ec019
https://gist.github.com/mtsokol/fe00f78bb0b925f986d241622c2ec019

(I focused on explaining `deterministic`, `rate` variable and `GammaPoisson` distribution)

**Comment by fritzo** [comment]
Hi @mtsokol your notebook looks great!  Even though it is simple, I still think it is worth publishing it and adding to the index, so feel free to submit a PR.

I think the following additions would also help users:
- Include both words "Predictive" and "Deterministic" in the notebook title, to help users find content.
- Add a paragraph linking to other tutorials and examples that use `Predictive` and `pyro.deterministic`, so users can see other uses.
- Maybe also add a section on SVI, so users can see the different way to construct a `Predictive` object.
- Maybe in a follow-up PR add an Advanced Usage section showing how simple uses of `Predictive` could be replaced with either replay+trace as in
  ```py
  guide_trace = poutine.trace(guide).get_trace(*args, **kwargs)
  model_trace = poutine.trace(poutine.replay(model, guide_trace)).get_trace(*args, **kwargs)
  ```
  or condition+trace as in
  ```py
  samples = mcmc.get_samples()
  vectorize = pyro.plate("particles", num_particles, dim=-model_specific_dim)
  trace = poutine.trace(poutine.condition(vectorize(model), samples)).get_trace(*args, **kwargs)
  ``` 
  (I find that in complex situations I often need to write custom code like this).

Anyway, don't hesitate to put up a PR even for a small notebook, and thanks for writing this!

**Comment by khsibr** [comment]
Hi @mtsokol 
Don't you need to add a bias term in the regression?
Also, it would nice to add a line explaining why `GammaPoisson` is appropriate for this example.

Thanks!

**Comment by mtsokol** [comment]
Hi @khsibr!

The model I used here was suggested by @fritzo a few comments before so I can't really elaborate why it's designed that way.

I've just opened a PR with updated notebook #2852 where we can continue discussion.

**Comment by fritzo** [comment]
Completed in #2857
