### ISSUE TITLE
SVI example has math error in posterior variance for beta-bernoulli model

### ISSUE THREAD

**Issue by murphyk** [pyro-ppl/pyro#2817]
In [the svi part 1 example](https://pyro.ai/examples/svi_part_i.html),  it should be
```
post_mean = alpha_q / (alpha_q + beta_q)
post_var = (post_mean * beta_q)/((alpha_q + beta_q) * (alpha_q + beta_q + 1))
post_std = np.sqrt(post_var)
```
You can verify this matches the HMC results...

**Comment by martinjankowiak** [comment]
thanks for the suggestion @murphyk . however your formula is equivalent to the formula in the tutorial, just factored differently

**Comment by murphyk** [comment]
Ahh yes, you are right. :)
