### ISSUE TITLE
[bug] Runtime error during SVI inference when using poutine.do()

### ISSUE THREAD

**Issue by h1psta** [pyro-ppl/pyro#2845]
### Issue Description

Setting: a simple model with 2 latent Gaussians z1 and z2, giving rise to x ~ N( z1+z2, I).

In this setting p(z2 | x, z1) should be the same as p(z2 | x, do(z1)). 

I wanted to check whether the current Pyro interface reflects this and it seems it does not.

My initial thought is that there is a difference in how .do() and .condition() broadcast the constants across the plate context.

### Environment

 - OS and python version: MacOS 10.14.6, Python: 3.8.6
 - PyTorch version: 1.9.0.dev20210502 (nightly version)
 - Pyro version: 1.6.0.

### Code Snippet

Replication code:
https://pastebin.com/Ki2PYX7z

**Comment by eb8680** [comment]
@h1psta thanks for reporting this and providing a reproducible test case, this is indeed a bug in `pyro.poutine.do`. I will push a fix now.
