### ISSUE TITLE
Renaming the Sine Bivariate Von Mises Distribution to the Sine Distribution 

### ISSUE THREAD

**Issue by OlaRonning** [pyro-ppl/pyro#2855]
The [`dist.SineBivariateVonMises`](https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/sine_bivariate_von_mises.py#L18) distribution is really a submodel, commonly known as the Sine Distribution in directional statistics, of the class of Bivariate von Mises distribution. Therefore, for consistency, I should have called the Pyro implementation of the distribution `Sine`.  

I'll make a PR resolving this if there are no concerns about the renaming.

**Comment by fehiepsi** [comment]
Hi @OlaRonning, if you want to rename the distribution, it is better to do it before the release. :) Personally, I think the verbose name `SineBivariateVonMises` is better than the short name `Sine`.

**Comment by OlaRonning** [comment]
Hi @fehiepsi, thanks for your input. I agree that it would be preferable to fix this before it was merged. I, however, was not aware that this was an "issue" at the time. 

I also lean towards the verbose name (which I why I used it :-).  Maybe a better solution is to just highlight that it's the submodel called the Sine Distribution in the DocString. What do you think?

**Comment by fritzo** [comment]
I like the longer `SineBivariateVonMises`.  As n00b I would guess that a `Sine` distribution would be maybe a 1-parameter subdistribution of the univariate `VonMises` distribution, where the log density is an affine transform of `sin(theta)`.
