### ISSUE TITLE
Examples for classification deep learning model

### ISSUE THREAD

**Issue by tonylin52** [pyro-ppl/pyro#2911]
Hi,

Is there any example code for classification deep learning model in terms of pyro? 
I have found one or two on Internet, and none of them are runnable...

https://paper.yanxishe.com/TextTranslation/1301

thanks

**Comment by eb8680** [comment]
@tonylin52 if you mean Bayesian neural networks like the one in your link, we recommend you check out [TyXe](https://github.com/TyXe-BDL/TyXe). You can also find lots of examples and snippets on our [forum](https://forum.pyro.ai/).

**Comment by eb8680** [comment]
Closing, feel free to follow up on the forum.
