### ISSUE TITLE
the previous version of pyro

### ISSUE THREAD

**Issue by lbq8942** [pyro-ppl/pyro#2922]
where can i find the the previous version of pyro?today i install pyro-ppl,but it automatic update pytorch 1.9。my pytorch is 1.8。i dont want to update pytorch but want to get the the previous version of pyro

**Comment by fritzo** [comment]
You pin the version of any package [via pip](https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers), e.g.
```sh
pip install pyro-ppl==1.6.0
```
You can see Pyro's release history [on pypi.org](https://pypi.org/project/pyro-ppl/#history) or [on github](https://github.com/pyro-ppl/pyro/releases).
