### ISSUE TITLE
pyro.param cannot be set to CPU correctly

### ISSUE THREAD

**Issue by hejj16** [pyro-ppl/pyro#2935]
### Issue Description

Even if the parameters I pass in ```pyro.param()``` are on the gpu, the returned param are still on cpu.

### Environment
For any bugs, please provide the following:
 - python 3.7, Ubuntu 18.04.5 LTS
 - PyTorch version 1.9.0+cu102
 - pyro 1.7.0
 - 
### Code Snippet
```
pyro.param("alpha_loc", torch.rand(3).cuda()).device
```

**Comment by fritzo** [comment]
Hi @hejj16 can you just be sure you've called `pyro.clear_param_store()` before inference? I wonder if an old CPU value is leaking into this run.

**Comment by hejj16** [comment]
> Hi @hejj16 can you just be sure you've called `pyro.clear_param_store()` before inference? I wonder if an old CPU value is leaking into this run.

Oh you are right. Sorry for my carelessness
