### ISSUE TITLE
About ValueError: Shape mismatch inside plate('data') at site obs

### ISSUE THREAD

**Issue by AmyTanJ** [pyro-ppl/pyro#2969]
When I try to construct a VAE model, I receive the following error, I don't know how to debug it.
![image](https://user-images.githubusercontent.com/73063292/141705630-af20d648-7878-4b7b-b465-71618423e936.png)

This is the code of the model, the dimension of my data is [1000, 1, 20, 10]
```python
class VAE(nn.Module):
    def __init__(self, n_inch, n_latent):
        super().__init__()
        self.n_latent = n_latent
        self.n_inch = n_inch
        self.decoder = Decoder(n_inch,n_latent,100)
        self.encoder = Encoder(n_inch,n_latent,100)

    def model(self, x):
        # register PyTorch module `decoder` with Pyro
        pyro.module("decoder", self.decoder)
        with pyro.plate("data", x.shape[0]):
            # setup hyperparameters for prior p(z)
            z_loc = x.new_zeros(torch.Size((x.shape[0], self.n_latent)))
            z_scale = x.new_ones(torch.Size((x.shape[0], self.n_latent)))
            z = pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
            # decode the latent code z
            px_scale = self.decoder(z)
            x_loc =  px_scale
            x_scale = torch.exp(x_loc)
            # score against actual images
            rx = pyro.sample("obs", dist.Normal(x_loc, x_scale).to_event(1), obs=x)
            return rx
         
    def guide(self, x):
        # register PyTorch module `encoder` with Pyro
        pyro.module("encoder", self.encoder)
        with pyro.plate("data", x.shape[0]):
            # use the encoder to get the parameters used to define q(z|x)
            [z_loc, z_scale] = self.encoder(x)
            # sample the latent code z
            rz=pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
            return rz
```

**Comment by fritzo** [comment]
Hi @AmyTanJ, Could you paste some more details of the shapes of things, e.g. by adding logging statements as below and pasting the output? It would be easier for me to help debug if I could see more tensor sizes. My blind guess is that you'll need to change the event dimension to be 2 if you're working with 2d images:
```diff
- .to_event(1)
+ .to_event(2)
```

Logging statements:
<details>

```diff
  class VAE(nn.Module):
      def __init__(self, n_inch, n_latent):
          super().__init__()
          self.n_latent = n_latent
          self.n_inch = n_inch
+         print(f"DEBUG n_inch = {n_inch}")
+         print(f"DEBUG n_latent = {n_latent}")
          self.decoder = Decoder(n_inch,n_latent,100)
          self.encoder = Encoder(n_inch,n_latent,100)
  
      def model(self, x):
          # register PyTorch module `decoder` with Pyro
          pyro.module("decoder", self.decoder)
          with pyro.plate("data", x.shape[0]):
              # setup hyperparameters for prior p(z)
              z_loc = x.new_zeros(torch.Size((x.shape[0], self.n_latent)))
              z_scale = x.new_ones(torch.Size((x.shape[0], self.n_latent)))
              z = pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
              # decode the latent code z
              px_scale = self.decoder(z)
+             print(f"DEBUG px_scale.shape = {tuple(px_scale.shape)}")
              x_loc =  px_scale
              x_scale = torch.exp(x_loc)
              # score against actual images
              rx = pyro.sample("obs", dist.Normal(x_loc, x_scale).to_event(1), obs=x)
              return rx

      def guide(self, x):
+         print(f"DEBUG x.shape = {tuple(x.shape)}")
          # register PyTorch module `encoder` with Pyro
          pyro.module("encoder", self.encoder)
          with pyro.plate("data", x.shape[0]):
              # use the encoder to get the parameters used to define q(z|x)
              [z_loc, z_scale] = self.encoder(x)
+             print(f"DEBUG z_loc.shape = {tuple(z_loc.shape)}")
+             print(f"DEBUG z_scale.shape = {tuple(z_scale.shape)}")
              # sample the latent code z
              rz=pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
              return rz
```

</details>

**Comment by AmyTanJ** [comment]
> Hi @AmyTanJ, Could you paste some more details of the shapes of things, e.g. by adding logging statements as below and pasting the output? It would be easier for me to help debug if I could see more tensor sizes. My blind guess is that you'll need to change the event dimension to be 2 if you're working with 2d images:
> 
> ```diff
> - .to_event(1)
> + .to_event(2)
> ```
> 
> Logging statements:
> 
> ```diff
>   class VAE(nn.Module):
>       def __init__(self, n_inch, n_latent):
>           super().__init__()
>           self.n_latent = n_latent
>           self.n_inch = n_inch
> +         print(f"DEBUG n_inch = {n_inch}")
> +         print(f"DEBUG n_latent = {n_latent}")
>           self.decoder = Decoder(n_inch,n_latent,100)
>           self.encoder = Encoder(n_inch,n_latent,100)
>   
>       def model(self, x):
>           # register PyTorch module `decoder` with Pyro
>           pyro.module("decoder", self.decoder)
>           with pyro.plate("data", x.shape[0]):
>               # setup hyperparameters for prior p(z)
>               z_loc = x.new_zeros(torch.Size((x.shape[0], self.n_latent)))
>               z_scale = x.new_ones(torch.Size((x.shape[0], self.n_latent)))
>               z = pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
>               # decode the latent code z
>               px_scale = self.decoder(z)
> +             print(f"DEBUG px_scale.shape = {tuple(px_scale.shape)}")
>               x_loc =  px_scale
>               x_scale = torch.exp(x_loc)
>               # score against actual images
>               rx = pyro.sample("obs", dist.Normal(x_loc, x_scale).to_event(1), obs=x)
>               return rx
> 
>       def guide(self, x):
> +         print(f"DEBUG x.shape = {tuple(x.shape)}")
>           # register PyTorch module `encoder` with Pyro
>           pyro.module("encoder", self.encoder)
>           with pyro.plate("data", x.shape[0]):
>               # use the encoder to get the parameters used to define q(z|x)
>               [z_loc, z_scale] = self.encoder(x)
> +             print(f"DEBUG z_loc.shape = {tuple(z_loc.shape)}")
> +             print(f"DEBUG z_scale.shape = {tuple(z_scale.shape)}")
>               # sample the latent code z
>               rz=pyro.sample("latent", dist.Normal(z_loc, z_scale).to_event(1))
>               return rz
> ```

Thank you for your reply, your blind guess is right！
Does it mean the x in `.to_event(x)`  represents the dimension of independent variables?

**Comment by fritzo** [comment]
Yes, `.to_event(x)` converts the rightmost `x` dimensions to be dependent (or an "event" in the language of probability), and those bundled events is independent of each other.

Glad that fixed your model, I'll close this issue now 🙂
