### ISSUE TITLE
pyro.render_model() fails to draw overlapping non-nested plates

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2980]
Due to [a shortcoming](https://stackoverflow.com/questions/12680865/how-to-draw-overlapping-clusters-in-graphviz) in [graphviz clusters](https://graphviz.org/Gallery/directed/cluster.html), Pyro's and NumPyro's [pyro.render_model()](https://docs.pyro.ai/en/latest/infer.util.html#pyro.infer.inspect.render_model) currently cannot render overlapping non-nested plates, e.g. the Venn diagram
```p
def model():
    plate1 = pyro.plate("plate1", 2, dim=-2)
    plate2 = pyro.plate("plate2", 3, dim=-1)
    with plate1:
        x = pyro.sample("x", dist.Normal(0, 1))
    with plate1, plate2:
        y = pyro.sample("y", dist.Normal(x, 1))
    with plate2:
        pyro.sample("z", dist.Normal(y.sum(-2, True), 1), obs=torch.zeros(3))

pyro.render_model(model)
```
![image](https://user-images.githubusercontent.com/648532/145103608-b0dcf75f-8a77-4b56-88dc-25d787a17b0b.png)

**Comment by eb8680** [comment]
One workaround would be to add an option to render with [daft](https://docs.daft-pgm.org/en/latest/), which handles plates correctly ([example](https://docs.daft-pgm.org/en/latest/examples/deconvolution/)).

**Comment by fritzo** [comment]
One optional would be to replace `graphviz` by [daft-pgm](https://docs.daft-pgm.org/en/latest/), which does support nested plates. However daft-pgm [does not support automatic node layout](https://github.com/daft-dev/daft/issues/122).

A more basic problem is that not all plate nesting patterns can be drawn by rectangular overlapping plates. Maybe we could use a generic venn diagram plotting library?

**Comment by fehiepsi** [comment]
@kpj [mentioned](https://github.com/pyro-ppl/numpyro/issues/949#issuecomment-793549236) that we can use graphviz to find positions then use daft for plotting. Probably that will work for a class of models.

**Comment by fehiepsi** [comment]
It seems that in numpyro, we have
![image](https://user-images.githubusercontent.com/4736342/145137100-16375ca4-6dfb-4eb9-a737-f7f76d27df03.png)
which can be seen as a temporary solution. What do you think @fritzo ?

**Comment by fritzo** [comment]
@fehiepsi that looks like a great solution, and I suspect the only fully general solution :+1:
