### ISSUE TITLE
[bug] AffineAutoregressive transform leads to exploding gradients

### ISSUE THREAD

**Issue by francois-rozet** [pyro-ppl/pyro#2998]
Please provide the following details:
--------------------------------------------------------------------------------------------------
### Issue Description

I implemented a basic Masked Autoregressive Flow (MAF) using the transform modules of `pyro`, notably `AffineAutoregressive`. For **all** my experiments, the flow learns correctly and the loss decreases until some point where the gradients suddenly explode. I tested with another library, namely `nflows`, and this issue does not arise.

I digged into both implementations and I believe the issue comes from the way the `scale` is extracted from the autoregressive network. In `pyro`, the `log_scale` is extracted from the network and clamped between two values. Firstly, this is highly restrictive in terms of estimator expressiveness. Secondly, i believe this introduces severe non-continuities in the gradients.

https://github.com/pyro-ppl/pyro/blob/7f1637de338889719f6f64e2b0b54bee95106227/pyro/distributions/transforms/affine_autoregressive.py#L131-L136

In `nflows`, the scale is extracted as a `softplus` of the network's output plus an epsilon for stability. This makes the resulting gradients much smoother.

https://github.com/bayesiains/nflows/blob/ac0bf432fc7904458a933ed14180f0ac26e3f93d/nflows/transforms/autoregressive.py#L101-L102

### Environment
Pyro 1.8.0
PyTorch 1.10.1

### Code Snippet
I can provide my codes, but I don't think this is relevant. However, I will (as soon as possible) edit pyro's implementation to copy nflows' one and see if it solves the problem.

**Comment by martinjankowiak** [comment]
@francois-rozet thanks for the detailed description. the normalizing flow library within this repo is no longer being actively developed. when the time is right we plan to switch to [flowtorch](https://flowtorch.ai/). 

not sure if this particular numerical issue appears in any of the flowtorch code base. any idea @stefanwebb ?

**Comment by francois-rozet** [comment]
I implemented the proposed changes (https://github.com/francois-rozet/pyro/commit/fa9d8e69ebb3c2f8c031d756be7c8130667faa6b) and, as I expected, using softplus (like `nflows`) instead of clamping completely solves the problem: the gradients don't explode anymore.
Should I make a PR since the library isn't developed anymore? Also when do you think flowtorch will be "ready" ? It does not seem to be under active development either.

**Comment by francois-rozet** [comment]
@stefanwebb Should I file an issue for FlowTorch as well? Or should I provide evidences first? It's hard to "prove" but I can simply show the losses ^^

**Comment by stefanwebb** [comment]
@francois-rozet could you please file an issue on FlowTorch (separate from the discussion thread there)?

I'm happy to switch over to the `softplus` solution if that is what's used in `nflows`, provided too that it works with some simple examples. Could you work on the change to `flowtorch.bijectors.ops.affine.Affine`? In the meanwhile, I will look into the implementations more to understand how they differ
