### ISSUE TITLE
Example for Stein Methods

### ISSUE THREAD

**Issue by chahak13** [pyro-ppl/pyro#3005]
Hi, is there an example implementation that uses Stein Methods for inference? I tried looking at the examples directory and documentation but couldn't find anything more extensive than the example function call in the code docs. Thanks for your help!

**Comment by martinjankowiak** [comment]
hello @chahak13 

there are some tests exercising stein methods [here](https://github.com/pyro-ppl/pyro/blob/b7ba915b851d51c61d805da741bf7a74fcf9319d/tests/infer/test_svgd.py)

i don't believe we have any example usage apart from that. personally i haven't had much luck with these methods. a PR showcasing additional usage would be welcome!
