### ISSUE TITLE
Contrib.GP DotProduct kernel has no `forward` method

### ISSUE THREAD

**Issue by nipunbatra** [pyro-ppl/pyro#3029]
Hi
As per my issue here: https://github.com/pyro-ppl/pyro/issues/3025#issuecomment-1055015321

I am trying to use `pyro.contrib.gp` for Classification. In my comment above, I showed the usage based on the `RBF` kernel. Next, when trying to use the `DotProduct` kernel as used in the [sklearn GP classification example](https://scikit-learn.org/stable/auto_examples/gaussian_process/plot_gpc_xor.html), I hit the following error.

```python
import pyro
import pyro.contrib.gp as gp
import numpy as np
import torch
import matplotlib.pyplot as plt

X = torch.randn(200, 2)
Y = torch.logical_xor(X[:, 0] > 0, X[:, 1] > 0).double()

kernel = gp.kernels.DotProduct(input_dim=2)

pyro.clear_param_store()
likelihood = gp.likelihoods.Binary()
model = gp.models.VariationalGP(
    X, Y, kernel, likelihood=likelihood, whiten=True, jitter=1e-03)
num_steps = 1000
loss = gp.util.train(model, num_steps=num_steps)
```

```python
File ~/miniforge3/lib/python3.9/site-packages/pyro/contrib/gp/kernels/kernel.py:55, in Kernel.forward(self, X, Z, diag)
     42 def forward(self, X, Z=None, diag=False):
     43     r"""
     44     Calculates covariance matrix of inputs on active dimensionals.
     45 
   (...)
     53     :rtype: torch.Tensor
     54     """
---> 55     raise NotImplementedError

NotImplementedError: 
Trace Shapes:
 Param Sites:
Sample Sites:
```

The `forward` method is implemented for the `Linear` and `Polynomial` kernels subclassing `DotProduct`, but not for `DotProduct` itself. 

The [sklearn GP kernel docs here](https://scikit-learn.org/stable/modules/gaussian_process.html#gp-kernels) define it as:

$k\left(x_{i}, x_{j}\right)=\sigma_{0}^{2}+x_{i} \cdot x_{j}$

I wanted to check if it is okay to implement the `forward` method for `DotProduct` kernel and if so, with what function definition?

**Comment by fehiepsi** [comment]
I think `Linear` behaves like your `DotProduct` usage. Maybe you can use it instead?

**Comment by nipunbatra** [comment]
Thanks, @fehiepsi 
The linear kernel won't suffice for the XOR classification problem, but Polynomial will suffice. I tested and got it to work to match the `sklearn` [like behaviour](https://scikit-learn.org/stable/auto_examples/gaussian_process/plot_gpc_xor.html#sphx-glr-auto-examples-gaussian-process-plot-gpc-xor-py). `1.0 * DotProduct(sigma_0=1.0) ** 2`


Thus, I'm closing this issue.
