### ISSUE TITLE
Issue while importing netcal library

### ISSUE THREAD

**Issue by rajat-tech-002** [pyro-ppl/pyro#3061]
File "/workspace/system-paper/main_util.py", line 23, in <module>
    from netcal.scaling import TemperatureScaling
  File "/opt/conda/lib/python3.6/site-packages/netcal/scaling/__init__.py", line 28, in <module>
    from .AbstractLogisticRegression import AbstractLogisticRegression
  File "/opt/conda/lib/python3.6/site-packages/netcal/scaling/AbstractLogisticRegression.py", line 26, in <module>
    import pyro
  File "/opt/conda/lib/python3.6/site-packages/pyro/__init__.py", line 4, in <module>
    import pyro.poutine as poutine
  File "/opt/conda/lib/python3.6/site-packages/pyro/poutine/__init__.py", line 4, in <module>
    from .handlers import (
  File "/opt/conda/lib/python3.6/site-packages/pyro/poutine/handlers.py", line 60, in <module>
    from .collapse_messenger import CollapseMessenger
  File "/opt/conda/lib/python3.6/site-packages/pyro/poutine/collapse_messenger.py", line 7, in <module>
    from pyro.distributions.distribution import COERCIONS
  File "/opt/conda/lib/python3.6/site-packages/pyro/distributions/__init__.py", line 4, in <module>
    import pyro.distributions.torch_patch  # noqa F403
  File "/opt/conda/lib/python3.6/site-packages/pyro/distributions/torch_patch.py", line 87, in <module>
    @patch_dependency("torch.distributions.constraints._CorrCholesky.check")
  File "/opt/conda/lib/python3.6/site-packages/pyro/distributions/torch_patch.py", line 18, in patch_dependency
    module = getattr(module, part)
AttributeError: module 'torch.distributions.constraints' has no attribute '_CorrCholesky'

**Comment by rajat-tech-002** [comment]
@fritzo , Sure
Output of pip freeze:
`absl-py==0.11.0
alabaster==0.7.12
apex==0.1
argon2-cffi==20.1.0
ascii-graph==1.5.1
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1600298409949/work
audioread==2.1.9
Babel==2.8.0
backcall==0.2.0
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
bleach==3.2.1
blis==0.4.1
boto3==1.16.11
botocore==1.19.11
brotlipy==0.7.0
cached-property==1.5.2
catalogue==1.0.0
certifi==2020.6.20
cffi @ file:///tmp/build/80754af9/cffi_1600699165083/work
chardet==3.0.4
click==7.1.2
codecov==2.1.10
conda==4.9.1
conda-build==3.20.5
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018143336/work
coverage==5.3
cryptography @ file:///tmp/build/80754af9/cryptography_1601047419573/work
cxxfilt==0.2.2
cycler==0.10.0
cymem==2.0.3
Cython==0.28.4
dataclasses==0.7
DataProperty==0.50.0
decorator==4.4.2
defusedxml==0.6.0
DLLogger @ git+git://github.com/NVIDIA/dllogger.git@26a0f8f1958de2c0c460925ff6102a4d2486d6cc
docutils==0.16
entrypoints==0.3
filelock==3.0.12
flake8==3.7.9
Flask==1.1.2
future==0.18.2
glob2==0.7
grpcio==1.33.2
h5py==3.0.0
html2text==2020.1.16
hypothesis==4.50.8
idna==2.9
imageio==2.9.0
imagesize==1.2.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
inflect==4.1.0
iniconfig==1.1.1
ipdb==0.13.4
ipykernel==5.3.4
ipython @ file:///tmp/build/80754af9/ipython_1593447367857/work
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi @ file:///tmp/build/80754af9/jedi_1598371618777/work
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.17.0
json5==0.9.5
jsonschema==3.0.2
jupyter-client==6.1.7
jupyter-core==4.6.3
jupyter-tensorboard==0.2.0
jupyterlab==1.2.14
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
jupytext==1.6.0
kiwisolver==1.3.1
libarchive-c==2.9
librosa==0.6.3
llvmlite==0.28.0
lmdb==1.0.0
Markdown==3.3.3
markdown-it-py==0.5.6
MarkupSafe==1.1.1
maskrcnn-benchmark @ file:///opt/pytorch/examples/maskrcnn/pytorch
matplotlib==3.3.2
mbstrdecoder==1.0.0
mccabe==0.6.1
mistune==0.8.4
mlperf-compliance==0.0.10
mock==4.0.2
msgfy==0.1.0
murmurhash==1.0.2
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.2
networkx==2.0
nltk==3.5
notebook==6.1.4
numba==0.43.1
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603483703303/work
nvidia-dali-cuda110==0.27.0
nvidia-pyprof @ git+https://github.com/NVIDIA/PyProf@c679342a21b1600a8a63e805b1a0b7198f449b74
nvidia-tensorboard @ file:///nvidia/opt/tensorboard_install/nvidia_tensorboard-1.15.0%2Bnv20.11-py3-none-any.whl
nvidia-tensorboard-plugin-dlprof @ file:///nvidia/opt/tensorboard_install/nvidia_tensorboard_plugin_dlprof-0.9-py3-none-any.whl
onnx @ file:///opt/pytorch/pytorch/third_party/onnx
onnxruntime==1.5.2
opencv-python==3.4.1.15
packaging==20.4
pandas==0.24.2
pandocfilters==1.4.3
parso==0.7.0
pathvalidate==2.3.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow-SIMD @ file:///tmp/pillow-simd
pkginfo==1.6.0
plac @ file:///tmp/build/80754af9/plac_1594261902054/work
pluggy==0.13.1
polygraphy==0.20.13
preshed==3.0.2
progressbar==2.5
prometheus-client==0.8.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.13.0
psutil @ file:///tmp/build/80754af9/psutil_1598370257337/work
ptyprocess==0.6.0
py==1.9.0
pybind11==2.6.0
pycocotools @ git+https://github.com/nvidia/cocoapi.git@6ac4a93058202603f36fd1ce47228e7d81119e5a#subdirectory=PythonAPI
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.20
pydot==1.4.1
pyflakes==2.1.1
Pygments @ file:///tmp/build/80754af9/pygments_1600458456400/work
pynvml==8.0.4
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1600141725711/work
PySocks==1.7.1
pytablewriter==0.47.0
pytest==6.1.2
pytest-cov==2.10.1
pytest-pythonpath==0.7.3
python-dateutil==2.8.1
python-hostlist==1.21
python-nvd3==0.15.0
python-slugify==4.0.1
pytorch-transformers==1.1.0
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.2
regex==2020.10.28
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
resampy==0.2.2
revtok @ git+git://github.com/jekbradbury/revtok.git@f1998b72a941d1e5f9578a66dc1c20b01913caab
ruamel-yaml==0.15.87
s3transfer==0.3.3
sacrebleu==1.2.10
sacremoses==0.0.35
scikit-image==0.15.0
scikit-learn==0.23.2
scipy @ file:///tmp/build/80754af9/scipy_1597686635649/work
Send2Trash==1.5.0
sentencepiece==0.1.94
six==1.15.0
snowballstemmer==2.0.0
SoundFile==0.10.3.post1
soupsieve==2.0.1
sox==1.4.1
spacy @ file:///tmp/build/80754af9/spacy_1600554229564/work
Sphinx==3.3.0
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
srsly==1.0.2
SSD @ file:///opt/pytorch/examples/ssd
subword-nmt @ git+git://github.com/rsennrich/subword-nmt.git@48ba99e657591c329e0003f0c6e32e493fa959ef
tabledata==1.1.3
tabulate==0.8.7
tensorboard @ file:///nvidia/opt/tensorboard_install/tensorboard-shim
tensorrt==7.2.1.6
terminado==0.9.1
testpath==0.4.4
text-unidecode==1.3
thinc @ file:///tmp/build/80754af9/thinc_1594251955397/work
threadpoolctl==2.1.0
toml==0.10.2
torch==1.8.0a0+17f8c32
torchtext @ file:///opt/pytorch/text
torchvision @ file:///opt/pytorch/vision
tornado==6.1
tqdm==4.31.1
traitlets==4.3.3
typepy==1.1.1
typing==3.7.4.3
typing-extensions==3.7.4.3
Unidecode==1.1.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
wasabi @ file:///tmp/build/80754af9/wasabi_1599244993840/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.10.11
yacs==0.1.8
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work`

**Comment by dilaragokay** [comment]
I have seen the same error when I upgraded pytorch and ran `import pyro` afterward. To solve this, the first thing I tried was uninstalling and installing pyro. Running
```
pip uninstall pyro
pip install pyro
```
showed
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. torchvision 0.11.3 requires torch==1.10.2, but you have torch 1.11.0 which is incompatible.
```
Eventually, I solved it by uninstalling both pytorch and pyro, then installing them again.

**Comment by dilaragokay** [comment]
> 

Exactly, thanks. I have edited the comment accordingly.

**Comment by dilaragokay** [comment]
> Hi @dilaragokay, I think you'll need to fix the pyro package name
> 
> ```diff
> - pip install pyro
> + pip install pyro-ppl
> ```

Exactly, thanks. I have edited the comment accordingly.

**Comment by fritzo** [comment]
@rajat-tech-002 you are using `torch==1.8.0a0+17f8c32` which is too old for your Pyro version. I'd recommend updating your versions
```sh
pip install -U torch torchvision pyro-ppl
```
