### ISSUE TITLE
Installing pyro on Colab keeps updating torch from 1.10 to 1.11

### ISSUE THREAD

**Issue by MaverickMeerkat** [pyro-ppl/pyro#3062]
Hi,

I'm using SBI which in-turns uses pyro. I noticed that installing pyro on Google Colab keeps updating the version to 1.11. This is something new that started a few weeks ago. Google Colab already comes with torch 1.10 installed - so is this update really necessary? And is there a way to circumvent it?

I'm running many simulations in different notebooks, and having to constantly reinstall torch (~750 mb) with every new environment is wasting a lot of time. 

Thanks

**Comment by fritzo** [comment]
Until google updates PyTorch you can prevent the update by pinning Pyro to an older version 1.8.0:
```
!pip install pyro-ppl==1.8.0
```

**Comment by MaverickMeerkat** [comment]
Thanks - this does seems to work!

I have to install pyro first, and then sbi.
