### ISSUE TITLE
TraceEnum_ELBO().compute_marginals gives unstable result

### ISSUE THREAD

**Issue by Tiantian-H** [pyro-ppl/pyro#3079]
### Issue Description
Hi,
I'm using TraceEnum_ELBO().compute_marginals to obtain the marginal distribution of a categorical discrete variable in SVI. However, I find that if I implement `TraceEnum_ELBO().compute_marginals` several times, I can get completely different distributions each time. I provided an example with code on the Pyro forum but haven't received any response yet. The link is: [pyro forum](https://forum.pyro.ai/t/traceenum-elbo-compute-marginals-gives-unstable-result/4153)

Please note I have fixed the seed and the starting point of SVI. I only trained the SVI once, but runs the TraceEnum_ELBO().compute_marginals several times and obtained different results each time.

I understand that the distribution is obtained by sampling, so I shouldn’t expect that the result is completely the same after each sampling. But I think the problem is from `TraceEnum_ELBO().compute_marginals` rather than the `pyro.sample` step because if I just implement `TraceEnum_ELBO().compute_marginals` only once and then implement `pyro.sample` several times then the distribution is much more stable. I want to know how can I fix this problem and get a more stable and reproducible result.

Thank you so much!
### Environment
For any bugs, please provide the following:
 - OS and python version: Python 3.7, Google Colab
 - PyTorch version: 1.11.0+cu113
 - Pyro version:  pyro-ppl-1.8.1

### Code Snippet
[pyro forum](https://forum.pyro.ai/t/traceenum-elbo-compute-marginals-gives-unstable-result/4153)

**Comment by eb8680** [comment]
Closing as a question, answering on the forum.

> I provided an example with code on the Pyro forum but haven't received any response yet.

We use GitHub for bug reports, feature requests and other development-related discussion. Please keep questions and support requests to the forum, so that other users with similar questions in the future may have an easier time finding them. We do our best to reply to everything there, but our team is small so sometimes it takes a few days.
