### ISSUE TITLE
How to deploy a Pyro model?

### ISSUE THREAD

**Issue by maulberto3** [pyro-ppl/pyro#3085]
I have gone through the official Pyro docs, but I haven't found it.

For example, how would the deployment of a guide model be?

Does a simple joblib of a guide model would work? Is it possible?

**Comment by eb8680** [comment]
Hi @maulberto3, please ask your question on [our forum](https://forum.pyro.ai/) so that other users with similar questions can find it more easily in the future. We use GitHub for bug reports, feature requests and other development-related discussion.
