### ISSUE TITLE
Possible typo in testing complexity

### ISSUE THREAD

**Issue by ivetasarfyova** [pyro-ppl/pyro#3096]
Hi, I noticed that the [Pyro documentation for SVGP model](https://github.com/pyro-ppl/pyro/blob/e2aad5ed70d20709bfdd7bc3f50eb7f87577081b/pyro/contrib/gp/models/vsgp.py#L44) states that the testing complexity is O(m^3) which contradicts the information in several GP related publications that SVGP has O(m^2) complexity for testing, e.g. Table 1 in [Understanding and Comparing Scalable Gaussian Process Regression for Big Data](https://www.researchgate.net/publication/328677184_Understanding_and_Comparing_Scalable_Gaussian_Process_Regression_for_Big_Data). Can you please clarify?

**Comment by martinjankowiak** [comment]
@ivetasarfyova gp prediction requires the kernel inverse. this is typically done with a cholesky decomposition. computing the cholesky factor is O(m^3). this only needs to be done once. with the cholesky factor in hand prediction then becomes O(m^2). so whether prediction is O(m^3) or O(m^2) depends on whether you want to include the one time cost of cholesky decomposition.

**Comment by ivetasarfyova** [comment]
Thank you for the explanation @martinjankowiak , that makes a lot more sense now. It would be really helpful to include this explanation in docs. If I understand it correctly, after the training arbitrary Pyro GP model, the inverse matrix is not stored within the model and has to be computed again while making predictions. Wouldn't it be better to re-use the already computed matrix inversion than to calculate it again? Or has this any other advantages than I'm not seeing? :)

**Comment by martinjankowiak** [comment]
well afaik the implementation in contrib.gp does [not cache](https://github.com/pyro-ppl/pyro/blob/e2aad5ed70d20709bfdd7bc3f50eb7f87577081b/pyro/contrib/gp/models/sgpr.py#L222) the cholesky factor so inference is in fact O(m^3) as stated in the docs. it would preferable to have a mechanism for this caching and a PR that implements this would no doubt be welcome. on the other hand m is typically somewhat moderate (m <= 1000) and so this cost is not terribly high. i wouldn't expect caching to make a terribly large practical difference unless you're doing lots and lots of predictions.

**Comment by ivetasarfyova** [comment]
Thanks so much, that cleared it up a lot :)
