### ISSUE TITLE
Incorrect noise addition in Gaussian processes [bug]

### ISSUE THREAD

**Issue by kdkalvik** [pyro-ppl/pyro#3106]
Please provide the following details:
--------------------------------------------------------------------------------------------------
### I think there is a bug in how we are adding noise and jitter to the covariance matrix in Gaussian processes (SGPs as well)
[Here is the line I am referencing](https://github.com/pyro-ppl/pyro/blob/f4b13ec784bd0ce81ef2f5fcdba0b9efd62e7cc2/pyro/contrib/gp/models/gpr.py#L135)

I noticed that sometimes I could not invert my covariance matrix, and I figured there might be a bug in how we add noise to stabilize the inversion.  So I wrote the following noise addition function (I converted GPFlow's TensorFlow [code ](https://github.com/GPflow/GPflow/blob/c42cd4772543dc0c3756620c8b407d8dbf2b2ee0/gpflow/utilities/model_utils.py#L12)to PyTorch)

```
def add_noise_cov(K, likelihood_variance):
    """
    Returns K + σ² I, where σ² is the likelihood noise variance and I is the corresponding identity
    matrix.
    """
    k_diag = torch.diag(K)
    s_diag = torch.ones_like(k_diag) * likelihood_variance
    return K.diagonal_scatter(k_diag + s_diag)
```

The results with the above code and the approach in pyro are different, and the above approach gives me the correct result. 

### Environment
For any bugs, please provide the following:
 - OS: WSL Ubuntu 20.04
 - Python version: 3.8.10.
 - PyTorch version: 1.11.0+cpu
 - Pyro version: 1.8.1

**Comment by kdkalvik** [comment]
@martinjankowiak, I see how you arrived at that conclusion, perhaps I should have added more context. Here is the current [code ](https://github.com/pyro-ppl/pyro/blob/f4b13ec784bd0ce81ef2f5fcdba0b9efd62e7cc2/pyro/contrib/gp/models/gpr.py#L133)in pyro 
```
        N = self.X.size(0)
        Kff = self.kernel(self.X).contiguous()
        Kff.view(-1)[:: N + 1] += self.jitter + self.noise  # add noise to the diagonal
        Lff = torch.linalg.cholesky(Kff)
```

The matrix Kff could be a diagonal matrix, but it is usually not the case. However, the noise term that is added to the covariance in Gaussian processes is a diagonal matrix. On top of that, we usually add additional jitter to the diagonal to ensure that the matrix is invertible. The function I provided adds noise and jitter to the diagonal, the same as the current implementation. My proposed change would look something like this 
```
        N = self.X.size(0)
        Kff = self.kernel(self.X)
        Kff = add_noise_cov(Kff, self.jitter + self.noise)  # add noise to diagonal
        Lff = torch.linalg.cholesky(Kff)
```

**Comment by martinjankowiak** [comment]
this code snippet passes fine on my system. does it not pass on yours?
```
import torch
from numpy.testing import assert_allclose

N = 3
x1 = torch.randn(N, N)
x2 = x1.clone()
x1 += torch.eye(N)
x2.view(-1)[::N + 1] += 1.0

delta = (x1 - x2).abs().max().item()
print("delta", delta)  # == 0.0
assert_allclose(x1.data.numpy(), x2.data.numpy())
```

**Comment by kdkalvik** [comment]
Hmmm, yes, it works fine on mine as well. Let me make an MRE and get back to you. Also, thank you for the quick responses ^_^

**Comment by kdkalvik** [comment]
Got it, the issue was on my end. I changed the value of N to something else, which made the diagonal updates in other parts of the matrix. @martinjankowiak thank you for looking into it :)
