### ISSUE TITLE
model_7 in `examples/contrib/funsor/hmm.py` may have a bug

### ISSUE THREAD

**Issue by amcpherson** [pyro-ppl/pyro#3117]
In the hmm example using funsor, model_7 may have a bug, `x_prev` is initialized but never updated.
https://github.com/pyro-ppl/pyro/blame/38facc126103ef77604d0d47dfde94839ad9dc69/examples/contrib/funsor/hmm.py#L610

**Comment by ordabayevy** [comment]
Nice catch! Would you like to submit a PR with the fix? If so could you also run `python examples/hmm.py -m 7 --funsor -n 1 --batch-size=10 --print-shapes` to see if there are any changes in the shapes of tensors?
