### ISSUE TITLE
Render deterministic functions of random variables

### ISSUE THREAD

**Issue by Eric-Bradford** [pyro-ppl/pyro#3134]
I would like to show variables explicitly using "render_model" that are functions of other variables. I tried using "deterministic" or "Delta distribution" for this purpose, but this seems to not propagate like other distributions, e.g. 

```python
def model(data):
    m = pyro.sample("m", dist.Normal(0, 1))
    sd = pyro.sample("sd", dist.Delta(m**2))
    with pyro.plate("N", len(data)):
        pyro.sample("obs", dist.Normal(m, sd), obs=data)
data = torch.ones(10)
pyro.render_model(model, model_args=(data,))
```

![image](https://user-images.githubusercontent.com/32679792/188665033-092838b2-ddf6-4240-809b-d3d6f6cc2212.png)

If I define sd as a normal distribution it shows the connection between sd and obs correctly, but with "Delta" the connection is not shown. How can I define sd as a function of m that would show this connection?

**Comment by fritzo** [comment]
Hi @Eric-Bradford this looks like a bug to me, let me take a look at what might be causing it...

**Comment by fritzo** [comment]
OK, this is not a bug, merely a historical design choice (pyro.infer.inspect originated as an inference tool that was concerned with only latent variables, hence it ignored deterministic dependencies).  I've started sketching support for this feature [in a branch](https://github.com/pyro-ppl/pyro/tree/render-deterministic) but it's a little more complex than I expected due to low-level provenance tracking issues.  Working on it...

**Comment by fritzo** [comment]
See also [this forum discussion](https://forum.pyro.ai/t/how-to-render-a-semi-supervised-model/4751/8)

**Comment by r3v1** [comment]
Have been any advances on this?

**Comment by fritzo** [comment]
I believe there has been no progress, but @eb8680 was looking into it around 6 months ago.

**Comment by r3v1** [comment]
Is there any plan to implement this in the short time? I've tried patching it somehow but I got lost...

**Comment by eb8680** [comment]
@r3v1 no, sorry, it's unlikely I/we will have the bandwidth to fix this ourselves any time soon. You're welcome to play around with the branch linked above and see if you can get it working yourself.

**Comment by r3v1** [comment]
Thanks anyway. I tried but it was quite difficult for me to understand what is going on behind the scenes, I would take it more deeply if I had some documentation, by the way, do you have any resources about?
