### ISSUE TITLE
Trouble Calling MCMC Multiple Times within Same Script

### ISSUE THREAD

**Issue by mlpotter** [pyro-ppl/pyro#3143]
### Issue Description
When I try to run MCMC twice within the same script, wrapped in a class object definition, I receive this error.

> Traceback (most recent call last):
>   File "/home/mpotter/Desktop/Survival_Analysis/main_mcmc_baseline.py", line 103, in <module>
>     clf.fit(None,t1_train,t2_train,y_train)
>   File "/home/mpotter/Desktop/Survival_Analysis/models.py", line 643, in fit
>     self.mcmc.run(t1, t2, y)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
>     return fn(*args, **kwargs)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/site-packages/pyro/infer/mcmc/api.py", line 563, in run
>     for x, chain_id in self.sampler.run(*args, **kwargs):
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/site-packages/pyro/infer/mcmc/api.py", line 333, in run
>     w.start()
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/home/mpotter/anaconda3/envs/lambdastack39/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: cannot pickle '_thread.lock' object

### Environment
For any bugs, please provide the following:
 - Ubuntu 20.04.3 LTS 
 - Python 3.9.0
 - PyTorch 1.12.1
 - Pyro 1.8.1

### Code Snippet
```
MCMC(self.nuts_kernel,
                         num_chains=self.num_of_chains,
                         num_samples=self.number_of_samples,
                         warmup_steps=self.burn_in_samples,mp_context='spawn').
```

**Comment by GStechschulte** [comment]
Hey @mlpotter, this is interesting. I know you said script, but just to make sure, you are running this class within a Python script (the main program being executed) and **not** a Jupyter Notebook correct? 

I had a similar problem, though not the same, when running MCMC with $> 1$ chains in a Jupyter Notebook. My error was also being thrown in the `multiprocessing` directory, albeit, with the `spawn.py` file. Here's the [link](https://forum.pyro.ai/t/attribute-error-when-setting-number-of-chains-greater-than-1-in-mcmc/4652) to my problem on the Pyro forum.

**Comment by mlpotter** [comment]
The main program being executed is not a Jupyter Notebook. I am importing into a script like main.py. 

I resolved the threadlock error by adding in main.py file `if __name__ == "__main__":`.

When running the same script in Windows, I received a pickling error that commonly appears in this issue boards with this code 

```
 def fit(self,X_train,X_val,y_train,y_val,t1_train,t1_val,t2_train,t2_val):
        self.nuts_kernel = NUTS(self.model)

        self.mcmc = MCMC(self.nuts_kernel,
                         num_chains=self.num_chains,
                         num_samples=self.number_of_samples,
                         warmup_steps=self.burn_in_samples)

        trace = poutine.trace(self.model).get_trace(X_train,t1_train,t2_train,y_train)
        trace.compute_log_prob()
        print(trace.format_shapes())

        self.mcmc.run(X_train, t1_train, t2_train, y_train)
```

> Traceback (most recent call last):
>   File "C:\Users\lpott\Desktop\MCMC_Survival_Analysis\main_mcmc.py", line 19, in <module>
>     clf.fit(X_train,None,y_train,None,t1_train,None,t2_train,None)
>   File "C:\Users\lpott\Desktop\MCMC_Survival_Analysis\models.py", line 98, in fit
>     self.mcmc.run(X_train, t1_train, t2_train, y_train)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\site-packages\pyro\poutine\messenger.py", line 12, in _context_wrap
>     return fn(*args, **kwargs)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\site-packages\pyro\infer\mcmc\api.py", line 563, in run
>     for x, chain_id in self.sampler.run(*args, **kwargs):
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\site-packages\pyro\infer\mcmc\api.py", line 333, in run
>     w.start()
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\multiprocessing\context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\multiprocessing\context.py", line 327, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\lpott\anaconda3\envs\DYAN\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> TypeError: cannot pickle 'module' object

But was able to resolve it by removing self assignments and adding a self assignment at the end of fit.

```
def fit(self,X_train,X_val,y_train,y_val,t1_train,t1_val,t2_train,t2_val):
        nuts_kernel = NUTS(self.model) 

        mcmc = MCMC(nuts_kernel, 
                         num_chains=self.num_chains,
                         num_samples=self.number_of_samples,
                         warmup_steps=self.burn_in_samples)

        trace = poutine.trace(self.model).get_trace(X_train,t1_train,t2_train,y_train)
        trace.compute_log_prob()
        print(trace.format_shapes())

        mcmc.run(X_train, t1_train, t2_train, y_train) 
        self.mcmc = mcmc # making the self statement at end after mcmc run does not give error
```
