### ISSUE TITLE
PyTorch 2.0 compatibility: Explicit PyTorch 1.x check causing issues with packages that depend on PyTorch / pyro (e.g. BoTorch)

### ISSUE THREAD

**Issue by danielrjiang** [pyro-ppl/pyro#3162]
### Issue Description
The explicit check for PyTorch 1.x here (https://github.com/pyro-ppl/pyro/blob/dev/pyro/distributions/torch_patch.py#L10) is causing problems when another package has a dependency on PyTorch + Pyro, since PyTorch is now at 2.0. For example, it is causing BoTorch tests to fail here (https://github.com/pytorch/botorch/pull/1551).

Could this check be removed to allow for PyTorch 2.0?

### Environment
Mac OS 11.7.1
Python 3.10
PyTorch 2.0
Pyro 1.8.3

### Code Snippet
https://github.com/pytorch/botorch/actions/runs/3659534850/jobs/6185642011

**Comment by fritzo** [comment]
Sure, thanks for pointing out this remnant from torch 0.x days.

Do y'all want a pyro-ppl release, or is #3164 enough?

**Comment by Balandat** [comment]
@danielrjiang how do you feel about testing against pyro dev (GH install) with torch nightlies? If that works we're probably ok without a release for now.

Thanks!

**Comment by Balandat** [comment]
@fritzo are there any plans to put out a new pyro-ppl soon? It would be nice to not have to work off the dev branch when doing (integration) testing on pytorch. Also the pytorch 2.0 release is coming up in March and you probably want to make sure not everything breaks for everyone using pyro when that release happens :)

**Comment by fritzo** [comment]
@Balandat sure, we can do a minor release of pyro-ppl

**Comment by fritzo** [comment]
done
