### ISSUE TITLE
Small typo in tutorial notebook on Normalizing Flows

### ISSUE THREAD

**Issue by felixschltr** [pyro-ppl/pyro#3176]
Hi,

there seems to be a small typo in the [tutorial notebook on normalizing flows](https://github.com/pyro-ppl/pyro/blob/dev/tutorial/source/normalizing_flows_i.ipynb) in section "Fixed Univariate Transforms in Pyro".

The log-absolute derivative of the exponential transform $y = g(x) = \exp(x)$ is stated as $\log(\vert\frac{dg}{dx}\vert)=y$ while it should rather be $\log(\vert\frac{dg}{dx}\vert)=x$ (see also the implementation of [torch.distributions.transforms.ExpTransform](https://pytorch.org/docs/master/_modules/torch/distributions/transforms.html#ExpTransform)).

**Comment by fritzo** [comment]
Yes, I think you're right:
```
g(x) = exp(x)
dg/dx = d/dx exp(x)
       = exp(x)
       > 0
|dg/dx| = dg/dx
        = exp(x)
log(|dg/dx|) = x
```
Typo fix is welcome 😄 !
