### ISSUE TITLE
Model Render fails when model args passed

### ISSUE THREAD

**Issue by KevinG1002** [pyro-ppl/pyro#3179]
### Issue Description

It seems that I am facing an issue when rendering my probabilistic model in pyro. 

I have tested my model ensuring the tensor dimensions are correct, independence within batches is well marked and dependencies between latent variables is established. After verifying all this, I wanted to render my probabilistic model using the `pyro.render_model` method. 

When I did this, however, my code fails due to a RunTime Error about tensor size mismatches in the provenance.py script within /pyro/ops. 

The curious thing here is that rendering works when *no* model arguments are passed (i.e. args are set to None). And even when I do pass arguments and execute my code step-by-step, no errors of this nature are raised within my model. So, this one is really a head scratcher for me which is why I was hoping you could help. 

For more context: the model args are lists of tensors containing the datasets I'm dealing with:
Arg_1: [torch.Size([10, 784, 128]), torch.Size([10, 128, 64]), torch.Size([10, 64, 10])]
Arg_2: [torch.Size([10, 128]), torch.Size([10, 64]), torch.Size([10, 10])]

### Environment
 - MacOS, Intel chip, Python 3.9.16
 - Torch version 1.13.0.
 - Pyro version 1.8.4

### Code Snippet
```
pyro.clear_param_store()
def mlp_pgm_final(weight_layer_dataset: list[torch.Tensor] = None, bias_layer_dataset: list[torch.Tensor] = None):
    dataset_len = weight_layer_dataset[0].size()[0] if weight_layer_dataset else 1
    layer_structure = (784, 128, 64, 10)
    weight_matrix_dims = [(layer_structure[i], layer_structure[i+1]) for i in range(len(layer_structure)-1)]
    bias_dims = [(layer_structure[k],1) for k in range(1,len(layer_structure))]
    x = torch.randn(dataset_len, 784,1)
    layer_idx = 0
    activations = []
    for _ in range(len(weight_matrix_dims)): # iterate over number of weight matrices 
        upper_bound = (1/layer_structure[layer_idx])**(1/2) * torch.ones(layer_structure[layer_idx])
        lower_bound = -upper_bound # define lower and upper bound for uniform distributions used to initialise weights for NNs
        b_upper_bound = (1/layer_structure[layer_idx+1]**(1/2)) * torch.ones(layer_structure[layer_idx+1])
        b_lower_bound = -b_upper_bound

        with pyro.plate(f"Layer_{layer_idx+1}", dataset_len, dim = -3):
            b = pyro.sample(f"b_{layer_idx+1}", dist.Uniform(b_lower_bound, b_upper_bound), obs = bias_layer_dataset[layer_idx] if bias_layer_dataset else None) # Sample b vector from uniform
            with pyro.plate(f"Layer_Weights_{layer_idx+1}", weight_matrix_dims[layer_idx][1], dim = -2) as j:
                w = pyro.sample(f"w_{layer_idx+1}", dist.Uniform(lower_bound, upper_bound), obs = weight_layer_dataset[layer_idx] if weight_layer_dataset else None) 
            
                
                if weight_layer_dataset:
                    act = torch.relu(torch.matmul(w.mT, x) + b.unsqueeze(-1))
                else:
                    b = b.permute(0,2,1).squeeze(-1)
                    act = torch.relu(torch.matmul(x.squeeze(),w.mT) + b).squeeze()
                
        with pyro.plate(f"Activations_{layer_idx+1}", 1, dim = -3):
            cov = torch.stack([torch.eye(bias_dims[layer_idx][0]) for _ in range(act.size()[0])], dim = 0)
            h_dist = dist.MultivariateNormal(act.squeeze(), cov)
            # print("Test Sample size", h_dist.sample().size())
            h = pyro.sample(f"h_{layer_idx +1}", h_dist).squeeze()
            # print("Latent Sample", h.size())
            x = h.unsqueeze(-1)
            layer_idx += 1


nn_list = [MLP() for _ in range(10)]       
layerwise_weight_datasets, layerwise_bias_datasets = layer_wise_dataset(nn_list)    
pyro.render_model(model=mlp_pgm_final, model_args=(layerwise_weight_datasets, layerwise_bias_datasets))
```

### Error Message I'm Getting
![image](https://user-images.githubusercontent.com/35625838/217869287-74f203d0-8dfa-477d-aae5-e82925cbf8a3.png)

**Comment by martinjankowiak** [comment]
it appears this issue was solved in the [forum](https://forum.pyro.ai/t/pyro-crashes-when-dealing-with-too-high-dimensional-graphs/4968), which incidentally would have been the best place to raise this issue in the first place.
