### ISSUE TITLE
About ValueError: Shape mismatch inside plate('data') 

### ISSUE THREAD

**Issue by Floyd809** [pyro-ppl/pyro#3183]
When Using Uber's open source PYRO to implement a fully connected layer Bayesian neural network, I receive the following error

![234_3](https://user-images.githubusercontent.com/83442112/219840759-eb03852b-c992-4180-bed1-e7c5652008e5.png)

`import torch
import random
import pandas as pd
import numpy as np
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data import DataLoader, TensorDataset
import matplotlib
from matplotlib import pyplot as plt
import tqdm
from tqdm import trange

#pip install pyro-ppl
import pyro
import pyro.nn
from pyro.nn import PyroModule
from pyro.nn import PyroSample
from pyro.distributions import Normal, Uniform
from pyro.optim import Adam
import pyro.infer
from pyro.infer import SVI, Trace_ELBO
from pyro.infer import autoguide

def building_dataset(ins_path, lab_path, train_volume, device):
  ins = pd.read_csv(ins_path)
  labs = pd.read_csv(lab_path)
  
  ins = np.array(ins)
  labs = np.array(labs)
  labs = labs[:,1].reshape(-1,10)

  data_volume = ins.shape[0]
  test_volume = data_volume - train_volume
  
  data_index = list(range(data_volume))
  train_index = random.sample(range(0, data_volume), train_volume)
  test_index = np.setdiff1d(data_index, train_index)

  train_data_ins = torch.from_numpy(ins[train_index, :])
  train_data_labs = torch.from_numpy(labs[train_index, :])
  
  test_data_ins = torch.from_numpy(ins[test_index, :])
  test_data_labs = torch.from_numpy(labs[test_index, :])
  
  train_set = TensorDataset(train_data_ins, train_data_labs)
  train_set = DataLoader(train_set, batch_size = train_volume, shuffle = True)
  
  test_set = TensorDataset(test_data_ins, test_data_labs)
  test_set = DataLoader(test_set, batch_size = test_volume, shuffle = True)

  return train_set, test_set

class bnn(PyroModule):
  def __init__(self):
    super(bnn, self).__init__()

    self.hidden_layer1 = PyroModule[nn.Linear](2, 100)
    self.hidden_layer1.weight = PyroSample(Normal(0.0, 1.0).expand([100, 2]).to_event(2))
    self.hidden_layer1.bias = PyroSample(Normal(0.0, 1.0).expand([100]).to_event(1))
    
    self.hidden_layer2 = PyroModule[nn.Linear](100, 100)
    self.hidden_layer2.weight = PyroSample(Normal(0.0, 1.0).expand([100, 100]).to_event(2))
    self.hidden_layer2.bias = PyroSample(Normal(0.0, 1.0).expand([100]).to_event(1))

    self.hidden_layer3 = PyroModule[nn.Linear](100, 10)
    self.hidden_layer3.weight = PyroSample(Normal(0.0, 1.0).expand([10, 100]).to_event(2))
    self.hidden_layer3.bias = PyroSample(Normal(0.0, 1.0).expand([10]).to_event(1))

    self.relu = nn.ReLU()
  
  def forward(self, x, y = None):
    x = x.reshape(-1, 2)#(100,2)
    x = self.relu(self.hidden_layer1(x))#100,100
    x = self.relu(self.hidden_layer2(x))#100,100
    
    mu = self.hidden_layer3(x).squeeze()#100,10

    
    sigma = pyro.sample('sigma', Uniform(0.0, 1.0).expand([10])) #10

    with pyro.plate('data',100 ):#x.shape[0]
      #obs = pyro.sample('obs', Normal(mu, sigma), obs = y)
      obs = pyro.sample("obs", Normal(mu, sigma), obs=y)
    return mu

def main():
  device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
  model = bnn()
  guide = autoguide.AutoDiagonalNormal(model)
  adam = Adam({'lr' : 1e-3})
  svi = SVI(model, guide, adam, loss = Trace_ELBO())

  pyro.clear_param_store()

  loss = []
  epoch = trange(20)
  ins_path = './inv_input_data.csv'
  labs_path = './inv_output_data.csv'
  train_set, test_set = building_dataset(ins_path, labs_path, 100, device)

  for i in epoch:
    for index, (ins, labs) in enumerate(train_set):
      ins = ins.reshape(-1,2).float()
      labs = labs.reshape(10,-1).float()
      l = svi.step(ins, labs)
if __name__ == '__main__':
      main( )`

**Comment by martinjankowiak** [comment]
hi @Floyd809 please ask your question in the [forum](https://forum.pyro.ai/). github issues are reserved for bug reports, feature requests, and the like.

in any case we recommend using [tyxe](https://github.com/TyXe-BDL/TyXe) to implement bayesian neural networks in pyro (instead of doing so in raw pyro).
