### ISSUE TITLE
Easy Enhancement: filepath instead of filename for pyro.render_model()

### ISSUE THREAD

**Issue by LysSanzMoreta** [pyro-ppl/pyro#3184]
Hi!

I am just wondering if it would be possible to have a small fix to the pyro.render_model() function, so that it can take a _filepath_ instead of a _filename_ to save the .pdf to. Right now the function removes the path from the name (not sure why):

```
    if filename is not None:
        filename = Path(filename)
        suffix = filename.suffix[1:]  # remove leading period from suffix
        graph.render(filename.stem, view=False, cleanup=True, format=suffix)
```

Thanks!

**Comment by fehiepsi** [comment]
Keeping the path sounds more reasonable to me. Do you want to submit the change?

**Comment by LysSanzMoreta** [comment]
Sure, let me have a look at it
