### ISSUE TITLE
When I define a new GPRegression, the kernel parameter is automatically overwritten by the kernel parameter of the previous GPRegression

### ISSUE THREAD

**Issue by pancratm** [pyro-ppl/pyro#3209]
### Issue Description
When I define a new GPRegression, the kernel parameter is automatically overwritten by the kernel parameter of the previous GPRegression. I checked the specific code and found that when training the new (second) GP to calculate loss or carry out ‘forward’ operation, kernel parameter would be overwritten by the first GP kernel parameter and would not be updated even if the parameters have gradients. This doesn't happen when I continue to train on top of this with the first GP, the parameters continue to update.
### Environment
python==3.7.4
torch==1.12.1
pyro-ppl==1.8.2
pyro-api==0.1.2

**Comment by fritzo** [comment]
This is happening because kernel parameters are stored in Pyro's global param store (`pyro.get_param_store()`).  To resolve this issue you could either:
1. call `pyro.clear_param_store()` before each run, or
2. run each model in a context manager
```python
with pyro.get_param_store().scope():
    # ...do stuff that will not leak outside of this context...
```
