### ISSUE TITLE
ParamStore save() function not working

### ISSUE THREAD

**Issue by SSchwoebel** [pyro-ppl/pyro#3225]
Hello,

I opened my code for the first time after an update and my previously working save to file of the ParamStore throws an error. I use the following code to save:
`pyro.get_param_store().save(fname)`

For which I get this error:
```
File <path_to_my_code>.py:2081 in save_parameters
    pyro.get_param_store().save(fname)

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/pyro/params/param_store.py:279 in save
    torch.save(self.get_state(), output_file)

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/serialization.py:441 in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/serialization.py:653 in _save
    pickler.dump(obj)

TypeError: cannot pickle 'weakref.ReferenceType' object
```

I am on Manjaro Linux using Anaconda for package management. Installed versions per Anaconda (conda list) are:
pytorch 2.0.0
pyro-ppl 1.8.4
pyro-api 0.1.2
python 3.11.3

I have tried rewriting the save command to `torch.save(pyro.get_param_store().get_state(), fname)` which (unsurprisingly) yields the same error.

Let me know, if there is any more information I can provide. Thank you!

**Comment by eb8680** [comment]
@SSchwoebel this should be fixed in the latest Pyro release (1.8.5)
