### ISSUE TITLE
Question about LDA example code.

### ISSUE THREAD

**Issue by whatever60** [pyro-ppl/pyro#3226]
Hi Pyro developers,

Thank you for maintaining this amazing project and the thorough documentation.

However, I do have two questions about the example code of amortized Latent Dirichlet Allocation.

1.
https://github.com/pyro-ppl/pyro/blob/ae124d51a9e88068b177656f430e33a41c7a39d4/examples/lda.py#LL96C1-L102C6

The comment at line 97 (repo tag 1.8.5) says it is using conjugate guide, but I think it is not conjugate since the posterior and prior are the same (in this case both Gamma or both Dirichlet, but neither Gamma or Dirichlet are conjugate of themselves). 

2.
https://github.com/pyro-ppl/pyro/blob/ae124d51a9e88068b177656f430e33a41c7a39d4/examples/lda.py#LL78C1-L94C1

From the way the neural network is constructed, it seems to take a histogram as input without normalizing it. The code certainly works but it is just not common practice for a neural net to take arbitrarily large integers as input. So is there rational around this? Is it just to keep the same as the reference?

Thank you,
Whatever60

**Comment by martinjankowiak** [comment]
@whatever60 can you please ask your question on the [forum](https://forum.pyro.ai/)? github issues are intended for bug reports, feature requests, etc
