### ISSUE TITLE
Switch to ruff for linting

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#3230]
Many projects in the Python community are moving to [ruff](https://github.com/astral-sh/ruff) for their linting, due to its speed and ability to fix some of the surfaced errors.  The speed is especially nice when integrated into IDEs like VS code.

It would be great if we could incrementally adopt ruff's checks, starting with 
- [ ] `E`, `F` for flake8
- [ ] `I` for isort
- [ ] see other checks [here](https://beta.ruff.rs/docs/rules/)

**Comment by Sameer-Pal** [comment]
hi @fritzo,
Is this issue open to contribute ?

**Comment by fritzo** [comment]
Absolutely @Sameer-Pal, any help is appreciated!
