### ISSUE TITLE
Possible bugs in the _dfs and topological_sort methods in trace_struct.py

### ISSUE THREAD

**Issue by hongseok-yang** [pyro-ppl/pyro#3244]
### Issue Description

I have been reading the source code of Pyro, and I think that the implementations of _dfs and topological_sort in trace_struct.py are likely to have errors.

Let me start with the implementation of _dfs, which is shown below:
```python
def _dfs(self, site, visited):
    if site in visited:
        return
    for s in self._succ[site]:
        for node in self._dfs(s, visited):
            yield node
    visited.add(site)
    yield site
```
Imagine that the graph is just a cycle. Then, I think that _dfs will not terminate. One easy fix is to move visited.add(site) above the for statement. Although _dfs is used only for dags in the implementation where this infinite-loop problem does not appear, I think that it is better to fix this error (if this is indeed an error) since fixing it is quite easy.

For the implementation of topological sort below:
```python
def topological_sort(self, reverse=False):
    """
    Return a list of nodes (site names) in topologically sorted order.

    :param bool reverse: Return the list in reverse order.
    :return: list of topologically sorted nodes (site names).
    """
    visited = set()
    top_sorted = []
    for s in self._succ:
        for node in self._dfs(s, visited):
            top_sorted.append(node)
    return top_sorted if reverse else list(reversed(top_sorted))
```
Now imagine a graph with four vertices v1, v2a, v2b, v3, and edges 

    v1 -> v2a -> v3
    v1 -> v2b -> v3

If the above function is run on this graph and self._succ happens to pick v1 first, the function can return the following list:

    v1, v2a, v3, v2b

But this is not a topological sort of the graph because there are edges going forward (v2a -> v3) and edges going backward (v2b -> v3)

Sorry for not following the formatting guideline and also for writing this issue in the text file format. I am not used to reporting an issue in GitHub.

**Comment by fritzo** [comment]
Hi @hongseok-yang you've convinced me there is a bug in the topological sort algorithm. We'd welcome a fix if you'd like to suggest one.

**Comment by martinjankowiak** [comment]
on the other hand if i add such a diamond structure

```[(1, 2), (1, 3), (2, 4), (3, 4)]```

to `tests/poutine/test_trace_struct.py::test_topological_sort` the tests still pass

**Comment by hongseok-yang** [comment]
Sorry. I was wrong. Martin is right. I missed the fact that the implementation of _dfs on a vertex v of a DAG first returns the set of all the reachable nodes of the vertex v, and then returns v itself. When I wrote my first message above, I wrongly thought that _dfs first returned v and then returned vertices reachable from v (excluding v) in some order. With the current postfix-like traversal of _dfs, I cannot find a problem in the current implementation of topological_sort. Sorry again for causing confusion and making you waste your time.

**Comment by martinjankowiak** [comment]
@hongseok-yang no problem more eyes are always welcome! 

btw if you're interested in `TraceGraph_ELBO` in particular here are some old notes that i wrote 6 (!) years ago that describe the basic logic (though a few details may have drifted since then).

[elbo.pdf](https://github.com/pyro-ppl/pyro/files/12137134/elbo.pdf)
