### ISSUE TITLE
Possible bug in poutine/trace_messenger.py, function identify_dense_edges

### ISSUE THREAD

**Issue by xrival** [pyro-ppl/pyro#3245]
Hi,

I found some strange code pattern in function identify_dense_edges, in file [poutine/trace_messenger.py](https://github.com/pyro-ppl/pyro/blob/dev/pyro/poutine/trace_messenger.py#L21).
I notice two sequential instances of:
`if site_is_subsample(node):
            continue`
The first one appears at line 17 (in the main loop of the function) and the second one at line 21 (in the nested loop).
It seems the second condition will never be reached; if it is, the first one would be selected, going to the next iteration of the main loop.

Should the second not be as follows ?
`if site_is_subsample(past_node):
            continue`

(this would be consistent with considering only pairs of non subsample nodes).

Thanks,

Regards,

Xavier

**Comment by fritzo** [comment]
Hi @xrival, indeed that line looks like a bug. Feel free to submit a one-line fix PR, or wait until we get around to fixing it ourselves. Many eyes 👀

**Comment by xrival** [comment]
Hi @fritzo,
Many thanks! I will try to do so in the next few days.

**Comment by fritzo** [comment]
Hi @xrival mind if I quick fix this to make it into our 1.8.6 release?  Thanks again for reporting it.

**Comment by xrival** [comment]
> Hi @xrival mind if I quick fix this to make it into our 1.8.6 release? Thanks again for reporting it.

Sure, no problem! I am traveling so I could not do it quick. Thanks for the quick replies and fix!
