### ISSUE TITLE
Docs builds are failing

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#3248]
Docs builds seem to have been failing since 1.8.5 release. We should fix this before the 1.8.6 release.

https://readthedocs.org/projects/pyro-ppl/builds/20847164/
<img width="812" alt="image" src="https://github.com/pyro-ppl/pyro/assets/648532/45149fae-a72d-481a-aaf9-73262d50aa92">

**Comment by fritzo** [comment]
hmm, still failing...
<img width="812" alt="image" src="https://github.com/pyro-ppl/pyro/assets/648532/57fd947d-5f98-432c-91ce-c03901634284">

**Comment by martinjankowiak** [comment]
have you seen some of this discussion? 
https://github.com/readthedocs/readthedocs.org/issues/10549
