### ISSUE TITLE
Bug in `CVAE` example

### ISSUE THREAD

**Issue by ordabayevy** [pyro-ppl/pyro#3273]
There is a bug in `CVAE` example. The `target` input to the `MaskedBCELoss` is not binary (it has values of -1, 0, 1). This was discovered by the PyTorch 2.1 update which started to validate the inputs of `F.binary_cross_entropy_loss`.

> FAILED tests/test_examples.py::test_cpu[cvae/main.py --num-quadrant-inputs=1 --num-epochs=1] - subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.8.18/x64/bin/python', '/home/runner/work/pyro/pyro/examples/cvae/main.py', '--num-quadrant-inputs=1', '--num-epochs=1']' returned non-zero exit status 1.
= 1 failed, 148 passed, 97 skipped, 26558 deselected, 2 warnings in 1948.89s (0:32:28) =

**Comment by FDUguchunhui** [comment]
In baseline.py:

Change code 
`
def forward(self, input, target):
        target = target.view(input.shape)
        loss = F.binary_cross_entropy(input, target, reduction='none')
        loss[target == self.masked_with] = 0
        return loss.sum()
`

to
`def forward(self, input, target):
        target = target.view(input.shape)
        # only calculate loss on target pixels (value = -1)
        loss = F.binary_cross_entropy(input[target != self.masked_with], target[target != self.masked_with], reduction='none')
        # loss[target == self.masked_with] = 0
        return loss.sum()
`

After that, I have successfully ran the code in python==2.2.0 and pyro=1.8.6

**Comment by ordabayevy** [comment]
@FDUguchunhui thank you! Could you submit a PR with the fix and remove the `pytest.mark.skip` in the test please?

https://github.com/pyro-ppl/pyro/blob/dev/tests/test_examples.py#L126-L129

**Comment by ordabayevy** [comment]
Hi @FDUguchunhui . We would like to have this fixed before the 1.9 release next week. If you can't get to it in the next couple of days I would be happy to fix it myself. Let me know.

**Comment by FDUguchunhui** [comment]
Hi Yerdos:

Sorry for the late reply. I will submit a pull request this weekend.

Thank you.

Best regards,
Chunhui

**Comment by FDUguchunhui** [comment]
A pull request has been submitted.

Thank you!

Best,
Chunhui
