### ISSUE TITLE
[docs] Distributions in docs but not in package

### ISSUE THREAD

**Issue by cyianor** [pyro-ppl/pyro#3279]
### Issue Description

There are distributions such as `MixtureSameFamily`, `Weibull` or `Wishart` that appear in the documentation but do not actually exist in `pyro.distributions` anymore (or so it seems). I can find some old issues about them but a code search here on GitHub or within pyro 1.8.6 does not give results.

Is this simply an issue of documentation having gone stale and not updated or am I missing something here?

### Environment

pyro 1.8.6

**Comment by fritzo** [comment]
Hi @cyianor, all of [MixtureSameFamily](https://pytorch.org/docs/stable/distributions.html#mixturesamefamily), [Weibull](https://pytorch.org/docs/stable/distributions.html#weibull), and [Wishart](https://pytorch.org/docs/stable/distributions.html#wishart) have been moved from pyro.distrubutions upstream to torch.distributions, and they should still be available as `pyro.distributions.MixtureSameFamily` etc via our [wrappers](https://github.com/pyro-ppl/pyro/blob/44ba2d2470b45a93a3ae951204becc194ef8346f/pyro/distributions/torch.py#L351).  Their docs have been moved from the "Pyro Distributions" section to the "PyTorch Distributions" section on https://docs.pyro.ai 
<img width="301" alt="image" src="https://github.com/pyro-ppl/pyro/assets/648532/fde2ea91-3859-4779-9265-947650ff1ca7">

For context, pyro.distributions was created before torch.distributions, and we and other teams have moved many of our distributions upstream. However some lesser-used more bespoke distributions remain in Pyro, where we are more concerned with testing and correctness, and less concerned with GPU performance than in torch.distributions.

**Comment by cyianor** [comment]
Oh ok, sorry! Failure on my part to grasp this properly. My IDE only showed me distributions that are available directly in pyro and a code search within pyro didn't lead to anything, so I just assumed they don't exist. I do manage to use them now, so all is as you say.

Thank you!
