### ISSUE TITLE
 [feature request], [discussion] Manual changes in the trace

### ISSUE THREAD

**Issue by pavleb** [pyro-ppl/pyro#3305]
### Main idea
Using ``poutine.mask`` offers a way of removing (masking) particular dimensions from the final trance log-likelihood calculation.
However, one should know the mask upfront.  I had an issue where I had to make sample first and then based on the values, I have to decide which dimensions should be masked. Details can be found in my [forum post](https://forum.pyro.ai/t/mask-a-sample-downstream/5777). The workaround that I made was to write my own ``Messenger`` that offers a way of altering the trace. The new messenger is simple, however the ``class Trace`` had to be upgraded with a new method:
```py
def edit_node(self, site_name, **kwargs):
        if site_name not in self:
            raise RuntimeError("Site {} not in trace".format(site_name))
        
        for key, value in kwargs.items():
            self.nodes[site_name][key] = value
```

The new messenger can be like:
```py
class ModifyMessenger(Messenger):
    def __init__(self, modify_attrs):
        super().__init__()
        self.modify_attrs = modify_attrs

    def _process_message(self, msg):
        msg['modify_attrs'] = self.modify_attrs
```
Finally in the ``class TraceMessenger`` method ``_pyro_post_sample`` can be upgraded to:
```py
 def _pyro_post_sample(self, msg):
        if self.param_only:
            return
        if msg["infer"].get("_do_not_trace"):
            assert msg["infer"].get("is_auxiliary")
            assert not msg["is_observed"]
            return
        if "modify_attrs" in msg:
            self.trace.edit_node(msg["name"], **msg["modify_attrs"])
        else:
            self.trace.add_node(msg["name"], **msg.copy())
```

I got the idea of late trace alteration from [this comment](https://github.com/pyro-ppl/pyro/blob/7d12015ea878456ff9f3283df42d25eeac43b5cd/pyro/poutine/trace_struct.py#L119C8-L119C69) in the code.

### Potential issues
I am aware that changing the trace by hand can lead to quite strange behaviour. However, maybe the ``ModifyMessenger`` can be limited to a subset of trace nodes, or some form of sanity check can be put in ``edit_node`` like function in the ``class Trace``.

**Comment by eb8680** [comment]
Hi @pavleb, thanks for the suggestion.

Because `TraceMessenger` and `Trace` are used so extensively throughout Pyro, we generally try to avoid adding or changing behavior there that could inadvertently impact other use cases unless there's no easy alternative.

In the use case in your forum post, I believe you can achieve the same behavior fairly straightforwardly within your model code by using the `Distribution.mask` method to defer the appropriate log-joint contributions to later calls to `pyro.factor`:
```py
a_dist: Distribution = ...
a = pyro.sample("a", a_dist.mask(False))
b_dist: Distribution = ...
b = pyro.sample("b", b_dist.mask(False))

mask: Tensor = get_mask(a, b)
pyro.factor("ab_a", a_dist.mask(mask).log_prob(a))
pyro.factor("ab_b", b_dist.mask(mask).log_prob(b))
```
Is there anything that would prevent you from using this or a similar workaround in your application?

**Comment by pavleb** [comment]
You are right, it is quite an elegant solution.
