### ISSUE TITLE
Add detailed descriptions of `Message` and `InferDict` keys

### ISSUE THREAD

**Issue by ordabayevy** [pyro-ppl/pyro#3322]
`Message` and `InferDict` were introduced for type annotations purposes. It would also be a great place to document the how messages are structured and the meanings of all their keys (can be taken from [here](https://pyro.ai/examples/effect_handlers.html#Inside-the-messages-sent-by-Messengers)).

**Comment by fritzo** [comment]
@ordabayevy I'm happy to do this, unless you're planning to do so. Just LMK so we can set an assignee

**Comment by ordabayevy** [comment]
Sure, that would be awesome.
