### ISSUE TITLE
[BUG] Coregionalize() kernel unable to be used

### ISSUE THREAD

**Issue by 2mLi** [pyro-ppl/pyro#3348]
Hello there, 

I'm recently implementing a multi-output GP regression problem using Pyro functionality, specifically the Coregionalize() kernel for capturing the between-output variation. 

For people who are not familiar with how this works in Pyro: GPs were defined by their kernel function which is therefore our modelling of interest. In Pyro each GP kernel usually takes two key arguments on initialisation that must be called: an `input_dim` which is an integer telling how many input dimensions there are; and an 'active_dims' which is a list indicating which dimensions of the input (called when initialising the 'model' after initialising the 'kernel') will be plugged into the kernel. For example if your input has 4 dimensions and you only want the kernel to be computed from the last 2 dimensions, the active dim should be [False, False, True, True] etc. Following the documentation on Pyro, multi-output GP problems using coregionalisation kernel should have the input structured such that the input_dim will be P + C, P being the original dimension of your input and C being a one-hot encoder dimension telling the Coregionalize() kernel which output each row of your input belongs to. Ideally, the coregionalize() kernel will be manipulating with the one-hot encoder bit only, which is a matrix with column number C. 

The problem comes with this Coregionalize() kernel being different from other kernels and this I believe has caused bugs. When initialising the coregionalize kernel initialises a matrix called `component` (in maths term this matrix maps some low-dimensional latent GPs to our interested GPs). Problem is, this component matrix has row equals to the input dimension - the dimension of the original input. Following notations from the previous paragraph, mathematically we want a `component` with row number C, so it could be matrix-multiplied with the one-hot encoder part of our input with column number C; but the kernel initialised a `component` with row number P+C. Therefore when I execute the code the Coregionalize() kernel could never be forward()-ed and the error message keeps saying the stuff I described above. I add a line modifying the initialization of Coregionalize() telling the `component` to have row number equal to input_dim * active_dims (essentially telling it to have rows equal to sum(active_dims)) and my script runs without any issue afterwards. 

I wonder if I have misused this Coregionalize() function, or if not, if the function is bugged? Has anyone else used this matrix and encountered the same problem? 

Thanks in advance for any help. Sorry if you feel the description is unclear - I really cannot find a more elegant way to describe the problem. Feel free to chase up if you need more description.

**Comment by fritzo** [comment]
Hi @2mLi could you provide some code reproducing your error and the actual error messages?

Do you have any idea why your error does not arise in [existing tests](https://github.com/pyro-ppl/pyro/blob/0dc635f85650fa48ee5fbdc74d4053942d78caa1/tests/contrib/gp/test_kernels.py#L63-L86)?

**Comment by 2mLi** [comment]
> Hi @2mLi could you provide some code reproducing your error and the actual error messages?
> 
> Do you have any idea why your error does not arise in [existing tests](https://github.com/pyro-ppl/pyro/blob/0dc635f85650fa48ee5fbdc74d4053942d78caa1/tests/contrib/gp/test_kernels.py#L63-L86)?

Thank you for your reply - I think the problem is solved. I think I did not specify the parameter `active_dims` and `input_dim` in the Pyro's fashion and this example has given the best illustration. 

Thank you for your time and I think this issue could be closed for now.
