### ISSUE TITLE
How to confirm the training is converged?

### ISSUE THREAD

**Issue by AmosJoseph** [pyro-ppl/pyro#3359]
Pardon! I trained a ML model and then test it with good accracy:
MSE is 0.065， MAE is 0.157， R^2 is 0.964。

![1713541626181](https://github.com/pyro-ppl/pyro/assets/40055065/40b4abe5-28ef-4c09-8b4b-d4e79714d783)

As for the above training plot, is the training is converged?

Best!

**Comment by fritzo** [comment]
@AmosJoseph Could you please ask on https://forum.pyro.ai, so that we may reserve github issues for code discussion? Thanks!
