### ISSUE TITLE
E-Mail in CODE_OF_CONDUCT.md probably not correct any more?

### ISSUE THREAD

**Issue by andife** [pyro-ppl/pyro#3381]
E-Mail in CODE_OF_CONDUCT.md probably not correct any more?

**Comment by Swarnim114** [comment]
@fritzo 
can i fix this?
can u please tell me the correct email?

**Comment by fritzo** [comment]
@Swarnim114 sure, thanks. You can use my personal email fritz.obermeyer@gmail.com. Or if you want to complain about me, you can find a sympathetic ear in Du Phan, fehiepsi@gmail.com . Probably best to add both 🙂
