### ISSUE TITLE
Implement LowerPoutine : sample -> param+observe

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#577]
MAP estimation requires a `param`+`observe` pattern for each estimated parameter in the `model` (see #573 ). This is awkward. We should instead provide something like a `poutine.lower()` to automatically transform `sample` sites in this way. This will require some refactoring of `Poutine` and `apply_stack`, since current poutines are restricted to 1-1 site transformations, whereas `poutine.lower()` needs to transform one `sample` site into two sites.

**Comment by fritzo** [comment]
@eb8680 Do you have any interest in refactoring to allow Poutines to perform one-to-many site transforms? If not I might do it this weekend.

**Comment by fritzo** [comment]
@nbren12 Hopefully this would allow you to write simpler models.

**Comment by eb8680** [comment]
> Do you have any interest in refactoring to allow Poutines to perform one-to-many site transforms?

@fritzo you shouldn't need to refactor anything.  You're free to call `sample`/`observe`/`param` within the evaluation of a site, as long as those calls all respect our global rules of naming.  In this case, you could just give the parameter site a different name by adding a prefix or suffix.

**Comment by fritzo** [comment]
Oh great, if that's the case I might just add `poutine.lift` to #573.

**Comment by fritzo** [comment]
I believe this is accomplished now by `AutoDelta`
