### ISSUE TITLE
HMC/NUTS Tutorial and Example

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#979]
Let us have a tutorial and example that uses HMC / NUTS. Right now, the only way to see working examples is looking at the tests.

- [x] Example (#1080 )
- [ ] Tutorial

**Comment by Jakedismo** [comment]
How did you wrangle the example dataset to run this example? Converted the dataframe to an array or columns to tensor variables?

**Comment by fritzo** [comment]
Removing from 0.3 milestone, since we already have HMC/NUTS in Bayesian Regression part II #1630 and in the jit tutorial. I'll leave this open for the baseball tutorial.
